import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const expectedNamedExports = [
  "Address",
  "AssemblePartialWitnessOptions",
  "AssetUnit",
  "Assets",
  "AttachApi",
  "AuthoredOutput",
  "AwaitTxOptions",
  "BuilderInvariantError",
  "BuilderScriptState",
  "BuilderSnapshot",
  "ChainOptions",
  "ChainResult",
  "CmlValue",
  "CompleteOptions",
  "CompleteTx",
  "CompleteTxMetadata",
  "CompleteTxSignApi",
  "Datum",
  "DatumOfOptions",
  "DatumWitness",
  "DecodedMidgardOutput",
  "ExUnits",
  "ExternalBodyHashSigner",
  "FromTxInput",
  "FromTxOptions",
  "InsufficientFundsError",
  "LocalPreflightOptions",
  "LocalPreflightPhase",
  "LocalValidationPreState",
  "LocalValidationPreStateSource",
  "LocalValidationRejectedTx",
  "LocalValidationReport",
  "LucidMidgard",
  "LucidMidgardConfig",
  "LucidMidgardConfigSnapshot",
  "LucidMidgardError",
  "MidgardEffect",
  "MidgardFetch",
  "MidgardNodeProvider",
  "MidgardNodeProviderOptions",
  "MidgardPartialWitnessBundle",
  "MIDGARD_PROTECTED_ADDRESS_HEADER_MASK",
  "MidgardProtocolInfo",
  "MidgardProtocolParameters",
  "MidgardProvider",
  "MidgardResult",
  "MidgardDatum",
  "MidgardOutRef",
  "MidgardScript",
  "MidgardTxOutput",
  "MidgardTxJson",
  "MidgardUtxo",
  "MidgardV1Validator",
  "MidgardWallet",
  "MintAssets",
  "MintIntent",
  "MintingPolicy",
  "ObserverIntent",
  "ObserverValidator",
  "OutRef",
  "OutputDatum",
  "OutputKind",
  "OutputOptions",
  "PartialSignApi",
  "PartialWitnessBundleInput",
  "PartiallySignedTx",
  "PayApi",
  "PlutusDataLike",
  "PlutusV3Validator",
  "PrivateKey",
  "ProtocolInfoFallback",
  "ProtocolScriptLanguage",
  "ProviderCapabilityError",
  "ProviderDiagnostics",
  "ProviderError",
  "ProviderHttpError",
  "ProviderPayloadError",
  "ProviderTransportError",
  "ReadFromOptions",
  "ReceiveRedeemerIntent",
  "Redeemer",
  "ReferenceInputIntent",
  "SUBMIT_ADMISSION_STATUS_VALUES",
  "ScriptLanguage",
  "ScriptPurpose",
  "ScriptRefLike",
  "ScriptSource",
  "SigningError",
  "SpendInputIntent",
  "SpendingValidator",
  "SubmitAdmissionStatus",
  "SubmitOptions",
  "SubmitTxResult",
  "SubmittedTx",
  "SupportedValidator",
  "SupportedValidatorLanguage",
  "SwitchProviderOptions",
  "TrustedReferenceScriptMetadata",
  "TxHash",
  "TxBuilder",
  "TxPartialSignBuilder",
  "TxStatus",
  "TxStatusKind",
  "UtxosByOutRefOptions",
  "VKeyWitness",
  "VKeyWitnessInput",
  "ValueLike",
  "WalletInputSource",
  "WalletNetworkValidation",
  "addAssets",
  "addressNetworkId",
  "assertAddressNetwork",
  "assertNonNegativeAssets",
  "assertVKeyWitness",
  "assetQuantity",
  "assetsToCmlValue",
  "assetsToLucidAssets",
  "authoredOutput",
  "cmlValueToAssets",
  "compareOutRefs",
  "decodeMidgardTxOutput",
  "decodeMidgardUtxo",
  "decodePartialWitnessBundle",
  "dedupeOutRefs",
  "emptyBuilderScriptState",
  "encodeMidgardTxOutput",
  "encodePartialWitnessBundle",
  "isSubmitAdmissionStatus",
  "isZeroAssets",
  "makeMidgardTxOutput",
  "makeVKeyWitness",
  "normalizeAssets",
  "normalizeOutRef",
  "normalizeOutputDatum",
  "normalizePlutusData",
  "normalizeScriptRef",
  "normalizeTxHash",
  "normalizeValueLike",
  "outRefLabel",
  "outRefToCbor",
  "outputAddressPaymentKeyHash",
  "outputAddressPaymentScriptHash",
  "outputAddressProtected",
  "parseOutRefLabel",
  "parsePartialWitnessBundle",
  "paymentKeyHashFromAddress",
  "protectMidgardOutputCbor",
  "subtractAssets",
  "utxoAddress",
  "utxoAssets",
  "utxoOutRefCbor",
  "utxoOutputCbor",
  "utxoProtectedAddress",
  "valueLikeToCmlValue",
  "verifyVKeyWitness",
  "walletFromExternalSigner",
  "walletFromPrivateKey",
  "walletFromSeedPhrase",
].sort();

const parseNamedExports = (declarationText: string): readonly string[] => {
  const matches = [
    ...declarationText.matchAll(
      /export\s+\{([^}]*)\}(?:\s+from\s+['"][^'"]+['"])?;/gs,
    ),
  ];
  if (matches.length === 0) {
    throw new Error("missing named export block");
  }
  return [
    ...new Set(
      matches.flatMap((match) =>
        match[1]!
          .split(",")
          .map((entry) => entry.trim().replace(/^type /, ""))
          .map(
            (entry) =>
              entry
                .split(/\s+as\s+/)
                .at(-1)
                ?.trim() ?? entry,
          )
          .filter((entry) => entry.length > 0),
      ),
    ),
  ].sort();
};

describe("public API export snapshot", () => {
  it("keeps the built declaration export set intentional", () => {
    const declarationText = readFileSync(
      resolve(import.meta.dirname, "../dist/index.d.ts"),
      "utf8",
    );
    expect(declarationText).toContain(
      "export * from '@al-ft/midgard-core/codec'",
    );
    expect(parseNamedExports(declarationText)).toEqual(expectedNamedExports);
  });
});
