import "node:fs";
import "@al-ft/midgard-test-support/hex";
import "@lucid-evolution/lucid";
import "effect";
import "vitest";
import "../src/index.js";
import "./da-attestation-rotation.make-fixture.js";
import "./da-attestation-rotation.q62-da-redeemer-constructor-abi.js";
import "./da-attestation-rotation.q63c-rescue-builder.js";
