import { describe, expect, it } from "vitest";

import {
  CANONICAL_DECODABILITY_FRAUD_CATEGORY_ID,
  COMMITTED_FIELD_SHAPE_FRAUD_CATEGORY_ID,
  CROSS_BLOCK_DUPLICATE_EVENT_FRAUD_CATEGORY_ID,
  DISTINCT_ASSET_ACCUMULATION_LIMIT_FRAUD_CATEGORY_ID,
  DOUBLE_WITHDRAW_FRAUD_CATEGORY_ID,
  EXECUTION_NATIVE_SCRIPT_INVALID_FRAUD_CATEGORY_ID,
  EXECUTION_SOURCE_SCRIPT_DECODING_FRAUD_CATEGORY_ID,
  FABRICATED_DEPOSIT_FRAUD_CATEGORY_ID,
  FABRICATED_WITHDRAWAL_FRAUD_CATEGORY_ID,
  FIELD_ITEM_WIDTH_ILLEGAL_FRAUD_CATEGORY_ID,
  FIELD_PREIMAGE_LENGTH_MISMATCH_FRAUD_CATEGORY_ID,
  FRAUD_PROOF_CATALOGUE_CATEGORY_IDS,
  FRAUD_PROOF_CATALOGUE_CATEGORY_ORDER,
  INPUT_SET_UNIQUENESS_FRAUD_CATEGORY_ID,
  L2_TX_MISTAG_FRAUD_CATEGORY_ID,
  MIN_ADA_FRAUD_CATEGORY_ID,
  MIN_FEE_FRAUD_CATEGORY_ID,
  MINT_AUTHORIZATION_FRAUD_CATEGORY_ID,
  MINT_DECLARED_ASSET_LIMIT_FRAUD_CATEGORY_ID,
  MISSING_NATIVE_SCRIPT_TX_FRAUD_CATEGORY_ID,
  MISSING_NATIVE_SCRIPT_UTXO_FRAUD_CATEGORY_ID,
  MISSING_REDEEMER_FRAUD_CATEGORY_ID,
  MISSING_SCRIPT_SOURCE_FRAUD_CATEGORY_ID,
  MISSING_SIGNATURE_FRAUD_CATEGORY_ID,
  NATIVE_SCRIPT_DECODING_FRAUD_CATEGORY_ID,
  NATIVE_SCRIPT_INVALID_FRAUD_CATEGORY_ID,
  NETWORK_ID_FRAUD_CATEGORY_ID,
  OBSERVER_ORDER_INVALID_FRAUD_CATEGORY_ID,
  OBSERVERS_FORBIDDEN_ON_UNTAGGED_NETWORK_FRAUD_CATEGORY_ID,
  OUTPUT_REFERENCE_SCRIPT_DECODING_FRAUD_CATEGORY_ID,
  PROTECTED_OUTPUT_SIGNER_MISSING_FRAUD_CATEGORY_ID,
  RECEIVE_PURPOSE_LANGUAGE_FRAUD_CATEGORY_ID,
  REDEEMER_CANONICITY_FRAUD_CATEGORY_ID,
  RESOLVED_OUTPUT_NON_CANONICAL_FRAUD_CATEGORY_ID,
  SCRIPT_INTEGRITY_HASH_MISMATCH_FRAUD_CATEGORY_ID,
  SCRIPT_INTEGRITY_HASH_MISSING_FRAUD_CATEGORY_ID,
  SPEND_INPUT_SIGNER_MISSING_FRAUD_CATEGORY_ID,
  TRANSACTION_OUTPUT_NON_CANONICAL_FRAUD_CATEGORY_ID,
  UNUSED_REDEEMER_FRAUD_CATEGORY_ID,
  UNUSED_SCRIPT_WITNESS_FRAUD_CATEGORY_ID,
  VALUE_NOT_PRESERVED_FRAUD_CATEGORY_ID,
  WITHDRAWAL_MISTAG_FRAUD_CATEGORY_ID,
  WITHDRAWN_INPUT_FRAUD_CATEGORY_ID,
  WITHDRAWN_REFERENCE_INPUT_FRAUD_CATEGORY_ID,
  WITNESS_SCRIPT_DECODING_FRAUD_CATEGORY_ID,
} from "../src/index.js";

describe("production fraud-proof catalogue registration", () => {
  it("pins the append-only category order and sparse four-byte ids", () => {
    expect(FRAUD_PROOF_CATALOGUE_CATEGORY_ORDER).toEqual([
      "doubleSpend",
      "nonExistentInput",
      "nonExistentInputNoIndex",
      "invalidRange",
      "transitionTrace",
      "zeroInput",
      "validationTraceDispute",
      "daHashPreimage",
      "noReferenceInput",
      "referenceInputNoIdx",
      "invalidSignature",
      "fabricatedDeposit",
      "fabricatedWithdrawal",
      "nativeScriptDecoding",
      "missingSignature",
      "missingNativeScriptTx",
      "withdrawnReferenceInput",
      "canonicalDecodability",
      "committedFieldShape",
      "minFee",
      "withdrawalMistag",
      "doubleWithdraw",
      "crossBlockDuplicateEvent",
      "l2TxMistag",
      "withdrawnInput",
      "valueNotPreserved",
      "inputSetUniqueness",
      "mintAuthorization",
      "networkId",
      "missingNativeScriptUtxo",
      "nativeScriptInvalid",
      "minAda",
      "fieldPreimageLengthMismatch",
      "fieldItemWidthIllegal",
      "witnessScriptDecoding",
      "scriptIntegrityHashMissing",
      "transactionOutputNonCanonical",
      "resolvedOutputNonCanonical",
      "mintDeclaredAssetLimit",
      "spendInputSignerMissing",
      "protectedOutputSignerMissing",
      "observersForbiddenOnUntaggedNetwork",
      "observerOrderInvalid",
      "redeemerCanonicity",
      "outputReferenceScriptDecoding",
      "executionSourceScriptDecoding",
      "receivePurposeLanguage",
      "unusedScriptWitness",
      "missingScriptSource",
      "missingRedeemer",
      "unusedRedeemer",
      "executionNativeScriptInvalid",
      "scriptIntegrityHashMismatch",
      "distinctAssetAccumulationLimit",
    ]);

    expect(Object.keys(FRAUD_PROOF_CATALOGUE_CATEGORY_IDS)).toEqual(
      FRAUD_PROOF_CATALOGUE_CATEGORY_ORDER,
    );
    const ids = FRAUD_PROOF_CATALOGUE_CATEGORY_ORDER.map(
      (name) => FRAUD_PROOF_CATALOGUE_CATEGORY_IDS[name],
    );
    expect(ids.every((id) => /^[0-9a-f]{8}$/u.test(id))).toBe(true);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it("exports canonical ids for every newly registered family", () => {
    expect({
      fabricatedDeposit: FABRICATED_DEPOSIT_FRAUD_CATEGORY_ID,
      fabricatedWithdrawal: FABRICATED_WITHDRAWAL_FRAUD_CATEGORY_ID,
      nativeScriptDecoding: NATIVE_SCRIPT_DECODING_FRAUD_CATEGORY_ID,
      missingSignature: MISSING_SIGNATURE_FRAUD_CATEGORY_ID,
      missingNativeScriptTx: MISSING_NATIVE_SCRIPT_TX_FRAUD_CATEGORY_ID,
      withdrawnReferenceInput: WITHDRAWN_REFERENCE_INPUT_FRAUD_CATEGORY_ID,
      canonicalDecodability: CANONICAL_DECODABILITY_FRAUD_CATEGORY_ID,
      committedFieldShape: COMMITTED_FIELD_SHAPE_FRAUD_CATEGORY_ID,
      minFee: MIN_FEE_FRAUD_CATEGORY_ID,
      withdrawalMistag: WITHDRAWAL_MISTAG_FRAUD_CATEGORY_ID,
      doubleWithdraw: DOUBLE_WITHDRAW_FRAUD_CATEGORY_ID,
      crossBlockDuplicateEvent: CROSS_BLOCK_DUPLICATE_EVENT_FRAUD_CATEGORY_ID,
      l2TxMistag: L2_TX_MISTAG_FRAUD_CATEGORY_ID,
      withdrawnInput: WITHDRAWN_INPUT_FRAUD_CATEGORY_ID,
      valueNotPreserved: VALUE_NOT_PRESERVED_FRAUD_CATEGORY_ID,
      inputSetUniqueness: INPUT_SET_UNIQUENESS_FRAUD_CATEGORY_ID,
      mintAuthorization: MINT_AUTHORIZATION_FRAUD_CATEGORY_ID,
      networkId: NETWORK_ID_FRAUD_CATEGORY_ID,
      missingNativeScriptUtxo: MISSING_NATIVE_SCRIPT_UTXO_FRAUD_CATEGORY_ID,
      nativeScriptInvalid: NATIVE_SCRIPT_INVALID_FRAUD_CATEGORY_ID,
      minAda: MIN_ADA_FRAUD_CATEGORY_ID,
      fieldPreimageLengthMismatch:
        FIELD_PREIMAGE_LENGTH_MISMATCH_FRAUD_CATEGORY_ID,
      fieldItemWidthIllegal: FIELD_ITEM_WIDTH_ILLEGAL_FRAUD_CATEGORY_ID,
      witnessScriptDecoding: WITNESS_SCRIPT_DECODING_FRAUD_CATEGORY_ID,
      scriptIntegrityHashMissing:
        SCRIPT_INTEGRITY_HASH_MISSING_FRAUD_CATEGORY_ID,
      transactionOutputNonCanonical:
        TRANSACTION_OUTPUT_NON_CANONICAL_FRAUD_CATEGORY_ID,
      resolvedOutputNonCanonical:
        RESOLVED_OUTPUT_NON_CANONICAL_FRAUD_CATEGORY_ID,
      mintDeclaredAssetLimit: MINT_DECLARED_ASSET_LIMIT_FRAUD_CATEGORY_ID,
      spendInputSignerMissing: SPEND_INPUT_SIGNER_MISSING_FRAUD_CATEGORY_ID,
      protectedOutputSignerMissing:
        PROTECTED_OUTPUT_SIGNER_MISSING_FRAUD_CATEGORY_ID,
      observersForbiddenOnUntaggedNetwork:
        OBSERVERS_FORBIDDEN_ON_UNTAGGED_NETWORK_FRAUD_CATEGORY_ID,
      observerOrderInvalid: OBSERVER_ORDER_INVALID_FRAUD_CATEGORY_ID,
      redeemerCanonicity: REDEEMER_CANONICITY_FRAUD_CATEGORY_ID,
      outputReferenceScriptDecoding:
        OUTPUT_REFERENCE_SCRIPT_DECODING_FRAUD_CATEGORY_ID,
      executionSourceScriptDecoding:
        EXECUTION_SOURCE_SCRIPT_DECODING_FRAUD_CATEGORY_ID,
      receivePurposeLanguage: RECEIVE_PURPOSE_LANGUAGE_FRAUD_CATEGORY_ID,
      unusedScriptWitness: UNUSED_SCRIPT_WITNESS_FRAUD_CATEGORY_ID,
      missingScriptSource: MISSING_SCRIPT_SOURCE_FRAUD_CATEGORY_ID,
      missingRedeemer: MISSING_REDEEMER_FRAUD_CATEGORY_ID,
      unusedRedeemer: UNUSED_REDEEMER_FRAUD_CATEGORY_ID,
      executionNativeScriptInvalid:
        EXECUTION_NATIVE_SCRIPT_INVALID_FRAUD_CATEGORY_ID,
      scriptIntegrityHashMismatch:
        SCRIPT_INTEGRITY_HASH_MISMATCH_FRAUD_CATEGORY_ID,
      distinctAssetAccumulationLimit:
        DISTINCT_ASSET_ACCUMULATION_LIMIT_FRAUD_CATEGORY_ID,
    }).toEqual({
      fabricatedDeposit: "0000000b",
      fabricatedWithdrawal: "0000000c",
      nativeScriptDecoding: "0000000d",
      missingSignature: "0000000e",
      missingNativeScriptTx: "0000000f",
      withdrawnReferenceInput: "00000010",
      canonicalDecodability: "00000011",
      committedFieldShape: "00000012",
      minFee: "00000013",
      withdrawalMistag: "00000014",
      doubleWithdraw: "00000015",
      crossBlockDuplicateEvent: "00000016",
      l2TxMistag: "00000017",
      withdrawnInput: "00000018",
      valueNotPreserved: "00000019",
      inputSetUniqueness: "0000001a",
      mintAuthorization: "0000001b",
      networkId: "0000001c",
      missingNativeScriptUtxo: "0000001d",
      nativeScriptInvalid: "0000001e",
      minAda: "0000001f",
      fieldPreimageLengthMismatch: "00000020",
      fieldItemWidthIllegal: "00000021",
      witnessScriptDecoding: "00000022",
      scriptIntegrityHashMissing: "00000023",
      transactionOutputNonCanonical: "00000029",
      resolvedOutputNonCanonical: "00000026",
      mintDeclaredAssetLimit: "0000002c",
      spendInputSignerMissing: "00000027",
      protectedOutputSignerMissing: "0000002b",
      observersForbiddenOnUntaggedNetwork: "00000024",
      observerOrderInvalid: "00000025",
      redeemerCanonicity: "00000028",
      outputReferenceScriptDecoding: "0000002a",
      executionSourceScriptDecoding: "00000031",
      receivePurposeLanguage: "00000034",
      unusedScriptWitness: "0000002f",
      missingScriptSource: "0000002d",
      missingRedeemer: "0000002e",
      unusedRedeemer: "00000030",
      executionNativeScriptInvalid: "00000032",
      scriptIntegrityHashMismatch: "00000033",
      distinctAssetAccumulationLimit: "00000035",
    });
  });
});
