import { readFileSync } from "node:fs";

import { Constr, Data } from "@lucid-evolution/lucid";
import { describe, expect, it } from "vitest";

import { ValidationAuxiliaryWitnessSchema } from "../src/fraud-proof/validation-auxiliary-witness.js";

type GeneratedAuxiliaryFixture = {
  readonly constructors: readonly {
    readonly tag: number;
    readonly arity: number;
    readonly cbor: string;
  }[];
  readonly corpusCbor: string;
  readonly corpusBlake2b256: string;
  readonly corpusSha256: string;
};

const auxiliaryFixture = JSON.parse(
  readFileSync(
    new URL(
      "../../midgard-validation/tests/fixtures/validation-auxiliary-witness-v1.generated.json",
      import.meta.url,
    ),
    "utf8",
  ),
) as GeneratedAuxiliaryFixture;

const CorpusSchema = Data.Array(ValidationAuxiliaryWitnessSchema);

const canonicalRawWitnesses = (): Constr<unknown>[] => {
  const raw = Data.from(auxiliaryFixture.corpusCbor);
  if (
    !Array.isArray(raw) ||
    !raw.every((witness) => witness instanceof Constr)
  ) {
    throw new Error("canonical auxiliary corpus is not a constructor list");
  }
  return raw as Constr<unknown>[];
};

/**
 * The corpus is generated by `midgard-validation`'s encoder
 * (`scripts/generate-validation-auxiliary-witness-v1-fixture.mjs`, wired into
 * CI as `fixtures:validation-auxiliary-witness-v1:check`), which emits both
 * this JSON and the on-chain
 * `validation-auxiliary-witness-v1-abi-generated.ak`. The SDK schema exercised
 * here is a second implementation of the same ABI, so agreement across the two
 * is the oracle. The arity cases below state the exactness of that ABI as a
 * property over every tag rather than transcribing four constructors' field
 * lists, which had to be hand-edited on any legitimate rename.
 */
describe("ValidationAuxiliaryWitnessSchema", () => {
  it("round-trips the canonical 40-constructor V1 corpus exactly", () => {
    const decoded = Data.from(auxiliaryFixture.corpusCbor, CorpusSchema);
    expect(Data.to(decoded, CorpusSchema)).toBe(auxiliaryFixture.corpusCbor);

    const raw = canonicalRawWitnesses();
    expect(raw).toHaveLength(auxiliaryFixture.constructors.length);
    expect(raw).toHaveLength(40);
    raw.forEach((witness, tag) => {
      const declared = auxiliaryFixture.constructors[tag]!;
      expect(witness.index).toBe(tag);
      expect(witness.fields).toHaveLength(declared.arity);
      // The generator records each constructor's own bytes as well as the
      // concatenated corpus; comparing per tag localises a divergence to the
      // constructor that moved instead of reporting one 40-element mismatch.
      expect(Data.to(witness as never), `tag ${tag.toString()}`).toBe(
        declared.cbor,
      );
    });
  });

  it("holds every constructor to its exact declared arity", () => {
    // What the deleted source-text field lists were protecting: no witness
    // constructor may quietly grow or lose a field. Stated over all 40 tags,
    // this needs no hand edit when a field is legitimately renamed, and still
    // fails when one is added or dropped.
    const raw = canonicalRawWitnesses();
    const accepts = (value: Constr<unknown>): boolean => {
      try {
        Data.from(Data.to(value as never), ValidationAuxiliaryWitnessSchema);
        return true;
      } catch {
        return false;
      }
    };

    const widenedAccepted: number[] = [];
    const narrowedAccepted: number[] = [];
    raw.forEach((witness, tag) => {
      // Accept case first, so a rejection below is caused by the arity change
      // and not by an unrelated defect in the vector.
      expect(accepts(witness), `tag ${tag.toString()} is accepted`).toBe(true);
      if (accepts(new Constr(tag, [...witness.fields, new Constr(0, [])]))) {
        widenedAccepted.push(tag);
      }
      if (
        witness.fields.length > 0 &&
        accepts(new Constr(tag, witness.fields.slice(0, -1)))
      ) {
        narrowedAccepted.push(tag);
      }
    });
    expect(widenedAccepted).toEqual([]);
    expect(narrowedAccepted).toEqual([]);
  });

  it("keeps every witness field typed rather than opaque", () => {
    // The other half of what the deleted source-text assertions protected: a
    // field widened to an untyped `Data.Any()` keeps both the arity and the
    // corpus bytes intact, so neither the round trip nor the arity property
    // above can see it. A typed field must refuse at least one of two probes
    // of obviously different shape; an opaque one refuses neither.
    const raw = canonicalRawWitnesses();
    const opaque: string[] = [];
    raw.forEach((witness, tag) => {
      witness.fields.forEach((_field, index) => {
        const probeAccepted = [new Constr(0, []), 0n].filter((probe) => {
          const perturbed = new Constr(tag, [
            ...witness.fields.slice(0, index),
            probe,
            ...witness.fields.slice(index + 1),
          ]);
          try {
            Data.from(
              Data.to(perturbed as never),
              ValidationAuxiliaryWitnessSchema,
            );
            return true;
          } catch {
            return false;
          }
        });
        if (probeAccepted.length === 2) {
          opaque.push(`tag ${tag.toString()} field ${index.toString()}`);
        }
      });
    });
    expect(opaque).toEqual([]);
  });

  it("preserves every individual canonical tag and encoding", () => {
    const raw = canonicalRawWitnesses();
    const decoded = raw.map((witness, tag) => {
      try {
        return Data.from(
          Data.to(witness as never),
          ValidationAuxiliaryWitnessSchema,
        );
      } catch (error) {
        const detail = error instanceof Error ? error.message : String(error);
        throw new Error(`canonical auxiliary tag ${tag} is invalid: ${detail}`);
      }
    });

    decoded.forEach((witness, tag) => {
      const encoded = Data.to(
        witness as never,
        ValidationAuxiliaryWitnessSchema,
      );
      expect(encoded).toBe(Data.to(raw[tag]! as never));
      const roundTrip = Data.from(encoded, ValidationAuxiliaryWitnessSchema);
      expect(Data.to(roundTrip, ValidationAuxiliaryWitnessSchema)).toBe(
        encoded,
      );
    });
  });

  it("rejects adjacent tags, wrong arities, and malformed nested shapes", () => {
    const rejects = (value: Constr<unknown>): void => {
      expect(() =>
        Data.from(Data.to(value as never), ValidationAuxiliaryWitnessSchema),
      ).toThrow();
    };

    rejects(new Constr(40, []));
    rejects(new Constr(1, ["01"]));

    const raw = canonicalRawWitnesses();
    rejects(new Constr(1, [0n, raw[1]!.fields[1]!]));
    rejects(
      new Constr(3, [
        raw[3]!.fields[0]!,
        new Constr(2, []),
        raw[3]!.fields[2]!,
      ]),
    );
    rejects(new Constr(11, raw[11]!.fields.slice(0, -1)));
    rejects(
      new Constr(11, [...raw[11]!.fields.slice(0, -1), new Constr(1, [])]),
    );
    rejects(new Constr(12, [new Constr(0, [])]));
    rejects(
      new Constr(34, [new Constr(0, [1n, 0n, 0n, 1n, new Constr(99, [])]), []]),
    );
  });
});
