// Public entrypoint; implementation is grouped by responsibility below.
export {
  admitWatcherRollbackDurableTrustedHead,
  evaluateAndPersistWatcherPostFinalityRecovery,
  evaluateAndPersistWatcherRollback,
  initializeWatcherRollbackDurableAuthority,
  loadWatcherRollbackDurableAuthority,
  persistWatcherRollbackDurableCanonicalProgress,
  persistWatcherRollbackDurableObservation,
  persistWatcherRollbackDurableObservations,
  persistWatcherRollbackDurableUserEventCheckpoint,
  prepareWatcherRollbackDurableTrustedHeadReconciliation,
  readWatcherRollbackDurableAuthority,
  readWatcherRollbackDurableFinalityState,
  readWatcherRollbackDurableUserEventCheckpoint,
  readWatcherRollbackDurableUserEventValidation,
  revalidateWatcherRollbackDurableAuthority,
  unsafeWatcherCanonicalAncestryLinksForTest,
  type WatcherRollbackCanonicalAncestryLink,
  watcherRollbackDurableAuthorityStatus,
  type WatcherRollbackDurableObservationEntry,
} from "./rollback-engine/durable-authority.js";
export {
  evaluateWatcherPostFinalityRecovery,
  parseWatcherPostFinalityRecoveryResult,
} from "./rollback-engine/recovery.js";
export {
  evaluateWatcherRollback,
  makeWatcherRollbackBootstrapState,
  parseWatcherRollbackState,
} from "./rollback-engine/state.js";
export {
  WATCHER_POST_FINALITY_RECOVERY_REASON_CODES,
  WATCHER_POST_FINALITY_RECOVERY_RESULT_SCHEMA_VERSION,
  WATCHER_POST_FINALITY_RECOVERY_STATE_SCHEMA_VERSION,
  WATCHER_ROLLBACK_ALERT_CODES,
  WATCHER_ROLLBACK_BOUNDS,
  WATCHER_ROLLBACK_DURABLE_AUTHORITY_HANDLE_SCHEMA_VERSION,
  WATCHER_ROLLBACK_DURABLE_AUTHORITY_SCHEMA_VERSION,
  WATCHER_ROLLBACK_DURABLE_TRUSTED_HEAD_SCHEMA_VERSION,
  WATCHER_ROLLBACK_EPOCH_CHECKPOINT_SCHEMA_VERSION,
  WATCHER_ROLLBACK_INCIDENT_SCHEMA_VERSION,
  WATCHER_ROLLBACK_REASON_CODES,
  WATCHER_ROLLBACK_RESULT_SCHEMA_VERSION,
  WATCHER_ROLLBACK_STATE_SCHEMA_VERSION,
  WATCHER_ROLLBACK_TRANSITION_SCHEMA_VERSION,
  type WatcherPostFinalityRecoveryIncidentLifecycle,
  type WatcherPostFinalityRecoveryInput,
  type WatcherPostFinalityRecoveryPath,
  type WatcherPostFinalityRecoveryReasonCode,
  type WatcherPostFinalityRecoveryResult,
  type WatcherPostFinalityRecoveryState,
  type WatcherRollbackAlertCode,
  type WatcherRollbackDurableAuthority,
  type WatcherRollbackDurableAuthorityOpenResult,
  type WatcherRollbackDurableAuthorityRead,
  type WatcherRollbackDurableAuthorityStatus,
  type WatcherRollbackDurableCanonicalProgressResult,
  type WatcherRollbackDurableEvaluationResult,
  type WatcherRollbackDurableObservationResult,
  type WatcherRollbackDurableRecoveryResult,
  type WatcherRollbackDurableTrustedHead,
  type WatcherRollbackDurableTrustedHeadReconciliation,
  type WatcherRollbackEpochCheckpoint,
  type WatcherRollbackIncident,
  type WatcherRollbackReasonCode,
  type WatcherRollbackRemovedRecords,
  type WatcherRollbackResult,
  type WatcherRollbackState,
  type WatcherRollbackStateVerificationContext,
  type WatcherRollbackTransition,
} from "./rollback-engine/types.js";
