name = "al-ft/midgard"
version = "0.0.0"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'al-ft/midgard'"

[repository]
user = "al-ft"
project = "midgard"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "2.1.0"
source = "github"

[[dependencies]]
name = "anastasia-labs/aiken-design-patterns"
version = "plutus-v3"
source = "github"

[config]
