{-# LANGUAGE OverloadedStrings #-}

{- |
Module      : Testing.TransactionRootV1Golden
Description : RF031 transaction and forced-transaction root golden vectors.

The fixture bytes are generated by the same canonical TypeScript fixture as
the Aiken suite. These tests consume those bytes through the Plutarch CBOR,
MPF, ledger-state, and counted-root implementations rather than recomputing the
expected values locally.
-}
module Testing.TransactionRootV1Golden (tests) where

import Data.ByteString qualified as BS
import PlutusCore.Data qualified as PD
import Plutarch.Core.Utils (pand'List)
import Plutarch.Prelude
import Plutarch.Unsafe (punsafeCoerce)
import Test.Tasty
import Test.Tasty.HUnit

import Aiken.Cbor (pdeserialise)
import Midgard.LedgerState (
  PForcedInclusionTxV1 (..),
  PL2TransactionSourceV1 (..),
  PNativeTxProofSourceV1 (..),
 )
import Midgard.MpfProof (phasV1)
import Midgard.MpfProof.Types (PProof)
import Midgard.TransitionTrace (
  PRootDomain (PForcedTransactionsV1RootDomain, PTransactionsV1RootDomain),
  pcommitCountedRoot,
 )
import Testing.Eval (passertEval)
import Testing.TransactionRootV1GoldenFixture qualified as F

tests :: TestTree
tests =
  testGroup
    "RF031 transaction-root V1 golden vectors"
    [ testCase "rf031_transaction_root_uses_exact_domain_and_ordering" $
        passertEval transactionRootIsExact
    , testCase "rf031_forced_transaction_root_uses_order_keys_and_domain" $
        passertEval forcedRootIsExact
    , transactionSourceCase "rf031_transaction_alpha_transaction_source_is_exact" transactionAlpha
    , transactionSourceCase "rf031_transaction_beta_transaction_source_is_exact" transactionBeta
    , forcedSourceCase "rf031_forced_alpha_valid_forced_source_and_verdict_are_exact" forcedAlphaValid
    , forcedSourceCase "rf031_forced_alpha_missing_input_forced_source_and_verdict_are_exact" forcedAlphaMissingInput
    , forcedSourceCase "rf031_forced_alpha_invalid_signature_forced_source_and_verdict_are_exact" forcedAlphaInvalidSignature
    , forcedSourceCase "rf031_forced_beta_failed_script_forced_source_and_verdict_are_exact" forcedBetaFailedScript
    , forcedSourceCase "rf031_forced_beta_fee_too_low_forced_source_and_verdict_are_exact" forcedBetaFeeTooLow
    , forcedSourceCase "rf031_forced_beta_unbalanced_forced_source_and_verdict_are_exact" forcedBetaUnbalanced
    ]

data TransactionFixture = TransactionFixture
  { txKey :: BS.ByteString
  , txValue :: BS.ByteString
  , txCompact :: BS.ByteString
  , txWitnessSet :: BS.ByteString
  , txLengths :: BS.ByteString
  }

data ForcedFixture = ForcedFixture
  { forcedKey :: BS.ByteString
  , forcedValue :: BS.ByteString
  , forcedOrderTransactionId :: BS.ByteString
  , forcedOrderIndex :: Integer
  , forcedTxId :: BS.ByteString
  , forcedCompact :: BS.ByteString
  , forcedWitnessSet :: BS.ByteString
  , forcedLengths :: BS.ByteString
  , forcedProof :: BS.ByteString
  , forcedVerdict :: Integer
  }

transactionSourceCase :: String -> TransactionFixture -> TestTree
transactionSourceCase name fixture = testCase name $ passertEval (transactionSourceIsExact fixture)

forcedSourceCase :: String -> ForcedFixture -> TestTree
forcedSourceCase name fixture = testCase name $ passertEval (forcedSourceIsExact fixture)

transactionRootIsExact :: forall s. Term s PBool
transactionRootIsExact =
  pand'List
    [ pconstant @PByteString F.transaction_alpha_key #< pconstant F.transaction_beta_key
    , membership
        F.transactions_phas_root
        F.transaction_alpha_key
        F.transaction_alpha_value_cbor
        F.transaction_alpha_proof_cbor
    , membership
        F.transactions_phas_root
        F.transaction_beta_key
        F.transaction_beta_value_cbor
        F.transaction_beta_proof_cbor
    , pcommitCountedRoot
        (pdata (pcon PTransactionsV1RootDomain))
        (pconstant F.transactions_phas_root)
        2
        #== pconstant F.transactions_root
    ]

forcedRootIsExact :: forall s. Term s PBool
forcedRootIsExact =
  pand'List
    [ pconstant @PByteString F.forced_alpha_valid_key #< pconstant F.forced_alpha_missing_input_key
    , pconstant @PByteString F.forced_alpha_missing_input_key #< pconstant F.forced_alpha_invalid_signature_key
    , pconstant @PByteString F.forced_alpha_invalid_signature_key #< pconstant F.forced_beta_failed_script_key
    , pconstant @PByteString F.forced_beta_failed_script_key #< pconstant F.forced_beta_fee_too_low_key
    , pconstant @PByteString F.forced_beta_fee_too_low_key #< pconstant F.forced_beta_unbalanced_key
    , forcedMembership forcedAlphaValid
    , forcedMembership forcedAlphaMissingInput
    , forcedMembership forcedAlphaInvalidSignature
    , forcedMembership forcedBetaFailedScript
    , forcedMembership forcedBetaFeeTooLow
    , forcedMembership forcedBetaUnbalanced
    , pcommitCountedRoot
        (pdata (pcon PForcedTransactionsV1RootDomain))
        (pconstant F.forced_transactions_phas_root)
        6
        #== pconstant F.forced_transactions_root
    , pnot
        # ( pcommitCountedRoot
              (pdata (pcon PTransactionsV1RootDomain))
              (pconstant F.forced_transactions_phas_root)
              6
              #== pconstant F.forced_transactions_root
          )
    ]

forcedMembership :: forall s. ForcedFixture -> Term s PBool
forcedMembership fixture =
  membership
    F.forced_transactions_phas_root
    (forcedKey fixture)
    (forcedValue fixture)
    (forcedProof fixture)

membership :: forall s. BS.ByteString -> BS.ByteString -> BS.ByteString -> BS.ByteString -> Term s PBool
membership root key value proofCbor =
  withDecoded proofCbor $ \proofData ->
    phasV1
      # pconstant root
      # pconstant key
      # pconstant value
      # (pfromData (punsafeCoerce @(PAsData PProof) proofData))

transactionSourceIsExact :: forall s. TransactionFixture -> Term s PBool
transactionSourceIsExact fixture =
  withDecoded (txValue fixture) $ \valueData ->
    pmatch
      (pfromData (punsafeCoerce @(PAsData PL2TransactionSourceV1) valueData))
      $ \PL2TransactionSourceV1 {pl2Source'txId, pl2Source'source} ->
        pmatch (pfromData pl2Source'source) $
          \PNativeTxProofSourceV1
            { pnativeSource'compactCbor
            , pnativeSource'witnessSetCompactCbor
            , pnativeSource'fieldPreimageLengthsCbor
            } ->
              pand'List
                [ pserialiseData # valueData #== pconstant (txValue fixture)
                , pfromData pl2Source'txId #== pconstant (txKey fixture)
                , pfromData pnativeSource'compactCbor #== pconstant (txCompact fixture)
                , pfromData pnativeSource'witnessSetCompactCbor #== pconstant (txWitnessSet fixture)
                , pfromData pnativeSource'fieldPreimageLengthsCbor #== pconstant (txLengths fixture)
                ]

forcedSourceIsExact :: forall s. ForcedFixture -> Term s PBool
forcedSourceIsExact fixture =
  withDecoded (forcedValue fixture) $ \valueData ->
    withDecoded (forcedKey fixture) $ \orderData ->
      pmatch
        (pfromData (punsafeCoerce @(PAsData PForcedInclusionTxV1) valueData))
        $ \PForcedInclusionTxV1 {pforcedTx'txId, pforcedTx'source, pforcedTx'operatorValidity} ->
          pmatch (pfromData pforcedTx'source) $
            \PNativeTxProofSourceV1
              { pnativeSource'compactCbor
              , pnativeSource'witnessSetCompactCbor
              , pnativeSource'fieldPreimageLengthsCbor
              } ->
                pand'List
                  [ pserialiseData # valueData #== pconstant (forcedValue fixture)
                  , pserialiseData # orderData #== pconstant (forcedKey fixture)
                  , outputReferenceIsExact
                      orderData
                      (forcedOrderTransactionId fixture)
                      (forcedOrderIndex fixture)
                  , pfromData pforcedTx'txId #== pconstant (forcedTxId fixture)
                  , pfromData pnativeSource'compactCbor #== pconstant (forcedCompact fixture)
                  , pfromData pnativeSource'witnessSetCompactCbor #== pconstant (forcedWitnessSet fixture)
                  , pfromData pnativeSource'fieldPreimageLengthsCbor #== pconstant (forcedLengths fixture)
                  , pforgetData pforcedTx'operatorValidity
                      #== pconstant (PD.Constr (forcedVerdict fixture) [])
                  ]

outputReferenceIsExact :: forall s. Term s PData -> BS.ByteString -> Integer -> Term s PBool
outputReferenceIsExact value transactionId outputIndex =
  pmatch (pasConstr # value) $ \(PBuiltinPair tag referenceFields) ->
    tag #== 0
      #&& plength # referenceFields #== 2
      #&& pasByteStr # (phead # referenceFields) #== pconstant transactionId
      #&& pasInt # (phead #$ ptail # referenceFields) #== pconstant outputIndex

withDecoded :: forall s. BS.ByteString -> (Term s PData -> Term s PBool) -> Term s PBool
withDecoded source continuation =
  pmatch (pdeserialise # pconstant source) $ \case
    PNothing -> pconstant False
    PJust value -> continuation value

transactionAlpha, transactionBeta :: TransactionFixture
transactionAlpha = TransactionFixture F.transaction_alpha_key F.transaction_alpha_value_cbor
  F.transaction_alpha_compact_cbor F.transaction_alpha_witness_set_compact_cbor
  F.transaction_alpha_field_preimage_lengths_cbor
transactionBeta = TransactionFixture F.transaction_beta_key F.transaction_beta_value_cbor
  F.transaction_beta_compact_cbor F.transaction_beta_witness_set_compact_cbor
  F.transaction_beta_field_preimage_lengths_cbor

forcedAlphaValid, forcedAlphaMissingInput, forcedAlphaInvalidSignature :: ForcedFixture
forcedBetaFailedScript, forcedBetaFeeTooLow, forcedBetaUnbalanced :: ForcedFixture
forcedAlphaValid = forcedFixture F.forced_alpha_valid_key F.forced_alpha_valid_value_cbor
  F.forced_alpha_valid_order_transaction_id 0 F.transaction_alpha_key F.forced_alpha_valid_compact_cbor
  F.forced_alpha_valid_witness_set_compact_cbor F.forced_alpha_valid_field_preimage_lengths_cbor
  F.forced_alpha_valid_proof_cbor 0
forcedAlphaMissingInput = forcedFixture F.forced_alpha_missing_input_key F.forced_alpha_missing_input_value_cbor
  F.forced_alpha_missing_input_order_transaction_id 1 F.transaction_alpha_key F.forced_alpha_missing_input_compact_cbor
  F.forced_alpha_missing_input_witness_set_compact_cbor F.forced_alpha_missing_input_field_preimage_lengths_cbor
  F.forced_alpha_missing_input_proof_cbor 1
forcedAlphaInvalidSignature = forcedFixture F.forced_alpha_invalid_signature_key F.forced_alpha_invalid_signature_value_cbor
  F.forced_alpha_invalid_signature_order_transaction_id 2 F.transaction_alpha_key F.forced_alpha_invalid_signature_compact_cbor
  F.forced_alpha_invalid_signature_witness_set_compact_cbor F.forced_alpha_invalid_signature_field_preimage_lengths_cbor
  F.forced_alpha_invalid_signature_proof_cbor 2
forcedBetaFailedScript = forcedFixture F.forced_beta_failed_script_key F.forced_beta_failed_script_value_cbor
  F.forced_beta_failed_script_order_transaction_id 0 F.transaction_beta_key F.forced_beta_failed_script_compact_cbor
  F.forced_beta_failed_script_witness_set_compact_cbor F.forced_beta_failed_script_field_preimage_lengths_cbor
  F.forced_beta_failed_script_proof_cbor 3
forcedBetaFeeTooLow = forcedFixture F.forced_beta_fee_too_low_key F.forced_beta_fee_too_low_value_cbor
  F.forced_beta_fee_too_low_order_transaction_id 1 F.transaction_beta_key F.forced_beta_fee_too_low_compact_cbor
  F.forced_beta_fee_too_low_witness_set_compact_cbor F.forced_beta_fee_too_low_field_preimage_lengths_cbor
  F.forced_beta_fee_too_low_proof_cbor 4
forcedBetaUnbalanced = forcedFixture F.forced_beta_unbalanced_key F.forced_beta_unbalanced_value_cbor
  F.forced_beta_unbalanced_order_transaction_id 2 F.transaction_beta_key F.forced_beta_unbalanced_compact_cbor
  F.forced_beta_unbalanced_witness_set_compact_cbor F.forced_beta_unbalanced_field_preimage_lengths_cbor
  F.forced_beta_unbalanced_proof_cbor 5

forcedFixture ::
  BS.ByteString -> BS.ByteString -> BS.ByteString -> Integer -> BS.ByteString ->
  BS.ByteString -> BS.ByteString -> BS.ByteString -> BS.ByteString -> Integer -> ForcedFixture
forcedFixture = ForcedFixture
