import {
  MIDGARD_CONSENSUS_LIMITS_V1,
  MIDGARD_V1_ENVELOPE_MEASUREMENTS,
} from "@al-ft/midgard-core";
import {
  healMidgardFieldCarriageV1,
  layOutMidgardFieldCarriageV1,
  MIDGARD_CARRIAGE_RELIABILITY_RESERVE_BYTES_V1,
  MIDGARD_EXACT_PUBLISHABLE_CARRIAGE_BYTES_V1,
  MIDGARD_MAX_PUBLISHABLE_CARRIAGE_BYTES_V1,
  midgardCarriageDataByteStringBytesV1,
  midgardCarriagePublicationBytesV1,
  midgardCarriagePublicationFramingBytesV1,
  midgardFieldCarriagePlansAreInterchangeableV1,
  type MidgardFieldCarriagePlanV1,
  midgardFieldCarriagePublishabilityV1,
  planMidgardFieldCarriageV1,
} from "@al-ft/midgard-core/codec/native-tx-carriage-v1";
import {
  authenticatedMidgardFieldViewV1,
  MIDGARD_CHUNK_BYTES_K_V1,
  MIDGARD_MAX_TIER1_REDEEMER_PREIMAGE_BYTES_V1,
  MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1,
  midgardFieldCommitmentV1,
  midgardFieldItemAtV1,
  midgardFieldItemCountV1,
  type MidgardFieldViewV1,
  type ResolvedCarriageReferenceInputV1,
} from "@al-ft/midgard-core/codec/native-tx-field-access-v1";
import {
  buildUnsignedFieldPreimageCertificationV1Program,
  buildUnsignedFieldPreimagePublicationV1Program,
  certifyFieldPreimageRedeemerV1,
  deriveFieldPreimageCertificationV1,
  FieldPreimageCertificateV1,
  fieldPreimagePublicationBytesV1,
  fieldPreimagePublicationDatumCborV1,
  fieldPreimagePublicationOutputsV1,
  type FieldPreimagePublicationOutputV1,
  minimumLovelaceForFieldPreimageCertificateV1,
  minimumLovelaceForFieldPreimagePublicationV1,
  resolveChunkReferenceIndicesV1,
  retireFieldPreimageCertificateRedeemerV1,
} from "@al-ft/midgard-sdk";
import {
  CML,
  Data,
  Emulator,
  Lucid,
  type LucidEvolution,
  type MintingPolicy,
  PROTOCOL_PARAMETERS_DEFAULT,
  type UTxO,
} from "@lucid-evolution/lucid";
import { Effect } from "effect";
import { beforeAll, beforeEach, describe, expect, it } from "vitest";

/**
 * Phase-4 carriage exit measurements and the §8.7 healing path, against a real
 * emulator ledger — `docs/spec/midgard-tx.md` §8.
 *
 * Three things happen here, and only the first is a test in the ordinary sense.
 *
 *   1. **The ladder is exercised end to end.** A preimage of each tier is
 *      planned, published where publication is required, resolved back out of
 *      the ledger, and read through the single field-access door by *one*
 *      consumer function that never mentions a tier.
 *   2. **The §8.7 healing path is driven.** A published chunk is clobbered — its
 *      UTxO spent out from under the dispute — and re-published by a second
 *      identity with no relationship to the first. The original certificate
 *      still describes the healed bytes, and the read that broke succeeds again.
 *   3. **The tier-2 byte frontier is measured**, because §8.3's `K` was
 *      *provisional pending Phase-4 measurement* and this is that measurement —
 *      the one that falsified 15,900 and re-pinned `K` to what it now is:
 *      the largest preimage whose real signed key-address publication clears
 *      `maxTxSize`, and the largest that clears it with the 512-byte
 *      reliability reserve the counted era used.
 *
 * **One emulator now, at the real limit — and that is E1's repair, visible.**
 * `setupEmulator` runs at the **real** `maxTxSize` (16,384) by default, so
 * anything that submits a publication is judged by the ledger itself and not by
 * an assertion written to pass. **Exactly one block still raises it**: the
 * frontier sweep, which has to build transactions *past* the limit in order to
 * find where the limit is. Every other block — the tier ladder, the tier-3
 * corner healing, the min-Ada measurements, the certification round trip — used
 * to raise it too, because at the superseded `K` = 15,900 a tier-3 chunk could
 * not be submitted at any size (§8.3 erratum E1). E1's repair re-pinned `K` to
 * the reliable frontier, so those blocks now publish full-`K` chunks through the
 * real ledger and the raise is gone with the defect. The mechanism that made
 * that happen is worth keeping in view: the inflated blocks asserted their
 * over-limit-ness explicitly, so the re-pin turned them red and had to come back
 * here and say so, rather than leaving them quietly vacuous. Every verdict is
 * still taken against `MIDGARD_CONSENSUS_LIMITS_V1.minSupportedL1MaxTxBytes`,
 * never against whatever the emulator was willing to accept.
 *
 * **The certificate is minted, under a stand-in policy.** The compiled
 * certificate validator landed in #573 but the blueprint carrying its code is
 * regenerated by #579, so its *content rules* are proved on the Aiken side
 * (`validators/field-preimage-certificate-handlers.test.ak`) and cannot be
 * proved here. What can be proved here — and now is — is everything the script
 * is not: the certification transaction really mints a `(tx_id, field_index)`
 * token, really lands the manifest as an inline datum at a script address, and
 * a consuming step really resolves that certificate **out of the ledger** by
 * decoding the datum and matching the token, rather than reading the plan it
 * was built from. The stand-in is an always-satisfiable native script, and the
 * one thing it does not check is the one thing the Aiken suite does. Where a
 * claim depends on the compiled script, it is stated as depending on it.
 */

// The 512-byte transaction-side allowance the counted era used to separate an
// "exact" frontier (lands on maxTxSize) from a "reliable" one (lands on
// maxTxSize with room for the variability a real submission path introduces).
// Named by the codec rather than restated here, so the frontier this file
// measures and the frontier the SDK guard enforces are the same reserve.
const RELIABILITY_RESERVE_BYTES = MIDGARD_CARRIAGE_RELIABILITY_RESERVE_BYTES_V1;
const MAX_L1_TX_BYTES = MIDGARD_CONSENSUS_LIMITS_V1.minSupportedL1MaxTxBytes;

/** Field 1 (reference inputs): §5.3 stride 40, 38-byte items. */
const FIELD_INDEX = 1;
const STRIDE = 40;
const ITEM_BYTES = 38;

const PUBLISHER_KEY = CML.PrivateKey.from_normal_bytes(Buffer.alloc(32, 11));
const HEALER_KEY = CML.PrivateKey.from_normal_bytes(Buffer.alloc(32, 22));

const keyHash = (key: CML.PrivateKey): Buffer =>
  Buffer.from(key.to_public().hash().to_raw_bytes());

const enterpriseAddress = (key: CML.PrivateKey): string =>
  CML.EnterpriseAddress.new(
    0,
    CML.Credential.new_pub_key(key.to_public().hash()),
  )
    .to_address()
    .to_bech32();

const PUBLISHER_ADDRESS = enterpriseAddress(PUBLISHER_KEY);
const HEALER_ADDRESS = enterpriseAddress(HEALER_KEY);

const TX_ID = Buffer.alloc(32, 0x5a);

/**
 * A §5.1 preimage of `itemCount` well-formed field-1 items. Item payloads are an
 * affine byte pattern keyed by index, so two items are never equal and a read
 * that lands one item off returns bytes that do not match anything.
 */
const fieldPreimage = (itemCount: number): Buffer => {
  const header =
    itemCount <= 23
      ? Buffer.from([0x80 + itemCount])
      : itemCount <= 255
        ? Buffer.from([0x98, itemCount])
        : Buffer.from([0x99, itemCount >> 8, itemCount & 0xff]);
  const items = Array.from({ length: itemCount }, (_unused, index) => {
    const payload = Buffer.concat([
      Buffer.from([0x82, 0x58, 0x20]),
      Buffer.from(
        Array.from(
          { length: 32 },
          (_byte, offset) => (index * 7 + offset) & 0xff,
        ),
      ),
      Buffer.from([0x19, (index >> 8) & 0xff, index & 0xff]),
    ]);
    if (payload.length !== ITEM_BYTES) {
      throw new Error("field-1 item must be 38 bytes");
    }
    return Buffer.concat([Buffer.from([0x58, ITEM_BYTES]), payload]);
  });
  return Buffer.concat([header, ...items]);
};

/** The item count whose §5.1 preimage is the largest at or under `bytes`. */
const itemCountForPreimageBytes = (bytes: number): number => {
  for (let count = Math.floor(bytes / STRIDE) + 1; count >= 0; count -= 1) {
    if (fieldPreimage(count).length <= bytes) {
      return count;
    }
  }
  throw new Error("no item count fits");
};

const itemPayloadAt = (preimage: Buffer, index: number): Buffer => {
  const headerLength = preimage[0] === 0x99 ? 3 : preimage[0] === 0x98 ? 2 : 1;
  const offset = headerLength + STRIDE * index + 2;
  return preimage.subarray(offset, offset + ITEM_BYTES);
};

type Harness = {
  readonly lucid: LucidEvolution;
  readonly emulator: Emulator;
};

/**
 * The `maxTxSize` a block asks for when it needs to build a transaction the
 * real ledger would refuse — the frontier sweep, and (until §8.3 erratum E1's
 * re-pin lands) anything that publishes a full-`K` tier-3 chunk.
 */
const MEASUREMENT_MAX_TX_BYTES = 65_536;

/**
 * The publication-size budget the frontier sweep hands the SDK builder. The
 * builder refuses anything over the E1 frontier by default, which is the whole
 * point of the guard; a measurement is the one caller entitled to raise it, and
 * it does so explicitly rather than by calling something else.
 */
const MEASUREMENT_PUBLICATION_BUDGET_BYTES =
  MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1;

/**
 * `maxTxSize` defaults to the **real** deployment floor. A block that wants
 * more has to say so and say why; that is what stops a gate that cannot fail
 * from being written by accident.
 */
const setupEmulator = async ({
  maxTxSize = MAX_L1_TX_BYTES,
}: { readonly maxTxSize?: number } = {}): Promise<Harness> => {
  const emulator = new Emulator(
    [
      {
        seedPhrase: "",
        privateKey: PUBLISHER_KEY.to_bech32(),
        address: PUBLISHER_ADDRESS,
        assets: { lovelace: 500_000_000_000n },
      },
      {
        seedPhrase: "",
        privateKey: HEALER_KEY.to_bech32(),
        address: HEALER_ADDRESS,
        assets: { lovelace: 500_000_000_000n },
      },
    ],
    { ...PROTOCOL_PARAMETERS_DEFAULT, maxTxSize },
  );
  const lucid = await Lucid(emulator, "Custom");
  lucid.selectWallet.fromPrivateKey(PUBLISHER_KEY.to_bech32());
  return { lucid, emulator };
};

/**
 * The publication output a plan requires for one chunk — the whole output, not
 * just its datum, which is why it is not called `publicationDatum`.
 */
const publicationOutputFor = (
  plan: MidgardFieldCarriagePlanV1,
  chunkIndex: number,
): FieldPreimagePublicationOutputV1 => {
  const output = fieldPreimagePublicationOutputsV1(plan).find(
    (candidate) => candidate.chunkIndex === chunkIndex,
  );
  if (output === undefined) {
    throw new Error(`plan has no chunk ${chunkIndex.toString()}`);
  }
  return output;
};

/**
 * A raw §8.5 publication output for arbitrary payload bytes, used only by the
 * byte-frontier sweep. It bypasses the plan on purpose: the frontier question
 * is what a nothing-but-bytes publication transaction costs at a given payload
 * size, and a plan below the tier-1 bound would answer "nothing to publish"
 * rather than answering the question.
 */
const rawPublicationOutput = (
  bytes: Buffer,
): FieldPreimagePublicationOutputV1 => ({
  chunkIndex: 0,
  datumCbor: fieldPreimagePublicationDatumCborV1(bytes),
  byteLength: bytes.length,
  digestHex: midgardFieldCommitmentV1(bytes).toString("hex"),
});

type PublicationResult = {
  readonly utxo: UTxO;
  readonly signedBytes: number;
  readonly minAdaLovelace: bigint;
  readonly feeLovelace: bigint;
};

/**
 * Builds, signs and submits one raw carriage publication, and reports what it
 * cost.
 *
 * The builder under test really is the SDK's —
 * {@link buildUnsignedFieldPreimagePublicationV1Program} — and nothing here
 * reimplements it. That matters more than it looks: an earlier revision of this
 * file said exactly this sentence while assembling the transaction inline, so
 * the shipped builder had no caller anywhere in the repository and its §8.3 E1
 * size guard could not have been exercised by anything.
 *
 * `maxPublicationBytes` is threaded through rather than defaulted away, so a
 * block that intends to build past the frontier says so.
 */
const publish = async ({
  harness,
  publication,
  signerKey,
  address,
  submit = true,
  maxPublicationBytes,
}: {
  readonly harness: Harness;
  readonly publication: FieldPreimagePublicationOutputV1;
  readonly signerKey: CML.PrivateKey;
  readonly address: string;
  readonly submit?: boolean;
  readonly maxPublicationBytes?: number;
}): Promise<PublicationResult> => {
  harness.lucid.selectWallet.fromPrivateKey(signerKey.to_bech32());
  const protocolParameters = harness.lucid.config().protocolParameters;
  if (protocolParameters === undefined) {
    throw new Error("emulator protocol parameters are unavailable");
  }
  const minAdaLovelace = minimumLovelaceForFieldPreimagePublicationV1({
    publisherAddress: address,
    output: publication,
    coinsPerUtxoByte: protocolParameters.coinsPerUtxoByte,
  });
  const unsigned = await Effect.runPromise(
    buildUnsignedFieldPreimagePublicationV1Program(harness.lucid, {
      publication,
      publisherAddress: address,
      ...(maxPublicationBytes === undefined ? {} : { maxPublicationBytes }),
    }),
  );
  const signed = await unsigned.sign.withWallet().complete();
  const signedCbor = signed.toCBOR();
  const signedBytes = signedCbor.length / 2;
  const feeLovelace = CML.Transaction.from_cbor_hex(signedCbor).body().fee();
  if (!submit) {
    return {
      utxo: {
        txHash: "",
        outputIndex: 0,
        address,
        assets: { lovelace: minAdaLovelace },
        datum: publication.datumCbor,
      },
      signedBytes,
      minAdaLovelace,
      feeLovelace,
    };
  }
  const txHash = await signed.submit();
  await harness.lucid.awaitTx(txHash);
  const published = (await harness.lucid.utxosAt(address)).find(
    (utxo) => utxo.txHash === txHash && utxo.datum === publication.datumCbor,
  );
  if (published === undefined) {
    throw new Error("published carriage UTxO was not found");
  }
  return { utxo: published, signedBytes, minAdaLovelace, feeLovelace };
};

/**
 * The consuming step, and the whole of the "tier is invisible" claim.
 *
 * It takes a carriage layout and the reference inputs that layout indexes, and
 * reads an item. There is no tier parameter, no branch on one, and no way to
 * tell from this function which rung of the ladder it is standing on — which is
 * §8's simplest-fitting-first mandate as a property of the code rather than a
 * convention.
 */
const readItemThroughTheDoor = ({
  plan,
  referenceInputs,
  index,
}: {
  readonly plan: MidgardFieldCarriagePlanV1;
  readonly referenceInputs: readonly ResolvedCarriageReferenceInputV1[];
  readonly index: number;
}): { readonly view: MidgardFieldViewV1; readonly item: Buffer } => {
  const layout = layOutMidgardFieldCarriageV1({ plan });
  const view = authenticatedMidgardFieldViewV1({
    fieldIndex: plan.fieldIndex,
    txId: plan.txId,
    expectedCommitment: plan.commitment,
    carriage: layout.carriage,
    referenceInputs,
  });
  return { view, item: midgardFieldItemAtV1(view, index) };
};

/**
 * Resolves a plan's carriage out of the ledger the way a step builder does:
 * the manifest first, then the chunks in §8.4 order, each located by the
 * content of its datum rather than by UTxO identity (§8.7).
 */
const resolveReferenceInputs = ({
  plan,
  utxos,
}: {
  readonly plan: MidgardFieldCarriagePlanV1;
  readonly utxos: readonly UTxO[];
}): readonly ResolvedCarriageReferenceInputV1[] => {
  const layout = layOutMidgardFieldCarriageV1({ plan });
  if (layout.carriage.carriage === "Inline") {
    return [];
  }
  const chunkInputs = plan.publications.map((publication) => {
    const expected = publicationOutputFor(
      plan,
      publication.chunkIndex,
    ).datumCbor;
    const utxo = utxos.find((candidate) => candidate.datum === expected);
    if (utxo === undefined) {
      throw new Error(
        `carriage for chunk ${publication.chunkIndex.toString()} is not on the ledger`,
      );
    }
    const datum = utxo.datum;
    if (datum === undefined || datum === null) {
      throw new Error("resolved carriage UTxO carries no inline datum");
    }
    return { inlineDatumBytes: fieldPreimagePublicationBytesV1(datum) };
  });
  if (layout.carriage.carriage === "RawUtxo") {
    return chunkInputs;
  }
  const certificate = plan.certificate;
  const certificateAssetName = plan.certificateAssetName;
  if (certificate === null || certificateAssetName === null) {
    throw new Error("tier-3 plan carries no certificate");
  }
  return [{ certificate, certificateAssetName }, ...chunkInputs];
};

/**
 * A tier-3 plan's reference inputs with one chunk's bytes replaced — what a
 * builder that resolved carriage by *anything other than content* would hand
 * the door.
 *
 * It bypasses {@link resolveReferenceInputs} deliberately. That helper refuses
 * first, by content, which is correct and is asserted on its own; but a
 * refusal that never reaches the door is not evidence about the door, and the
 * door is what §8.6's digest vector is for.
 */
const referenceInputsWithSubstitutedChunk = ({
  plan,
  chunkIndex,
  bytes,
}: {
  readonly plan: MidgardFieldCarriagePlanV1;
  readonly chunkIndex: number;
  readonly bytes: Buffer;
}): readonly ResolvedCarriageReferenceInputV1[] => {
  const certificate = plan.certificate;
  const certificateAssetName = plan.certificateAssetName;
  if (certificate === null || certificateAssetName === null) {
    throw new Error("tier-3 plan carries no certificate");
  }
  return [
    { certificate, certificateAssetName },
    ...plan.publications.map((publication) => ({
      inlineDatumBytes:
        publication.chunkIndex === chunkIndex ? bytes : publication.bytes,
    })),
  ];
};

describe("§8 carriage ladder — tier selection is a partition", () => {
  it("assigns exactly one tier to every length up to the §5.4 cap", () => {
    const planFor = (bytes: number): MidgardFieldCarriagePlanV1 =>
      planMidgardFieldCarriageV1({
        owner: keyHash(PUBLISHER_KEY),
        txId: TX_ID,
        fieldIndex: FIELD_INDEX,
        preimage: fieldPreimage(itemCountForPreimageBytes(bytes)),
      });

    // The boundaries are the interesting inputs: one byte either side of each
    // rung, so a tier chosen with the wrong comparison operator is visible.
    expect(planFor(1).tier).toBe("Inline");
    expect(planFor(MIDGARD_MAX_TIER1_REDEEMER_PREIMAGE_BYTES_V1).tier).toBe(
      "Inline",
    );
    expect(
      planFor(MIDGARD_MAX_TIER1_REDEEMER_PREIMAGE_BYTES_V1 + 40).tier,
    ).toBe("RawUtxo");
    expect(planFor(MIDGARD_CHUNK_BYTES_K_V1).tier).toBe("RawUtxo");
    expect(planFor(MIDGARD_CHUNK_BYTES_K_V1 + 40).tier).toBe("Certified");
    const corner = planFor(MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1);
    expect(corner.tier).toBe("Certified");
    expect(corner.publications.length).toBe(3);
    expect(corner.publications.map((entry) => entry.bytes.length)).toEqual([
      MIDGARD_CHUNK_BYTES_K_V1,
      MIDGARD_CHUNK_BYTES_K_V1,
      corner.totalLength - 2 * MIDGARD_CHUNK_BYTES_K_V1,
    ]);
  });

  it("refuses a preimage above the §5.4 aggregate cap", () => {
    expect(() =>
      planMidgardFieldCarriageV1({
        owner: keyHash(PUBLISHER_KEY),
        txId: TX_ID,
        fieldIndex: FIELD_INDEX,
        preimage: Buffer.alloc(
          MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1 + 1,
        ),
      }),
    ).toThrow();
  });
});

describe("§8 carriage ladder — one consumer path, three tiers", () => {
  let harness: Harness;

  beforeAll(async () => {
    // Inflated, and only because of §8.3 erratum E1: the tier-3 case publishes
    // full-`K` chunks, and at the currently-pinned `K` those measure 16,648
    // bytes and the real ledger refuses them. The block asserts that overrun
    // explicitly below rather than letting the inflated limit hide it.
    harness = await setupEmulator();
  });

  it("carries a preimage of every tier to a dispute read with no tier branch", async () => {
    const cases = [
      { label: "tier 1 — redeemer", bytes: 4_000, tier: "Inline" as const },
      { label: "tier 2 — raw UTxO", bytes: 15_000, tier: "RawUtxo" as const },
      {
        label: "tier 3 — certified chunks",
        bytes: MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1,
        tier: "Certified" as const,
      },
    ];

    for (const testCase of cases) {
      const itemCount = itemCountForPreimageBytes(testCase.bytes);
      const preimage = fieldPreimage(itemCount);
      const plan = planMidgardFieldCarriageV1({
        owner: keyHash(PUBLISHER_KEY),
        txId: TX_ID,
        fieldIndex: FIELD_INDEX,
        preimage,
      });
      expect(plan.tier).toBe(testCase.tier);
      expect(plan.commitment).toEqual(midgardFieldCommitmentV1(preimage));

      for (const publication of fieldPreimagePublicationOutputsV1(plan)) {
        const result = await publish({
          harness,
          publication,
          signerKey: PUBLISHER_KEY,
          address: PUBLISHER_ADDRESS,
        });
        // The E1 gate, stated per publication rather than assumed for the
        // block: a chunk at or under the frontier really does fit the real
        // limit, and a full-`K` chunk really does not. The second half is the
        // live defect, and it is asserted as an exact overrun so that the day
        // `K` is re-pinned this line turns red and has to be revisited rather
        // than silently continuing to pass.
        if (
          publication.byteLength <= MIDGARD_MAX_PUBLISHABLE_CARRIAGE_BYTES_V1
        ) {
          expect(result.signedBytes).toBeLessThanOrEqual(
            MAX_L1_TX_BYTES - RELIABILITY_RESERVE_BYTES,
          );
        } else {
          expect(publication.byteLength).toBe(MIDGARD_CHUNK_BYTES_K_V1);
          expect(result.signedBytes).toBe(16_648);
          expect(result.signedBytes - MAX_L1_TX_BYTES).toBe(264);
        }
        // Whatever the size, the cost model the guard is built on reproduces
        // the real signed transaction to the byte.
        expect(midgardCarriagePublicationBytesV1(publication.byteLength)).toBe(
          result.signedBytes,
        );
      }
      const utxos = await harness.lucid.utxosAt(PUBLISHER_ADDRESS);
      const referenceInputs = resolveReferenceInputs({ plan, utxos });

      // The same three lines for every tier, and the last item of each — the
      // read most likely to be off by one, and under tier 3 the one that lands
      // in the ragged tail.
      const lastIndex = itemCount - 1;
      const { view, item } = readItemThroughTheDoor({
        plan,
        referenceInputs,
        index: lastIndex,
      });
      expect(midgardFieldItemCountV1(view)).toBe(itemCount);
      expect(item).toEqual(itemPayloadAt(preimage, lastIndex));

      // And an item that straddles a chunk boundary wherever there is one.
      if (plan.publications.length > 1) {
        const straddling = Math.floor((MIDGARD_CHUNK_BYTES_K_V1 - 3) / STRIDE);
        const straddled = readItemThroughTheDoor({
          plan,
          referenceInputs,
          index: straddling,
        });
        expect(straddled.item).toEqual(itemPayloadAt(preimage, straddling));
      }
    }
  });
});

describe("§8.7 healing — carriage lost or corrupted is re-published by a second identity", () => {
  let harness: Harness;

  // A **fresh ledger per test**, not per block. Carriage is addressed by
  // content, so two tests that publish the same corner leave two UTxOs carrying
  // byte-identical datums — and a yank in the second test would then be healed,
  // silently and wrongly, by the first test's leftover. That is exactly the
  // class of false green a content-addressed resolver invites, and a shared
  // `beforeAll` walks into it.
  beforeEach(async () => {
    // Inflated for the same reason as the ladder block, and for no other: a
    // tier-3 corner cannot be published at the currently-pinned `K` (§8.3 E1).
    // The tier-2 heal at the end of this file runs at the real limit.
    harness = await setupEmulator();
  });

  const publishCorner = async (): Promise<{
    readonly preimage: Buffer;
    readonly itemCount: number;
    readonly plan: MidgardFieldCarriagePlanV1;
    readonly published: readonly UTxO[];
  }> => {
    const itemCount = itemCountForPreimageBytes(
      MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1,
    );
    const preimage = fieldPreimage(itemCount);
    const plan = planMidgardFieldCarriageV1({
      owner: keyHash(PUBLISHER_KEY),
      txId: TX_ID,
      fieldIndex: FIELD_INDEX,
      preimage,
    });
    expect(plan.tier).toBe("Certified");
    expect(plan.publications.length).toBe(3);
    const published: UTxO[] = [];
    for (const publication of fieldPreimagePublicationOutputsV1(plan)) {
      const result = await publish({
        harness,
        publication,
        signerKey: PUBLISHER_KEY,
        address: PUBLISHER_ADDRESS,
      });
      published.push(result.utxo);
    }
    return { preimage, itemCount, plan, published };
  };

  /**
   * The item index that lands inside chunk `chunkIndex`, so a yank of that
   * chunk is a yank of the bytes the read actually needs. Derived rather than
   * hard-coded: an off-by-one here would make a refusal attributable to the
   * wrong chunk.
   */
  const itemIndexInsideChunk = (chunkIndex: number): number =>
    Math.floor((MIDGARD_CHUNK_BYTES_K_V1 * chunkIndex + 200) / STRIDE);

  // §8.7 names two ways carriage stops being usable, and #565 claims healing
  // for both. They are different failures — one removes the UTxO, the other
  // leaves a UTxO carrying the wrong bytes — so they are exercised separately.
  //
  // The full-`K` chunk 0 is deliberately first. It is the largest publication
  // the ladder produces and the one that sits exactly on erratum E1's reliable
  // frontier; healing only the 2,467-byte ragged tail, as an earlier revision of
  // this file did, exercised the one chunk whose publication was never in
  // question.
  for (const chunkIndex of [0, 2]) {
    it(`survives a yank of chunk ${chunkIndex.toString()}: the original certificate still describes healed bytes`, async () => {
      const { preimage, plan, published } = await publishCorner();
      const readIndex = itemIndexInsideChunk(chunkIndex);
      const chunkBytes = plan.publications[chunkIndex]?.bytes.length;
      // The corner's ragged tail: 32,763 − 2·15,148 = 2,467 bytes at E1's
      // repaired `K`. It was 963 at the superseded 15,900.
      expect(chunkBytes).toBe(
        chunkIndex === 2 ? 2_467 : MIDGARD_CHUNK_BYTES_K_V1,
      );

      const beforeYank = readItemThroughTheDoor({
        plan,
        referenceInputs: resolveReferenceInputs({
          plan,
          utxos: await harness.lucid.utxosAt(PUBLISHER_ADDRESS),
        }),
        index: readIndex,
      });
      expect(beforeYank.item).toEqual(itemPayloadAt(preimage, readIndex));

      // The yank. §8.7's "mid-game yank" is the publisher spending their own
      // carriage out from under a dispute — an ordinary key spend, because raw
      // carriage is unauthenticated data at the publisher's own address and
      // nothing stops them.
      const yanked = published[chunkIndex];
      if (yanked === undefined) {
        throw new Error("expected three published chunks");
      }
      harness.lucid.selectWallet.fromPrivateKey(PUBLISHER_KEY.to_bech32());
      const yankTx = await harness.lucid
        .newTx()
        .collectFrom([yanked])
        .complete({ localUPLCEval: true });
      const yankHash = await (
        await yankTx.sign.withWallet().complete()
      ).submit();
      await harness.lucid.awaitTx(yankHash);

      // The dispute is now stuck, and stuck is what it must be: fail-closed,
      // never a wrong answer. Two refusals are asserted, and they are asserted
      // *separately* because they belong to different components — an earlier
      // revision asserted one `toThrow()` that the resolver's own error
      // satisfied, so the door was never reached and never tested.
      //
      // One: the step builder cannot assemble the reference inputs, because the
      // chunk is not on the ledger. That is this file's helper refusing, and it
      // is checked by message so it cannot be confused with the next one.
      const survivors = await harness.lucid.utxosAt(PUBLISHER_ADDRESS);
      expect(() => resolveReferenceInputs({ plan, utxos: survivors })).toThrow(
        `carriage for chunk ${chunkIndex.toString()} is not on the ledger`,
      );

      // Two, and this is the one that matters: suppose a builder *does* hand
      // the door something in that slot — the obvious mistake, some other
      // chunk's bytes. The door itself refuses, on the certificate's digest
      // vector, and the refusal comes from the SDK/codec rather than from this
      // file. Substituting the *neighbouring* chunk's real bytes makes it a
      // genuine wrong-chunk substitution and not merely malformed input.
      const substitute = plan.publications[1];
      if (substitute === undefined) {
        throw new Error("expected a neighbouring chunk to substitute");
      }
      expect(() =>
        readItemThroughTheDoor({
          plan,
          referenceInputs: referenceInputsWithSubstitutedChunk({
            plan,
            chunkIndex,
            bytes: substitute.bytes,
          }),
          index: readIndex,
        }),
      ).toThrow();

      // The heal. A second identity — different key, different UTxOs, different
      // min-Ada reclaim authority, no relationship to the original publisher —
      // re-derives the carriage from the preimage bytes alone.
      const healedPlan = healMidgardFieldCarriageV1({
        healer: keyHash(HEALER_KEY),
        txId: TX_ID,
        fieldIndex: FIELD_INDEX,
        preimage,
      });
      expect(
        midgardFieldCarriagePlansAreInterchangeableV1(plan, healedPlan),
      ).toBe(true);
      expect(healedPlan.certificate?.owner).not.toEqual(
        plan.certificate?.owner,
      );

      const healedPublication = publicationOutputFor(healedPlan, chunkIndex);
      // Byte-identical to what was yanked, which is the whole mechanism: the
      // certificate that already exists describes these bytes without being
      // re-minted.
      expect(healedPublication.datumCbor).toBe(
        publicationOutputFor(plan, chunkIndex).datumCbor,
      );
      expect(healedPublication.digestHex).toBe(
        publicationOutputFor(plan, chunkIndex).digestHex,
      );

      await publish({
        harness,
        publication: healedPublication,
        signerKey: HEALER_KEY,
        address: HEALER_ADDRESS,
      });

      // The dispute proceeds. Note the carriage now spans two addresses under
      // two owners, and the read neither knows nor cares — it resolves by
      // content.
      const healedUtxos = [
        ...(await harness.lucid.utxosAt(PUBLISHER_ADDRESS)),
        ...(await harness.lucid.utxosAt(HEALER_ADDRESS)),
      ];
      const afterHeal = readItemThroughTheDoor({
        plan,
        referenceInputs: resolveReferenceInputs({ plan, utxos: healedUtxos }),
        index: readIndex,
      });
      expect(afterHeal.item).toEqual(itemPayloadAt(preimage, readIndex));
      expect(afterHeal.item).toEqual(beforeYank.item);

      // And the *healer's* certificate is equally good over the *publisher's*
      // surviving chunks — interchangeable in both directions, which is what
      // "anyone's republication heals anyone's certificate" means.
      const healedCertificateRead = readItemThroughTheDoor({
        plan: healedPlan,
        referenceInputs: resolveReferenceInputs({
          plan: healedPlan,
          utxos: healedUtxos,
        }),
        index: readIndex,
      });
      expect(healedCertificateRead.item).toEqual(
        itemPayloadAt(preimage, readIndex),
      );
    }, 120_000);
  }

  it("survives a malicious publication: wrong bytes on the ledger are ignored, not consumed", async () => {
    // #565's other healing claim, and the one no test reached: the attack is
    // not always removal. A hostile party can publish *wrong* bytes for a chunk
    // and leave them sitting on the ledger next to the right ones. §8.7 says
    // content addressing makes that a non-event; this is that claim, exercised.
    const { preimage, plan, published } = await publishCorner();
    const readIndex = itemIndexInsideChunk(0);
    const victim = published[0];
    const genuine = plan.publications[0];
    if (victim === undefined || genuine === undefined) {
      throw new Error("expected a published chunk 0");
    }

    // The impostor: chunk 0's length, one byte different, published by the
    // *other* identity at their own address. Nothing forbids this; carriage is
    // unauthenticated data (§8.5).
    const corrupted = Buffer.from(genuine.bytes);
    corrupted[7] = (corrupted[7] ?? 0) ^ 0xff;
    await publish({
      harness,
      publication: {
        chunkIndex: 0,
        datumCbor: fieldPreimagePublicationDatumCborV1(corrupted),
        byteLength: corrupted.length,
        digestHex: midgardFieldCommitmentV1(corrupted).toString("hex"),
      },
      signerKey: HEALER_KEY,
      address: HEALER_ADDRESS,
    });

    // With both on the ledger, resolution by content picks the genuine one and
    // the read is unaffected. The impostor is not rejected — it is not seen.
    const both = [
      ...(await harness.lucid.utxosAt(PUBLISHER_ADDRESS)),
      ...(await harness.lucid.utxosAt(HEALER_ADDRESS)),
    ];
    const withImpostor = readItemThroughTheDoor({
      plan,
      referenceInputs: resolveReferenceInputs({ plan, utxos: both }),
      index: readIndex,
    });
    expect(withImpostor.item).toEqual(itemPayloadAt(preimage, readIndex));

    // And now yank the genuine one, leaving *only* the corrupted bytes. This is
    // the composite attack — remove the truth, leave a plausible lie — and the
    // door must still refuse rather than serve the lie.
    harness.lucid.selectWallet.fromPrivateKey(PUBLISHER_KEY.to_bech32());
    const yankTx = await harness.lucid
      .newTx()
      .collectFrom([victim])
      .complete({ localUPLCEval: true });
    await harness.lucid.awaitTx(
      await (await yankTx.sign.withWallet().complete()).submit(),
    );
    const survivors = [
      ...(await harness.lucid.utxosAt(PUBLISHER_ADDRESS)),
      ...(await harness.lucid.utxosAt(HEALER_ADDRESS)),
    ];
    expect(() => resolveReferenceInputs({ plan, utxos: survivors })).toThrow(
      "carriage for chunk 0 is not on the ledger",
    );
    // Forced past the resolver — a builder that matched on length instead of
    // content would produce exactly this — the door refuses on the digest.
    expect(() =>
      readItemThroughTheDoor({
        plan,
        referenceInputs: referenceInputsWithSubstitutedChunk({
          plan,
          chunkIndex: 0,
          bytes: corrupted,
        }),
        index: readIndex,
      }),
    ).toThrow();
  }, 120_000);
});

describe("§8.3 Phase-4 exit measurement — the tier-2 raw-UTxO bound", () => {
  let harness: Harness;

  beforeAll(async () => {
    // The only block that legitimately builds past the limit, because that is
    // what finding a frontier means.
    harness = await setupEmulator({ maxTxSize: MEASUREMENT_MAX_TX_BYTES });
  });

  /**
   * The signed size of a real §8.5 publication of `bytes` payload bytes.
   *
   * Measured over raw payload bytes rather than over a plan, because a plan
   * below the tier-1 bound publishes nothing at all: the question is what a
   * nothing-but-bytes publication transaction costs at a given payload size,
   * and that is the same transaction whether the payload is a whole tier-2
   * preimage or a tier-3 chunk.
   *
   * **At one-byte resolution.** An earlier revision measured at the field-1
   * stride of 40 bytes and published the largest stride-quantised preimage
   * under each frontier as the frontier — 15,643 and 15,123, which are one and
   * twenty-five bytes short. A frontier measured on a lattice is not a
   * frontier, and the exact row's own stated property ("lands on `maxTxSize`")
   * was false of the transaction it reported.
   */
  const measure = async (bytes: number): Promise<number> => {
    const payload = Buffer.from(
      Array.from({ length: bytes }, (_unused, index) => (index * 7 + 3) & 0xff),
    );
    const result = await publish({
      harness,
      publication: rawPublicationOutput(payload),
      signerKey: PUBLISHER_KEY,
      address: PUBLISHER_ADDRESS,
      submit: false,
      maxPublicationBytes: MEASUREMENT_PUBLICATION_BUDGET_BYTES,
    });
    return result.signedBytes;
  };

  it("reproduces the real signed transaction size from the three-term cost model", async () => {
    // The frontiers below are *derived* from `midgardCarriagePublicationBytesV1`
    // rather than searched for, which is only sound if that function is the
    // truth. This is where that is established: across four orders of magnitude
    // of payload, the model and the real signed emulator transaction agree to
    // the byte.
    //
    // **The samples straddle the boundaries the claim needs, not just the sizes
    // the ladder uses.** An earlier revision sampled only inside the band where
    // the non-payload framing happens to be a flat 248 bytes, and then published
    // "two terms and no third" — a claim its own sample set was structurally
    // incapable of falsifying. The third term is the CBOR head of the inline
    // datum's byte-string wrapper, which steps at datum lengths 24, 256 and
    // 65,536; the payloads below sit on both sides of the first two. The third
    // step is at a 63,548-byte payload, which is above the §5.4 aggregate cap
    // and so cannot be a real publication at any `maxTxSize` — it is pinned
    // analytically in midgard-core's unit suite instead, and it is pinned
    // precisely because it is the step the collapsed model got *optimistically*
    // wrong.
    for (const payloadBytes of [
      22, 23, 63, 64, 65, 245, 246, 548, 1_000, 8_000, 14_336, 15_148, 15_644,
      15_900,
    ]) {
      const signedBytes = await measure(payloadBytes);
      expect({ payloadBytes, signedBytes }).toEqual({
        payloadBytes,
        signedBytes: midgardCarriagePublicationBytesV1(payloadBytes),
      });
      // And the decomposition §8.3 E1 publishes: whatever is left after the
      // payload's own Plutus Data encoding is the fixed 245 bytes plus that
      // datum's own head. This is the assertion that would catch the claim E1
      // corrected — that the 740 bytes measured at the frontier were a floor
      // for the family rather than a figure that moves with the payload.
      const datumBytes = midgardCarriageDataByteStringBytesV1(payloadBytes);
      expect(signedBytes - datumBytes).toBe(
        midgardCarriagePublicationFramingBytesV1(datumBytes),
      );
    }

    // The step is real and measured, not merely modelled: the same family of
    // transaction costs 246, 247 and 248 bytes of non-payload framing at these
    // three payloads. A model that collapsed them to a constant would have to
    // be wrong at two of the three.
    expect(await measure(22)).toBe(269);
    expect(await measure(23)).toBe(271);
    expect(await measure(246)).toBe(504);
  }, 180_000);

  it("measures the largest publishable preimage and re-pins K against it", async () => {
    // A frontier is a pair of adjacent measurements, not a single one: the
    // largest payload that fits, and the smallest that does not. Both are real
    // signed transactions.
    const exactSigned = await measure(
      MIDGARD_EXACT_PUBLISHABLE_CARRIAGE_BYTES_V1,
    );
    const exactOverSigned = await measure(
      MIDGARD_EXACT_PUBLISHABLE_CARRIAGE_BYTES_V1 + 1,
    );
    const reliableSigned = await measure(
      MIDGARD_MAX_PUBLISHABLE_CARRIAGE_BYTES_V1,
    );
    const reliableOverSigned = await measure(
      MIDGARD_MAX_PUBLISHABLE_CARRIAGE_BYTES_V1 + 1,
    );
    const atKSigned = await measure(MIDGARD_CHUNK_BYTES_K_V1);

    // Reported so a re-take reads the numbers off the report rather than
    // reconstructing them. This is the Phase-4 measurement §8.3 declared
    // itself provisional pending.
    console.log(
      JSON.stringify({
        measurement: "tier2-raw-utxo-bound-v1",
        maxL1TxBytes: MAX_L1_TX_BYTES,
        reliabilityReserveBytes: RELIABILITY_RESERVE_BYTES,
        supersededChunkBytesK: MIDGARD_CHUNK_BYTES_K_V1,
        exactFrontierPreimageBytes: MIDGARD_EXACT_PUBLISHABLE_CARRIAGE_BYTES_V1,
        exactFrontierTransactionBytes: exactSigned,
        firstUnpublishablePreimageBytes:
          MIDGARD_EXACT_PUBLISHABLE_CARRIAGE_BYTES_V1 + 1,
        firstUnpublishableTransactionBytes: exactOverSigned,
        reliableFrontierPreimageBytes:
          MIDGARD_MAX_PUBLISHABLE_CARRIAGE_BYTES_V1,
        reliableFrontierTransactionBytes: reliableSigned,
        transactionBytesAtSupersededK: atKSigned,
        supersededKOverrunBytes: atKSigned - MAX_L1_TX_BYTES,
        framingBytesAtExactFrontier:
          exactSigned - MIDGARD_EXACT_PUBLISHABLE_CARRIAGE_BYTES_V1,
        // Non-datum framing *at this datum size* — 245 fixed plus a 3-byte
        // head. Reported under a name that says so, because an earlier
        // revision called the same subtraction "fixed" and that is what let
        // the head hide inside it.
        nonDatumFramingBytesAtExactFrontier:
          exactSigned -
          midgardCarriageDataByteStringBytesV1(
            MIDGARD_EXACT_PUBLISHABLE_CARRIAGE_BYTES_V1,
          ),
        countedEraExactFrontier:
          MIDGARD_V1_ENVELOPE_MEASUREMENTS.maxExactCompleteItemPublicationBytes,
        countedEraReliableFrontier:
          MIDGARD_V1_ENVELOPE_MEASUREMENTS.maxReliableCompleteItemPublicationBytes,
        countedEraAppliedCap:
          MIDGARD_CONSENSUS_LIMITS_V1.maxSinglePublicationCompleteItemBytes,
      }),
    );

    // The frontiers are pinned to the byte, the way the counted era pinned
    // `maxExactCompleteItemPublicationBytes` and
    // `maxReliableCompleteItemPublicationBytes`: spec §8.10 and §8.3's erratum
    // quote these numbers, so an environment or builder change that moves them
    // has to move the document too rather than drifting away from it.
    expect(MIDGARD_EXACT_PUBLISHABLE_CARRIAGE_BYTES_V1).toBe(15_644);
    expect(MIDGARD_MAX_PUBLISHABLE_CARRIAGE_BYTES_V1).toBe(15_148);
    // "Lands on `maxTxSize`" is asserted as an equality, because that is the
    // claim §8.10's row makes and the previous revision's 16,383 did not meet.
    expect(exactSigned).toBe(MAX_L1_TX_BYTES);
    expect(exactOverSigned).toBe(MAX_L1_TX_BYTES + 1);
    expect(reliableSigned).toBe(MAX_L1_TX_BYTES - RELIABILITY_RESERVE_BYTES);
    expect(reliableOverSigned).toBe(
      MAX_L1_TX_BYTES - RELIABILITY_RESERVE_BYTES + 1,
    );

    // The claim #574 owes as the flat successor to the counted-era bound —
    // stated against the counted **frontiers**, which are the like-for-like
    // quantities. `maxSinglePublicationCompleteItemBytes` = 14,396 is an
    // applied policy cap with 1,128 bytes of unused headroom, and comparing a
    // frontier to a cap measures the cap's safety margin rather than the
    // format's gain; the previous revision did that and reported +1,247 B,
    // about 17× the real figure.
    //
    // **CORRECTED 2026-08-14 (owner ruling): the gain was +74 / +75 B, not
    // +155 / +155.** The two counted-era frontiers this subtracts from were
    // themselves ~80 bytes low — 14,993/15,489 where the counted publisher
    // actually reaches 15,073/15,570, as the three sibling measurements in the
    // same `MIDGARD_V1_ENVELOPE_MEASUREMENTS` block (datum bytes, min-Ada, fee)
    // had said all along. The flat format's real gain over the counted era is
    // therefore about half what was claimed. The overstated figure is not
    // preserved anywhere as if it still held; the measured one replaces it here
    // and in §8.10 of `docs/spec/midgard-tx.md`.
    expect(
      MIDGARD_EXACT_PUBLISHABLE_CARRIAGE_BYTES_V1 -
        MIDGARD_V1_ENVELOPE_MEASUREMENTS.maxExactCompleteItemPublicationBytes,
    ).toBe(74);
    expect(
      MIDGARD_MAX_PUBLISHABLE_CARRIAGE_BYTES_V1 -
        MIDGARD_V1_ENVELOPE_MEASUREMENTS.maxReliableCompleteItemPublicationBytes,
    ).toBe(75);
    // The counted reliable publication and the flat reliable frontier land in
    // the same size of transaction. That is what makes the two gains comparable
    // at all. They differ by one byte rather than being equal, and that byte is
    // accounted for: across the 512-byte reserve the counted shape's non-payload
    // framing steps by 15 (814 B at 15,570 -> 799 B at 15,073) while the flat
    // shape's steps by 16 (740 B at 15,644 -> 724 B at 15,148), so 16 - 15 = 1.
    // Two ends of one gain, not two different gains.
    expect(reliableSigned).toBe(
      MIDGARD_V1_ENVELOPE_MEASUREMENTS.maxReliableCompleteItemPublicationTransactionBytes,
    );

    // §8.3's provisional `K = 15,900` was **falsified** by this measurement: a
    // 15,900-byte publication measured 16,648 signed bytes, 264 over
    // `maxTxSize`, reserve or no reserve. Erratum E1 recorded that and re-pinned
    // `K` to the reliable frontier, and the re-pin has now landed — so what this
    // block measures today is the repaired ladder rather than the outage.
    //
    // A full-`K` publication is exactly the reliable frontier's transaction: it
    // clears `maxTxSize` with the 512-byte reserve intact, which is the property
    // that makes every chunk of every tier-3 plan publishable.
    expect(atKSigned).toBe(MAX_L1_TX_BYTES - RELIABILITY_RESERVE_BYTES);
    expect(atKSigned).toBe(15_872);
    expect(MAX_L1_TX_BYTES - atKSigned).toBe(RELIABILITY_RESERVE_BYTES);

    // E1's repair, as an exact equality rather than an inequality: `K` **is**
    // the reliable frontier. This is the one line that says the erratum is
    // closed, and it is written as `=== 0` on purpose — any future re-pin of
    // either half that does not move the other turns it red instead of leaving a
    // silent gap, which is what the superseded 752-byte gap was.
    expect(
      MIDGARD_CHUNK_BYTES_K_V1 - MIDGARD_MAX_PUBLISHABLE_CARRIAGE_BYTES_V1,
    ).toBe(0);
    // And the superseded value, kept as a measurement rather than as prose: it
    // is still over the limit, which is why it is no longer `K`.
    expect(midgardCarriagePublicationBytesV1(15_900)).toBe(16_648);
    expect(midgardCarriagePublicationBytesV1(15_900) - MAX_L1_TX_BYTES).toBe(
      264,
    );

    // §8.3 E1's tier-1 note: the same Plutus Data chunking cost applies to
    // redeemer carriage, and it is 450 bytes of the 2,048-byte allowance before
    // any step machinery exists.
    expect(
      midgardCarriageDataByteStringBytesV1(
        MIDGARD_MAX_TIER1_REDEEMER_PREIMAGE_BYTES_V1,
      ),
    ).toBe(14_786);
  }, 300_000);
});

describe("§8.3 erratum E1 — the publishable frontier is enforced, at the real maxTxSize", () => {
  let harness: Harness;

  beforeAll(async () => {
    // No inflation. Every publication in this block is judged by the ledger.
    harness = await setupEmulator();
  });

  it("submits a frontier-sized publication and refuses the byte past it", async () => {
    const atFrontier = await publish({
      harness,
      publication: rawPublicationOutput(
        Buffer.alloc(MIDGARD_MAX_PUBLISHABLE_CARRIAGE_BYTES_V1, 0x5c),
      ),
      signerKey: PUBLISHER_KEY,
      address: PUBLISHER_ADDRESS,
    });
    // Submitted, on a ledger with maxTxSize = 16,384. This is the assertion
    // that could not have been written before: the previous revision ran every
    // block at 65,536 and nothing anywhere checked a publication against the
    // real limit.
    expect(atFrontier.utxo.txHash).not.toBe("");
    expect(atFrontier.signedBytes).toBe(
      MAX_L1_TX_BYTES - RELIABILITY_RESERVE_BYTES,
    );

    // One byte more and the guard refuses — before the ledger is asked, and
    // naming the erratum rather than surfacing a submission error.
    await expect(
      publish({
        harness,
        publication: rawPublicationOutput(
          Buffer.alloc(MIDGARD_MAX_PUBLISHABLE_CARRIAGE_BYTES_V1 + 1, 0x5c),
        ),
        signerKey: PUBLISHER_KEY,
        address: PUBLISHER_ADDRESS,
      }),
    ).rejects.toThrow("§8.3 erratum E1");
  }, 120_000);

  it("passes every chunk of the largest tier-3 plan, and still names one over a lowered budget", () => {
    const plan = planMidgardFieldCarriageV1({
      owner: keyHash(PUBLISHER_KEY),
      txId: TX_ID,
      fieldIndex: FIELD_INDEX,
      preimage: fieldPreimage(
        itemCountForPreimageBytes(
          MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1,
        ),
      ),
    });
    // This is E1's repair as an end-to-end property, at the largest plan the
    // format admits: three chunks, two of them full-`K`, and *every* one of them
    // publishable inside the reserve. Before the repair this row asserted the
    // opposite — chunks 0 and 1 unpublishable at 16,648 signed bytes apiece —
    // and that was the whole shape of the outage: every tier-3 plan there was
    // had a chunk the ledger would refuse.
    expect(plan.tier).toBe("Certified");
    expect(
      plan.publications.map((publication) => publication.bytes.length),
    ).toEqual([MIDGARD_CHUNK_BYTES_K_V1, MIDGARD_CHUNK_BYTES_K_V1, 2_467]);
    const report = midgardFieldCarriagePublishabilityV1({ plan });
    expect(report.publishable).toBe(true);
    expect(report.unpublishableChunks).toEqual([]);
    // The guard is not vacuous now that honest plans pass it: judged against a
    // budget one byte under the full-`K` publication it names exactly the two
    // full chunks and the overrun to the byte. Without this half the row would
    // be a gate that cannot fail.
    const tightened = midgardFieldCarriagePublishabilityV1({
      plan,
      budgetBytes: MAX_L1_TX_BYTES - RELIABILITY_RESERVE_BYTES - 1,
    });
    expect(tightened.publishable).toBe(false);
    expect(
      tightened.unpublishableChunks.map((chunk) => chunk.chunkIndex),
    ).toEqual([0, 1]);
    for (const chunk of tightened.unpublishableChunks) {
      expect(chunk.byteLength).toBe(MIDGARD_CHUNK_BYTES_K_V1);
      expect(chunk.publicationBytes).toBe(
        MAX_L1_TX_BYTES - RELIABILITY_RESERVE_BYTES,
      );
      expect(chunk.overrunBytes).toBe(1);
    }
  });

  it("heals a frontier-sized tier-2 publication under real protocol parameters", async () => {
    // §8.7 healing at the size that matters. The tier-3 healing block above
    // runs inflated because tier 3 cannot be published at all right now; this
    // one runs at the real limit over the largest publication the ladder can
    // actually make, so "a yanked publication is healed" is demonstrated as a
    // property of the deployed parameters rather than of an emulator setting.
    const itemCount = itemCountForPreimageBytes(
      MIDGARD_MAX_PUBLISHABLE_CARRIAGE_BYTES_V1,
    );
    const preimage = fieldPreimage(itemCount);
    const plan = planMidgardFieldCarriageV1({
      owner: keyHash(PUBLISHER_KEY),
      txId: TX_ID,
      fieldIndex: FIELD_INDEX,
      preimage,
    });
    expect(plan.tier).toBe("RawUtxo");
    expect(midgardFieldCarriagePublishabilityV1({ plan }).publishable).toBe(
      true,
    );

    const original = await publish({
      harness,
      publication: publicationOutputFor(plan, 0),
      signerKey: PUBLISHER_KEY,
      address: PUBLISHER_ADDRESS,
    });
    expect(original.signedBytes).toBeLessThanOrEqual(
      MAX_L1_TX_BYTES - RELIABILITY_RESERVE_BYTES,
    );

    const lastIndex = itemCount - 1;
    const before = readItemThroughTheDoor({
      plan,
      referenceInputs: resolveReferenceInputs({
        plan,
        utxos: await harness.lucid.utxosAt(PUBLISHER_ADDRESS),
      }),
      index: lastIndex,
    });
    expect(before.item).toEqual(itemPayloadAt(preimage, lastIndex));

    harness.lucid.selectWallet.fromPrivateKey(PUBLISHER_KEY.to_bech32());
    const yankTx = await harness.lucid
      .newTx()
      .collectFrom([original.utxo])
      .complete({ localUPLCEval: true });
    await harness.lucid.awaitTx(
      await (await yankTx.sign.withWallet().complete()).submit(),
    );
    expect(() =>
      resolveReferenceInputs({
        plan,
        utxos: [],
      }),
    ).toThrow("carriage for chunk 0 is not on the ledger");

    const healedPlan = healMidgardFieldCarriageV1({
      healer: keyHash(HEALER_KEY),
      txId: TX_ID,
      fieldIndex: FIELD_INDEX,
      preimage,
    });
    expect(
      midgardFieldCarriagePlansAreInterchangeableV1(plan, healedPlan),
    ).toBe(true);
    const healed = await publish({
      harness,
      publication: publicationOutputFor(healedPlan, 0),
      signerKey: HEALER_KEY,
      address: HEALER_ADDRESS,
    });
    expect(healed.utxo.txHash).not.toBe("");
    expect(healed.signedBytes).toBe(original.signedBytes);

    const after = readItemThroughTheDoor({
      plan,
      referenceInputs: resolveReferenceInputs({
        plan,
        utxos: await harness.lucid.utxosAt(HEALER_ADDRESS),
      }),
      index: lastIndex,
    });
    expect(after.item).toEqual(before.item);
  }, 120_000);
});

/**
 * The §8.6 redeemer a certification carries, sized once.
 *
 * It re-carries no chunk bytes — only the committed structures and the
 * positional indices — which is why §8.3 says certification never constrains
 * `K`. The 400-byte compact structure and 100-byte witness set are the
 * stand-in shapes both cost claims below are quoted against, and they are
 * written once so the two cannot drift apart.
 */
const CERTIFY_REDEEMER_BYTES =
  certifyFieldPreimageRedeemerV1({
    compactCbor: "ab".repeat(400),
    witnessSetCompactCbor: "cd".repeat(100),
    chunkRefInputIndices: [0, 1, 2],
    outputIndex: 0,
  }).length / 2;

describe("§8.6 Phase-4 exit measurement — certificate min-Ada and the one-transaction question", () => {
  it("reports min-Ada at the sizes the ladder really uses", async () => {
    const harness = await setupEmulator();
    const protocolParameters = harness.lucid.config().protocolParameters;
    if (protocolParameters === undefined) {
      throw new Error("emulator protocol parameters are unavailable");
    }
    const { coinsPerUtxoByte } = protocolParameters;

    const cornerPlan = planMidgardFieldCarriageV1({
      owner: keyHash(PUBLISHER_KEY),
      txId: TX_ID,
      fieldIndex: FIELD_INDEX,
      preimage: fieldPreimage(
        itemCountForPreimageBytes(
          MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1,
        ),
      ),
    });
    const certification = deriveFieldPreimageCertificationV1(cornerPlan);
    // The certificate lives at the validator's own address. Its *code* comes
    // from the blueprint #579 regenerates, but min-Ada depends only on the
    // output's serialised size — address, value, inline datum — so a stand-in
    // script address of the right shape measures the same number the real one
    // will. Stated rather than hidden: this is the one figure here that does
    // not come from the deployed script, and it does not need to.
    const certificatePolicyId = "22".repeat(28);
    const certificateAddress = CML.EnterpriseAddress.new(
      0,
      CML.Credential.new_script(CML.ScriptHash.from_hex(certificatePolicyId)),
    )
      .to_address()
      .to_bech32();

    const certificateMinAda = minimumLovelaceForFieldPreimageCertificateV1({
      certificateAddress,
      certification,
      certificatePolicyId,
      coinsPerUtxoByte,
    });

    const chunkMinAda = minimumLovelaceForFieldPreimagePublicationV1({
      publisherAddress: PUBLISHER_ADDRESS,
      output: publicationOutputFor(cornerPlan, 0),
      coinsPerUtxoByte,
    });
    const raggedMinAda = minimumLovelaceForFieldPreimagePublicationV1({
      publisherAddress: PUBLISHER_ADDRESS,
      output: publicationOutputFor(cornerPlan, 2),
      coinsPerUtxoByte,
    });

    console.log(
      JSON.stringify({
        measurement: "certificate-min-ada-v1",
        coinsPerUtxoByte: coinsPerUtxoByte.toString(),
        certificateChunkDigests: certification.chunkCount,
        certificateDatumBytes: certification.datumCbor.length / 2,
        certificateMinAdaLovelace: certificateMinAda.toString(),
        fullChunkMinAdaLovelace: chunkMinAda.toString(),
        raggedChunkMinAdaLovelace: raggedMinAda.toString(),
        certifyRedeemerBytes: CERTIFY_REDEEMER_BYTES,
      }),
    );

    // §8.10 quotes these three numbers as a table, so they are asserted rather
    // than only printed — a console.log is a report, not a gate, and the table
    // it feeds is the deliverable.
    expect(coinsPerUtxoByte).toBe(4_310n);
    expect(certification.chunkCount).toBe(3);
    // 210 bytes since #606: the datum gained the 32-byte mint-welded
    // `field_hash` (plus its 2-byte CBOR head), 176 → 210, and the manifest's
    // min-Ada moved with it (1.9395 → 2.0645 ADA).
    expect(certification.datumCbor.length / 2).toBe(210);
    expect(certificateMinAda).toBe(2_064_490n);
    expect(chunkMinAda).toBe(68_231_610n);
    expect(raggedMinAda).toBe(11_869_740n);

    // The datum a full chunk carries is 15,624 bytes, not the 15,148 of
    // payload: min-Ada is charged on the serialised output, so the ≈3.125 %
    // Plutus Data chunking cost is deposit as well as transaction size. §8.10's
    // table labelled the datum column with the payload figure until this line
    // existed to contradict it. (The three deposit figures moved with §8.3
    // erratum E1's repair of `K`: the full chunk was 15,900 B of payload in a
    // 16,400-byte datum at 71.5762 ADA, and the ragged tail 963 B in 996 at
    // 5.1849 ADA. The manifest is unmoved — three digests either way.)
    expect(midgardCarriageDataByteStringBytesV1(MIDGARD_CHUNK_BYTES_K_V1)).toBe(
      15_624,
    );
    expect(publicationOutputFor(cornerPlan, 0).datumCbor.length / 2).toBe(
      15_624,
    );
    expect(publicationOutputFor(cornerPlan, 2).datumCbor.length / 2).toBe(
      2_547,
    );

    // A manifest is small: three digests, a length and an owner. The whole
    // point of tier 3 is that the *certified* object is tiny even though the
    // preimage is not.
    expect(certificateMinAda).toBeLessThan(chunkMinAda);
    expect(raggedMinAda).toBeLessThan(chunkMinAda);
  });

  it("shows last-chunk publication and certification cannot share a transaction", async () => {
    const harness = await setupEmulator();
    const cornerPlan = planMidgardFieldCarriageV1({
      owner: keyHash(PUBLISHER_KEY),
      txId: TX_ID,
      fieldIndex: FIELD_INDEX,
      preimage: fieldPreimage(
        itemCountForPreimageBytes(
          MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1,
        ),
      ),
    });

    // Reason one, and it is structural rather than a matter of size. §8.6
    // resolves chunks from *reference inputs*, and the Cardano ledger resolves
    // reference inputs against the UTxO set as it stands before the
    // transaction. An output the same transaction creates is therefore not
    // available to it, at any size, under any protocol parameters. The builder
    // makes that concrete by requiring resolved chunk UTxOs rather than
    // datums: there is no way to hand it a chunk that does not yet exist.
    const lastChunk = publicationOutputFor(cornerPlan, 2);
    const published = await publish({
      harness,
      publication: lastChunk,
      signerKey: PUBLISHER_KEY,
      address: PUBLISHER_ADDRESS,
    });
    expect(published.utxo.txHash).not.toBe("");

    // Reason two, independent of the first and measured: even if a chunk could
    // be self-referenced, the bytes do not fit. A full-K publication alone is
    // already most of maxTxSize, and a certification adds the manifest output,
    // the §8.6 redeemer and the minting-policy witness on top.
    const fullChunkPublication = await publish({
      harness,
      publication: publicationOutputFor(cornerPlan, 0),
      signerKey: PUBLISHER_KEY,
      address: PUBLISHER_ADDRESS,
      submit: false,
    });
    const redeemerBytes = CERTIFY_REDEEMER_BYTES;
    const certification = deriveFieldPreimageCertificationV1(cornerPlan);
    const certificateOutputBytes = certification.datumCbor.length / 2;

    console.log(
      JSON.stringify({
        measurement: "publication-plus-certification-fit-v1",
        maxL1TxBytes: MAX_L1_TX_BYTES,
        fullChunkPublicationBytes: fullChunkPublication.signedBytes,
        certifyRedeemerBytes: redeemerBytes,
        certificateDatumBytes: certificateOutputBytes,
        combinedLowerBound:
          fullChunkPublication.signedBytes +
          redeemerBytes +
          certificateOutputBytes,
        fitsOneTransaction: false,
        structuralReason:
          "reference inputs resolve against the pre-transaction UTxO set",
      }),
    );

    expect(
      fullChunkPublication.signedBytes + redeemerBytes + certificateOutputBytes,
    ).toBeGreaterThan(MAX_L1_TX_BYTES);
  }, 120_000);
});

/**
 * A stand-in certificate minting policy: an always-satisfiable native script.
 *
 * **What this is and is not.** The compiled `field_preimage_certificate`
 * validator landed in #573, but the blueprint that would carry its code is
 * regenerated by #579, so nothing in this repository can put *that* script on
 * an emulator ledger yet. Its content rules — the §3 tx-id re-derivation, the
 * positional field-hash extraction, `total_length`, the per-chunk digests, the
 * output shape — are proved by `validators/field-preimage-certificate-handlers.test.ak`
 * and are proved nowhere here.
 *
 * What the stand-in buys is everything that is not the script's arithmetic: a
 * certificate token that really exists under a `(tx_id, field_index)` asset
 * name, a manifest that really sits as an inline datum at a script address, and
 * a consuming step that really recovers it from the ledger. Before this, the
 * certificate half of every tier-3 read in this file came out of the in-memory
 * plan, so the reference input a step resolves had never been round-tripped
 * through a UTxO at all.
 */
const standInCertificatePolicy = (): {
  readonly policy: MintingPolicy;
  readonly policyId: string;
  readonly address: string;
} => {
  const script = CML.NativeScript.new_script_all(CML.NativeScriptList.new());
  const policyId = script.hash().to_hex();
  return {
    policy: {
      type: "Native",
      script: Buffer.from(script.to_cbor_bytes()).toString("hex"),
    },
    policyId,
    address: CML.EnterpriseAddress.new(
      0,
      CML.Credential.new_script(CML.ScriptHash.from_hex(policyId)),
    )
      .to_address()
      .to_bech32(),
  };
};

/**
 * Recovers a tier-3 certificate reference input the way a step builder must:
 * from the **ledger**, by decoding the manifest out of the UTxO's inline datum
 * and taking the asset name off the token the UTxO actually carries.
 *
 * Nothing here consults the plan. That is the point — a resolver that read the
 * certificate out of the plan it was built from would agree with itself no
 * matter what the mint had done.
 */
const resolveCertificateFromLedger = (
  utxo: UTxO,
  policyId: string,
): ResolvedCarriageReferenceInputV1 => {
  const datum = utxo.datum;
  if (datum === undefined || datum === null) {
    throw new Error("certificate UTxO carries no inline datum");
  }
  const decoded = Data.from(datum, FieldPreimageCertificateV1);
  const units = Object.keys(utxo.assets).filter(
    (unit) => unit !== "lovelace" && unit.startsWith(policyId),
  );
  const unit = units[0];
  if (units.length !== 1 || unit === undefined) {
    throw new Error("certificate output must carry exactly one policy asset");
  }
  return {
    certificate: {
      owner: Buffer.from(decoded.owner, "hex"),
      txId: Buffer.from(decoded.tx_id, "hex"),
      fieldIndex: Number(decoded.field_index),
      fieldHash: Buffer.from(decoded.field_hash, "hex"),
      totalLength: Number(decoded.total_length),
      chunkDigests: decoded.chunk_digests.map((digest) =>
        Buffer.from(digest, "hex"),
      ),
    },
    certificateAssetName: Buffer.from(unit.slice(policyId.length), "hex"),
  };
};

describe("§8.6 certification — the certificate is minted, and a step reads it off the ledger", () => {
  let harness: Harness;

  beforeAll(async () => {
    // Inflated for the chunk publications only (§8.3 E1); the certification
    // transaction itself is small and its size is asserted against the real
    // limit below.
    harness = await setupEmulator();
  });

  it("publishes, certifies, and resolves the manifest back out of the UTxO set", async () => {
    const itemCount = itemCountForPreimageBytes(
      MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1,
    );
    const preimage = fieldPreimage(itemCount);
    const plan = planMidgardFieldCarriageV1({
      owner: keyHash(PUBLISHER_KEY),
      txId: TX_ID,
      fieldIndex: FIELD_INDEX,
      preimage,
    });
    const chunkUtxos: UTxO[] = [];
    for (const publication of fieldPreimagePublicationOutputsV1(plan)) {
      const result = await publish({
        harness,
        publication,
        signerKey: PUBLISHER_KEY,
        address: PUBLISHER_ADDRESS,
      });
      chunkUtxos.push(result.utxo);
    }

    const { policy, policyId, address } = standInCertificatePolicy();
    harness.lucid.selectWallet.fromPrivateKey(PUBLISHER_KEY.to_bech32());

    // The SDK's certification builder, driven end to end. It derives the
    // manifest, the asset name, the min-Ada, the redeemer and — through
    // `resolveChunkReferenceIndicesV1` — the positional chunk indices.
    const unsigned = await Effect.runPromise(
      buildUnsignedFieldPreimageCertificationV1Program(harness.lucid, {
        plan,
        certificatePolicyId: policyId,
        certificateAddress: address,
        certificateScript: policy,
        // Deliberately out of ledger order: the indices the redeemer carries
        // must be indices into the *sorted* reference-input list, and a builder
        // that used the order it was handed would be right until the first
        // transaction whose UTxOs sorted differently.
        chunkUtxos: [...chunkUtxos].reverse(),
        compactCbor: "ab".repeat(400),
        witnessSetCompactCbor: "cd".repeat(100),
      }),
    );
    const signed = await unsigned.sign.withWallet().complete();
    const certificationBytes = signed.toCBOR().length / 2;
    await harness.lucid.awaitTx(await signed.submit());

    // A certification is small — it re-carries no chunk bytes — and therefore
    // fits the real limit even though the publications it references do not.
    expect(certificationBytes).toBeLessThanOrEqual(MAX_L1_TX_BYTES);

    const certificateUtxos = await harness.lucid.utxosAt(address);
    expect(certificateUtxos.length).toBe(1);
    const certificateUtxo = certificateUtxos[0];
    if (certificateUtxo === undefined) {
      throw new Error("certificate UTxO was not found");
    }

    // The manifest comes back off the ledger and matches what was planned —
    // decoded from CBOR, with the asset name taken from the minted token rather
    // than from the plan.
    const resolvedCertificate = resolveCertificateFromLedger(
      certificateUtxo,
      policyId,
    );
    expect(resolvedCertificate).toEqual({
      certificate: plan.certificate,
      certificateAssetName: plan.certificateAssetName,
    });

    // And the whole tier-3 read runs with that ledger-resolved certificate in
    // the certificate slot, rather than the plan's own copy.
    const lastIndex = itemCount - 1;
    const layout = layOutMidgardFieldCarriageV1({ plan });
    const view = authenticatedMidgardFieldViewV1({
      fieldIndex: plan.fieldIndex,
      txId: plan.txId,
      expectedCommitment: plan.commitment,
      carriage: layout.carriage,
      referenceInputs: [
        resolvedCertificate,
        ...plan.publications.map((publication) => ({
          inlineDatumBytes: publication.bytes,
        })),
      ],
    });
    expect(midgardFieldItemAtV1(view, lastIndex)).toEqual(
      itemPayloadAt(preimage, lastIndex),
    );

    // §8.7's recertify half: a second identity mints an interchangeable
    // certificate over the same chunks. Only the `owner` differs, and no
    // consuming step reads it.
    const healedPlan = healMidgardFieldCarriageV1({
      healer: keyHash(HEALER_KEY),
      txId: TX_ID,
      fieldIndex: FIELD_INDEX,
      preimage,
    });
    expect(deriveFieldPreimageCertificationV1(healedPlan).assetNameHex).toBe(
      deriveFieldPreimageCertificationV1(plan).assetNameHex,
    );

    // The burn half of §8.7's yank mode is **not** exercised here and cannot
    // be: retirement spends the certificate output, and that needs the compiled
    // spend handler #579's blueprint carries. `certificate_spend_cost` and
    // `certificate_spend_*` in the Aiken suite are where the burn path is
    // proved. What is checked here is that the off-chain half of it — the
    // `Retire` redeemer an off-chain burner emits — is the frozen Constr tag 1
    // the policy branches on.
    expect(retireFieldPreimageCertificateRedeemerV1()).toBe("d87a80");
  }, 300_000);

  it("orders reference-input indices the way the ledger does, not the way it was handed them", () => {
    const plan = planMidgardFieldCarriageV1({
      owner: keyHash(PUBLISHER_KEY),
      txId: TX_ID,
      fieldIndex: FIELD_INDEX,
      preimage: fieldPreimage(
        itemCountForPreimageBytes(
          MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1,
        ),
      ),
    });
    // Three synthetic UTxOs whose canonical (txHash, outputIndex) order is the
    // reverse of the §8.4 chunk order, so a resolver that returned positions in
    // the order it was given would return [0, 1, 2] and be wrong.
    const utxos: UTxO[] = plan.publications.map((publication, offset) => ({
      txHash: `${(9 - offset).toString().repeat(2)}`.repeat(32).slice(0, 64),
      outputIndex: 0,
      address: PUBLISHER_ADDRESS,
      assets: { lovelace: 1n },
      datum: fieldPreimagePublicationDatumCborV1(publication.bytes),
    }));
    expect(
      resolveChunkReferenceIndicesV1({ plan, referenceInputs: utxos }),
    ).toEqual([2, 1, 0]);
    // Handing them in a different order changes nothing, which is the property.
    expect(
      resolveChunkReferenceIndicesV1({
        plan,
        referenceInputs: [...utxos].reverse(),
      }),
    ).toEqual([2, 1, 0]);
  });

  it("refuses to locate a chunk that is not among the reference inputs", () => {
    const plan = planMidgardFieldCarriageV1({
      owner: keyHash(PUBLISHER_KEY),
      txId: TX_ID,
      fieldIndex: FIELD_INDEX,
      preimage: fieldPreimage(
        itemCountForPreimageBytes(
          MIDGARD_MAX_TRANSACTION_AGGREGATE_FIELD_BYTES_V1,
        ),
      ),
    });
    expect(() =>
      resolveChunkReferenceIndicesV1({ plan, referenceInputs: [] }),
    ).toThrow("is not among the transaction's reference inputs");
  });
});
