import { spawnSync } from "node:child_process";
import {
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { after, describe, test } from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";

import {
  createTree,
  globToRegExp,
  workflowStep,
} from "./affected-channels.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const script = join(here, "affected-channels.mjs");
const realTable = join(here, "channels.json");
const skillRoot = resolve(here, "..");
const repositoryRoot = resolve(here, "../../../..");

const scratch = mkdtempSync(join(tmpdir(), "affected-channels-test-"));
after(() => rmSync(scratch, { recursive: true, force: true }));

const invoke = (args, cwd = scratch) => {
  // The ceiling keeps git from finding a repository above the scratch
  // directory, so "not a repository" stays true wherever tmpdir lives.
  const result = spawnSync(process.execPath, [script, ...args], {
    cwd,
    encoding: "utf8",
    env: { ...process.env, GIT_CEILING_DIRECTORIES: scratch },
  });
  return { code: result.status, out: result.stdout, err: result.stderr };
};

const git = (root, ...args) => {
  const result = spawnSync(
    "git",
    [
      "-c",
      "user.name=fixture",
      "-c",
      "user.email=fixture@example.invalid",
      "-c",
      "commit.gpgsign=false",
      "-c",
      "core.hooksPath=/dev/null",
      ...args,
    ],
    { cwd: root, encoding: "utf8" },
  );
  assert.equal(result.status, 0, `git ${args.join(" ")}: ${result.stderr}`);
  return result.stdout;
};

const write = (root, file, content) => {
  mkdirSync(dirname(join(root, file)), { recursive: true });
  writeFileSync(join(root, file), content);
};

// A miniature repository with one golden channel: a generator in a workspace
// package that emits a JSON fixture and an Aiken module importing a helper.
const fixtureTable = {
  inputSets: { "@shared": ["demo/shared.mjs"] },
  channels: [
    {
      id: "x-golden",
      kind: "golden",
      summary: "fixture channel",
      generators: ["demo/pkg-a/scripts/generate-x.mjs"],
      packageScripts: [
        "demo/pkg-a:fixtures:x:sync",
        "demo/pkg-a:fixtures:x:check",
      ],
      producers: ["demo/pkg-a"],
      inputs: ["@shared"],
      outputs: [
        "demo/pkg-a/tests/fixtures/x.generated.json",
        "onchain/aiken/lib/m/x-golden.test.ak",
      ],
      aikenImportsOfOutputs: true,
      sync: { run: "pnpm --dir demo/pkg-a run fixtures:x:sync" },
      check: { run: "pnpm --dir demo/pkg-a run fixtures:x:check" },
      ci: {
        workflow: ".github/workflows/ci.yml",
        step: "Check x golden vectors",
      },
    },
    {
      id: "y-doc",
      kind: "doc",
      summary: "reads the x fixture",
      generators: ["demo/pkg-b/scripts/sync-y.mjs"],
      packageScripts: ["demo/pkg-b:docs:y:sync"],
      inputs: ["demo/pkg-a/tests/fixtures/x.generated.json"],
      outputs: ["docs/y.md"],
      sync: { run: "pnpm --dir demo/pkg-b run docs:y:sync" },
      check: { none: "no check mode" },
      ci: { none: "not in CI" },
    },
  ],
  ignored: [],
};

const makeRepository = (name, { table = fixtureTable, init = true } = {}) => {
  const root = join(scratch, name);
  write(
    root,
    "demo/pkg-a/package.json",
    JSON.stringify({
      name: "@x/a",
      scripts: {
        "fixtures:x:sync": "node scripts/generate-x.mjs",
        "fixtures:x:check": "node scripts/generate-x.mjs --check",
      },
    }),
  );
  write(root, "demo/pkg-a/src/index.ts", "export const x = 1;\n");
  write(
    root,
    "demo/pkg-a/scripts/generate-x.mjs",
    'const out = "onchain/aiken/lib/m/x-golden.test.ak";\n',
  );
  write(root, "demo/pkg-a/tests/fixtures/x.generated.json", "{}\n");
  write(
    root,
    "demo/pkg-b/package.json",
    JSON.stringify({
      name: "@x/b",
      dependencies: { "@x/a": "workspace:*" },
      scripts: { "docs:y:sync": "node scripts/sync-y.mjs" },
    }),
  );
  write(root, "demo/pkg-b/scripts/sync-y.mjs", "// writes docs/y.md\n");
  write(root, "demo/shared.mjs", "export {};\n");
  write(root, "docs/y.md", "# y\n");
  write(
    root,
    "onchain/aiken/lib/m/x-golden.test.ak",
    "// Generated by demo/pkg-a/scripts/generate-x.mjs\nuse m/helper\n",
  );
  write(root, "onchain/aiken/lib/m/helper.ak", "pub const h = 1\n");
  write(root, "onchain/aiken/lib/m/unrelated.ak", "pub const u = 1\n");
  write(root, "README.md", "# fixture\n");
  write(
    root,
    ".github/workflows/ci.yml",
    "name: CI\njobs:\n  a:\n    steps:\n      - name: Check x golden vectors\n        run: pnpm --dir demo/pkg-a run fixtures:x:check\n      - name: Other\n        run: echo\n",
  );
  write(root, "table.json", JSON.stringify(table, null, 2));
  if (init) {
    git(root, "init", "-q", "-b", "main");
    git(root, "add", "-A");
    git(root, "commit", "-q", "-m", "fixture");
  }
  return root;
};

const withRoot = (root, ...args) => [
  "--root",
  root,
  "--table",
  join(root, "table.json"),
  ...args,
];

describe("glob matching", () => {
  test("** spans directories, * stays in one segment, braces alternate", () => {
    assert.ok(globToRegExp("demo/**/src/*.ts").test("demo/a/b/src/x.ts"));
    assert.ok(
      globToRegExp("**/scripts/generate-*").test("scripts/generate-a.sh"),
    );
    assert.ok(!globToRegExp("demo/*/x.ts").test("demo/a/b/x.ts"));
    assert.ok(globToRegExp("a.{json,ak}").test("a.ak"));
    assert.ok(!globToRegExp("a.{json,ak}").test("a.ts"));
  });

  test("workflowStep returns the named step only", () => {
    const source =
      "steps:\n  - name: A\n    run: one\n  - name: B\n    run: two\n";
    assert.match(workflowStep(source, "A"), /one/u);
    assert.doesNotMatch(workflowStep(source, "A"), /two/u);
    assert.equal(workflowStep(source, "C"), undefined);
  });
});

describe("mapping changed files to channels", () => {
  const root = makeRepository("mapping");

  test("a producer source change affects the channel and prints its commands", () => {
    const result = invoke(withRoot(root, "--files", "demo/pkg-a/src/index.ts"));
    assert.equal(result.code, 0, result.err);
    assert.match(result.out, /x-golden {2}\[golden\]/u);
    assert.match(
      result.out,
      /check {4}pnpm --dir demo\/pkg-a run fixtures:x:check/u,
    );
    assert.match(
      result.out,
      /sync {5}pnpm --dir demo\/pkg-a run fixtures:x:sync/u,
    );
    assert.match(
      result.out,
      /ci {7}\.github\/workflows\/ci\.yml \/ Check x golden vectors/u,
    );
  });

  test("a dependent package does not make the upstream channel stale", () => {
    write(root, "demo/pkg-b/src/index.ts", "export {};\n");
    const result = invoke(withRoot(root, "--files", "demo/pkg-b/src/index.ts"));
    assert.equal(result.code, 0, result.err);
    assert.match(result.out, /no generated-artifact channel is affected/u);
  });

  test("a module the generated Aiken imports is an input", () => {
    const result = invoke(
      withRoot(root, "--files", "onchain/aiken/lib/m/helper.ak", "--json"),
    );
    assert.equal(result.code, 0, result.err);
    const report = JSON.parse(result.out);
    assert.deepEqual(
      report.channels.map((c) => c.id),
      ["x-golden", "y-doc"],
    );
    assert.match(
      report.channels[0].reasons[0],
      /imported by x-golden\.test\.ak/u,
    );
    assert.match(report.channels[1].reasons[0], /regenerated by x-golden/u);
  });

  test("an unrelated file affects nothing, with exit 0", () => {
    const result = invoke(
      withRoot(
        root,
        "--files",
        "README.md",
        "onchain/aiken/lib/m/unrelated.ak",
      ),
    );
    assert.equal(result.code, 0, result.err);
    assert.match(
      result.out,
      /looked: no generated-artifact channel is affected/u,
    );
  });

  test("a hand edit of an output is reported against its channel", () => {
    const result = invoke(
      withRoot(
        root,
        "--files",
        "onchain/aiken/lib/m/x-golden.test.ak",
        "--json",
      ),
    );
    const report = JSON.parse(result.out);
    assert.equal(report.channels[0].id, "x-golden");
    assert.match(
      report.channels[0].reasons[0],
      /output: hand edit or regeneration/u,
    );
  });

  test("git mode sees modified and untracked files against the base", () => {
    write(root, "demo/pkg-a/src/index.ts", "export const x = 2;\n");
    write(root, "demo/shared.mjs", "export const shared = 1;\n");
    const result = invoke(withRoot(root, "--json"));
    assert.equal(result.code, 0, result.err);
    const report = JSON.parse(result.out);
    assert.ok(report.changedFiles.includes("demo/pkg-a/src/index.ts"));
    assert.ok(
      report.changedFiles.includes("demo/pkg-b/src/index.ts"),
      "untracked files count",
    );
    assert.equal(report.channels[0].id, "x-golden");
  });

  test("git mode with --base diffs against the merge-base", () => {
    git(root, "checkout", "-q", "-b", "topic");
    git(root, "add", "-A");
    git(root, "commit", "-q", "-m", "topic change");
    const clean = invoke(withRoot(root, "--json"));
    assert.equal(JSON.parse(clean.out).changedFiles.length, 0);
    const against = invoke(withRoot(root, "--base", "main", "--json"));
    assert.equal(against.code, 0, against.err);
    assert.ok(
      JSON.parse(against.out).changedFiles.includes("demo/pkg-a/src/index.ts"),
    );
  });
});

describe("could not look is not the same as nothing affected", () => {
  test("outside a git repository the diff cannot be read: exit 2", () => {
    const root = makeRepository("not-a-repository", { init: false });
    const result = invoke(withRoot(root));
    assert.equal(result.code, 2);
    assert.match(result.err, /could not look: could not read git diff/u);
    assert.doesNotMatch(
      result.out,
      /no generated-artifact channel is affected/u,
    );
  });

  test("an unknown base ref: exit 2", () => {
    const root = makeRepository("bad-ref");
    const result = invoke(withRoot(root, "--base", "no-such-ref"));
    assert.equal(result.code, 2);
    assert.match(
      result.err,
      /could not read git diff: resolving base no-such-ref/u,
    );
  });

  test("an unreadable table: exit 2", () => {
    const result = invoke([
      "--table",
      join(scratch, "missing.json"),
      "--files",
      "README.md",
    ]);
    assert.equal(result.code, 2);
    assert.match(result.err, /could not read the channel table/u);
  });

  test("--json reports could-not-look as its own status", () => {
    const root = makeRepository("bad-ref-json");
    const result = invoke(withRoot(root, "--base", "no-such-ref", "--json"));
    assert.equal(result.code, 2);
    assert.equal(JSON.parse(result.out).status, "could-not-look");
  });

  test("bad arguments: exit 2", () => {
    assert.equal(invoke(["--base"]).code, 2);
    assert.equal(invoke(["--bogus"]).code, 2);
  });
});

describe("--verify-table", () => {
  test("a table that matches the tree passes", () => {
    const root = makeRepository("verify-clean");
    const result = invoke(withRoot(root, "--verify-table"));
    assert.equal(result.code, 0, result.out + result.err);
    assert.match(result.out, /verify-table: ok/u);
  });

  test("an unmapped generator fails, in both modes", () => {
    const root = makeRepository("verify-unmapped");
    write(root, "demo/pkg-a/scripts/generate-z.mjs", "// new generator\n");
    git(root, "add", "-A");
    const verify = invoke(withRoot(root, "--verify-table"));
    assert.equal(verify.code, 1);
    assert.match(
      verify.out,
      /generate-z\.mjs looks like a generator but no channel claims it/u,
    );
    const mapping = invoke(
      withRoot(root, "--files", "demo/pkg-a/scripts/generate-z.mjs"),
    );
    assert.equal(mapping.code, 1);
    assert.match(
      mapping.out,
      /PROBLEM: .*generate-z\.mjs looks like a generator/u,
    );
  });

  test("an unmapped ledger, generated file, package script or writer env fails", () => {
    const root = makeRepository("verify-unclaimed");
    write(root, "onchain/aiken/scripts/new-exec-ledger-v1.json", "{}\n");
    write(root, "demo/pkg-a/tests/fixtures/z.generated.json", "{}\n");
    write(
      root,
      "demo/pkg-a/tests/marked.json",
      '{"_note": "Generated by something; do not edit."}\n',
    );
    write(
      root,
      "demo/pkg-a/src/writer.ts",
      "if (process.env.MIDGARD_WRITE_Z_FIXTURE) {}\n",
    );
    const manifest = JSON.parse(
      readFileSync(join(root, "demo/pkg-a/package.json"), "utf8"),
    );
    manifest.scripts["fixtures:z:sync"] = "true";
    write(root, "demo/pkg-a/package.json", JSON.stringify(manifest));
    git(root, "add", "-A");
    const result = invoke(withRoot(root, "--verify-table"));
    assert.equal(result.code, 1);
    assert.match(result.out, /new-exec-ledger-v1\.json looks like a ledger/u);
    assert.match(result.out, /z\.generated\.json looks generated/u);
    assert.match(result.out, /marked\.json looks generated/u);
    assert.match(result.out, /package script demo\/pkg-a:fixtures:z:sync/u);
    assert.match(result.out, /writer env MIDGARD_WRITE_Z_FIXTURE/u);
  });

  test("stale declarations fail: missing step, script, command target, output path", () => {
    const table = structuredClone(fixtureTable);
    table.channels[0].ci.step = "Renamed step";
    table.channels[0].check.run = "pnpm --dir demo/pkg-a run fixtures:x:gone";
    table.channels[0].outputs.push("onchain/aiken/lib/m/deleted.ak");
    table.channels[1].sync = {
      run: "make no-such-target && node demo/missing.mjs",
    };
    table.ignored.push({ path: "demo/gone.mjs", why: "gone" });
    const root = makeRepository("verify-stale", { table });
    const result = invoke(withRoot(root, "--verify-table"));
    assert.equal(result.code, 1);
    assert.match(result.out, /no step "Renamed step"/u);
    assert.match(result.out, /no script "fixtures:x:gone"/u);
    assert.match(
      result.out,
      /output onchain\/aiken\/lib\/m\/deleted\.ak matches no tracked file/u,
    );
    assert.match(result.out, /make: no target no-such-target/u);
    assert.match(result.out, /node: demo\/missing\.mjs does not exist/u);
    assert.match(result.out, /ignored path demo\/gone\.mjs is gone/u);
  });

  test("a generator naming an Aiken path outside its outputs fails", () => {
    const root = makeRepository("verify-generator-target");
    write(
      root,
      "demo/pkg-a/scripts/generate-x.mjs",
      'const a = "onchain/aiken/lib/m/x-golden.test.ak";\nconst b = "onchain/aiken/lib/m/helper.ak";\n',
    );
    git(root, "add", "-A");
    const result = invoke(withRoot(root, "--verify-table"));
    assert.equal(result.code, 1);
    assert.match(
      result.out,
      /names onchain\/aiken\/lib\/m\/helper\.ak, which is not among the channel's outputs/u,
    );
  });

  test("a CI step that runs something else fails", () => {
    const root = makeRepository("verify-ci-token");
    write(
      root,
      ".github/workflows/ci.yml",
      "name: CI\njobs:\n  a:\n    steps:\n      - name: Check x golden vectors\n        run: echo nothing\n",
    );
    git(root, "add", "-A");
    const result = invoke(withRoot(root, "--verify-table"));
    assert.equal(result.code, 1);
    assert.match(result.out, /mentions none of the channel's check command/u);
  });
});

// Read-only checks against this repository's own tree.
describe("the real table", () => {
  test("covers every generator, ledger and generated file in this tree", () => {
    const result = invoke(["--verify-table"], repositoryRoot);
    assert.equal(result.code, 0, result.out + result.err);
  });

  test("every channel is documented in references/channels.md", () => {
    const table = JSON.parse(readFileSync(realTable, "utf8"));
    const reference = readFileSync(
      join(skillRoot, "references/channels.md"),
      "utf8",
    );
    for (const channel of table.channels) {
      assert.ok(
        reference.includes(`\`${channel.id}\``),
        `${channel.id} missing from references/channels.md`,
      );
    }
  });

  test("every [ci: ...] tag in the skill names a real workflow step", () => {
    const tree = createTree(repositoryRoot);
    const workflows = new Map();
    for (const file of readdirSync(join(repositoryRoot, ".github/workflows"))) {
      const source = tree.read(`.github/workflows/${file}`);
      const name = /^name:\s*(.+?)\s*$/mu.exec(source ?? "")?.[1];
      if (name) workflows.set(name, source);
    }
    const markdown = [
      join(skillRoot, "SKILL.md"),
      ...readdirSync(join(skillRoot, "references")).map((f) =>
        join(skillRoot, "references", f),
      ),
    ];
    let tags = 0;
    for (const file of markdown) {
      for (const match of readFileSync(file, "utf8").matchAll(
        /\[ci: ([^/\]]+)\/([^\]]+)\]/gu,
      )) {
        tags += 1;
        const source = workflows.get(match[1]);
        assert.ok(source, `${file}: no workflow named "${match[1]}"`);
        assert.ok(
          workflowStep(source, match[2]),
          `${file}: no step "${match[2]}" in ${match[1]}`,
        );
      }
    }
    assert.ok(
      tags > 0,
      "the skill cites no CI steps, so this check proved nothing",
    );
  });
});
