import { existsSync, mkdirSync } from "node:fs";

import { DEPLOYMENT_MANIFEST_L1_FINALITY } from "@al-ft/midgard-core/deployment-manifest-identity";

import { psql } from "./chain.js";
import { type DeployContext, nodeCli } from "./deploy.js";
import { requireSuccess } from "./exec.js";
import { type Identities, walletInfo } from "./identities.js";
import { type Layout, type RunEnv, servicePorts } from "./layout.js";
import { DA_THRESHOLD, type HubOracleOneShot } from "./node-env.js";

export const COMMITTEE_SIZE = 2;
export const PUBLIC_READER_ROLE = "midgard_public_retained_da";
/** Member roles: every member attests, may submit to L1 and serves retrieval. */
const MEMBER_ROLES = "committee+coordinator+retrieval";
/** Satisfies both the source and the native-ledger authority id grammars. */
export const LOCAL_AUTHORITY_ID = "local-cardano-node";

export const committeeDatabase = (index: number) => `da_committee_${index}`;

/**
 * The deployed committee is the operator key and the cosigner key, emitted
 * sorted by verification key (`deriveOperatorDaParams`); a member's signer
 * index is its position in that order.
 */
export const committeeMembers = (identities: Identities) =>
  [identities.seeds.operator, identities.seeds.daCosigner]
    .map((seed) => ({ seed, vkey: walletInfo(seed).paymentVkey }))
    .sort((left, right) => (left.vkey < right.vkey ? -1 : 1))
    .map((member, index) => ({
      ...member,
      index,
      submitterSeed: [
        identities.seeds.daSubmitter0,
        identities.seeds.daSubmitter1,
      ][index]!,
      availabilitySeed: [
        identities.seeds.daAvailability0,
        identities.seeds.daAvailability1,
      ][index]!,
      libp2pSeed: [identities.libp2p.committee0, identities.libp2p.committee1][
        index
      ]!,
    }));

export const databaseUrl = (
  run: RunEnv,
  database: string,
  user = run.postgresUser,
  password = run.postgresPassword,
) =>
  `postgres://${encodeURIComponent(user)}:${encodeURIComponent(password)}@127.0.0.1:${run.postgresPort}/${database}`;

/** One database per committee member; created once, never recreated. */
export const ensureCommitteeDatabases = async (layout: Layout, run: RunEnv) => {
  for (let index = 0; index < COMMITTEE_SIZE; index += 1) {
    const name = committeeDatabase(index);
    await psql(
      layout,
      run,
      "postgres",
      `SELECT 'CREATE DATABASE ${name}' WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${name}')\\gexec\n`,
      `create-${name}`,
    );
  }
};

/**
 * The public retained-DA reader: a login role with SELECT on exactly the two
 * tables it serves, in member 0's database. The tables exist only once that
 * member has migrated its store, so this is retried until it succeeds.
 */
export const grantPublicReader = async (
  layout: Layout,
  run: RunEnv,
  identities: Identities,
): Promise<boolean> => {
  const password = identities.publicReaderPassword;
  const tables = await psql(
    layout,
    run,
    committeeDatabase(0),
    "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name IN ('committee_da_payloads', 'committee_state_queue_headers');\n",
    "public-reader-tables",
  );
  if (tables !== "2") return false;
  await psql(
    layout,
    run,
    committeeDatabase(0),
    [
      `SELECT 'CREATE ROLE ${PUBLIC_READER_ROLE} LOGIN' WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${PUBLIC_READER_ROLE}')\\gexec`,
      `ALTER ROLE ${PUBLIC_READER_ROLE} WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD '${password}';`,
      `GRANT USAGE ON SCHEMA public TO ${PUBLIC_READER_ROLE};`,
      `REVOKE ALL ON committee_da_payloads, committee_state_queue_headers FROM ${PUBLIC_READER_ROLE};`,
      `GRANT SELECT ON committee_da_payloads, committee_state_queue_headers TO ${PUBLIC_READER_ROLE};`,
      "",
    ].join("\n"),
    "public-reader-grant",
  );
  return true;
};

/**
 * Producer and per-member libp2p runtime manifests, generated by the node's
 * supported command from the finalized contract manifest. Each is written
 * once; the member keys and ports they bind never change for a run.
 */
export const ensureDaManifests = async (
  context: DeployContext,
  oneShot: HubOracleOneShot,
) => {
  const { layout, run, identities } = context;
  const ports = servicePorts(run);
  const members = committeeMembers(identities);
  const common = [
    "--profile",
    "host",
    "--contract-deployment-info",
    layout.contractManifest,
    "--producer-libp2p-key-source",
    `seed:${identities.libp2p.producer}`,
    "--public-retained-da-libp2p-key-source",
    `seed:${identities.libp2p.retained}`,
    "--threshold",
    String(DA_THRESHOLD),
    "--network",
    "Custom",
    "--producer-port",
    String(ports.producerLibp2p),
    "--public-retained-da-port",
    String(ports.retainedLibp2p),
    ...members.flatMap((member) => [
      "--committee-member",
      `${member.index},${member.vkey},seed:${member.libp2pSeed},${MEMBER_ROLES},${ports.committeeLibp2p(member.index)}`,
    ]),
  ];
  const generate = async (
    out: string,
    target: readonly string[],
    label: string,
  ) => {
    if (existsSync(out)) return;
    requireSuccess(
      await nodeCli(
        context,
        ["da-libp2p-generate-manifest", ...target, ...common, "--out", out],
        label,
        oneShot,
      ),
      label,
    );
  };
  await generate(
    layout.producerManifest,
    ["--target", "producer"],
    "da-manifest-producer",
  );
  for (const member of members)
    await generate(
      layout.committeeManifest(member.index),
      ["--target", "committee", "--local-signer-index", String(member.index)],
      `da-manifest-committee-${member.index}`,
    );
};

const kupmios = (run: RunEnv) =>
  `kupmios:http://127.0.0.1:${run.kupoPort}|http://127.0.0.1:${run.ogmiosPort}`;

/** A committee member's complete environment, from the run's records only. */
export const committeeEnvironment = (input: {
  readonly layout: Layout;
  readonly run: RunEnv;
  readonly identities: Identities;
  readonly transportBinary: string;
  readonly index: number;
}): Record<string, string> => {
  const { layout, run, identities, transportBinary, index } = input;
  const member = committeeMembers(identities)[index];
  if (member === undefined) throw new Error(`no committee member ${index}`);
  const data = layout.committeeData(index);
  mkdirSync(data, { recursive: true, mode: 0o700 });
  return {
    MIDGARD_CONFIG_MODE: "disabled",
    MIDGARD_DOTENV_MODE: "disabled",
    MIDGARD_NETWORK: "Custom",
    MIDGARD_DEPLOYMENT_MANIFEST_PATH: layout.committeeManifest(index),
    MIDGARD_CONTRACT_DEPLOYMENT_INFO_PATH: layout.contractManifest,
    CARDANO_PROVIDER_URLS: kupmios(run),
    CARDANO_L1_SOURCE_MODE: "local_node",
    CARDANO_LOCAL_NODE_AUTHORITY_ID: LOCAL_AUTHORITY_ID,
    CARDANO_LOCAL_NODE_CHAIN_SYNC_URL: `chain-sync:${kupmios(run)}`,
    CARDANO_LOCAL_NODE_CHAIN_SYNC_CURSOR_PATH: `${data}/chain-sync-cursor.json`,
    CARDANO_LOCAL_NODE_SOCKET_PATH: layout.cardanoSocket,
    CARDANO_LOCAL_NODE_CONFIG_PATH: layout.hostCardanoConfig,
    CARDANO_NATIVE_CHAIN_SYNC_BINARY_PATH: transportBinary,
    CARDANO_NETWORK_MAGIC: String(run.networkMagic),
    // The committee refuses any value but its manifest's confirmation depth,
    // which is the compiled deployment profile's.
    CARDANO_FINALITY_DEPTH: String(
      DEPLOYMENT_MANIFEST_L1_FINALITY.confirmationDepth,
    ),
    DA_SIGNER_INDEX: String(member.index),
    DA_SIGNER_KEY_SOURCE: `cardano-seed:${member.seed}`,
    DA_L1_SUBMISSION_ENABLED: "true",
    DA_L1_PREFLIGHT_ENABLED: "true",
    L1_SUBMITTER_KEY_SOURCE: `seed:${member.submitterSeed}`,
    DA_AVAILABILITY_SUBMITTER_KEY_SOURCE: `seed:${member.availabilitySeed}`,
    DA_AVAILABILITY_JOURNAL_PATH: `${data}/availability-journal.jsonl`,
    DA_COMMITTEE_DATABASE_URL: databaseUrl(run, committeeDatabase(index)),
    DA_COMMITTEE_API_HOST: "127.0.0.1",
    DA_COMMITTEE_API_PORT: String(servicePorts(run).committeeApi(index)),
    DA_COMMITTEE_POLL_INTERVAL_MS: "2000",
    DA_LIBP2P_PRIVATE_KEY_SOURCE: `seed:${member.libp2pSeed}`,
  };
};

/** The public retained-DA reader: no committee store, signer or provider. */
export const publicRetainedDaEnvironment = (input: {
  readonly layout: Layout;
  readonly run: RunEnv;
  readonly identities: Identities;
}): Record<string, string> => {
  const { layout, run, identities } = input;
  return {
    MIDGARD_CONFIG_MODE: "disabled",
    MIDGARD_DOTENV_MODE: "disabled",
    MIDGARD_NETWORK: "Custom",
    DA_PUBLIC_RETAINED_DA_ENABLED: "true",
    DA_PUBLIC_RETAINED_DA_HEALTH_HOST: "127.0.0.1",
    DA_PUBLIC_RETAINED_DA_HEALTH_PORT: String(
      servicePorts(run).publicRetainedDaHealth,
    ),
    MIDGARD_DEPLOYMENT_MANIFEST_PATH: layout.committeeManifest(0),
    MIDGARD_CONTRACT_DEPLOYMENT_INFO_PATH: layout.contractManifest,
    DA_PUBLIC_RETAINED_DA_PRIVATE_KEY_SOURCE: `seed:${identities.libp2p.retained}`,
    DA_PUBLIC_RETAINED_DA_DATABASE_URL: databaseUrl(
      run,
      committeeDatabase(0),
      PUBLIC_READER_ROLE,
      identities.publicReaderPassword,
    ),
    DA_PUBLIC_RETAINED_DA_DATABASE_ROLE: PUBLIC_READER_ROLE,
  };
};
