import { type SupportedFaultProofCategoryName } from "./runtime.require-fault-proof-step-reference-script.js";

/**
 * Canonical manifest entries in the same order as each SDK chain's `steps`.
 *
 * The older families still have only their historical first-step deployment
 * entry. Every category registered by the current append wave names every
 * step, so production resolution cannot silently fall back to an inline
 * validator for a later transition.
 */
export const FRAUD_PROOF_DEPLOYMENT_ENTRIES_BY_CATEGORY = {
  doubleSpend: ["fraudProofDoubleSpend"],
  nonExistentInput: ["fraudProofNonExistentInput"],
  nonExistentInputNoIndex: ["fraudProofNonExistentInputNoIndex"],
  invalidRange: ["fraudProofInvalidRange"],
  transitionTrace: [
    "fraudProofTransitionTrace",
    "fraudProofTransitionTraceControl",
    "fraudProofTransitionTraceSource",
    "fraudProofTransitionTraceWithdrawal",
    "fraudProofTransitionTraceForced",
    "fraudProofTransitionTraceAcceptedTransaction",
    "fraudProofTransitionTraceDeposit",
    "fraudProofTransitionTraceL1Event",
    "fraudProofTransitionTraceDuplicate",
  ],
  zeroInput: ["fraudProofZeroInput"],
  validationTraceDispute: ["validationTraceDispute"],
  daHashPreimage: ["fraudProofDaHashPreimage"],
  noReferenceInput: ["fraudProofNoReferenceInput"],
  referenceInputNoIdx: ["fraudProofReferenceInputNoIdx"],
  invalidSignature: ["fraudProofInvalidSignature"],
  fabricatedDeposit: [
    "fraudProofFabricatedDeposit",
    "fraudProofFabricatedDepositStep02",
    "fraudProofFabricatedDepositStep03",
    "fraudProofFabricatedDepositStep04",
  ],
  fabricatedWithdrawal: [
    "fraudProofFabricatedWithdrawal",
    "fraudProofFabricatedWithdrawalStep02",
    "fraudProofFabricatedWithdrawalStep03",
    "fraudProofFabricatedWithdrawalStep04",
  ],
  nativeScriptDecoding: [
    "fraudProofNativeScriptDecoding",
    "fraudProofNativeScriptDecodingStep02",
    "fraudProofNativeScriptDecodingStep03OpenSubject",
    "fraudProofNativeScriptDecodingStep03BindDescriptor",
    "fraudProofNativeScriptDecodingStep03AdvanceOrClose",
    "fraudProofNativeScriptDecodingStep04",
  ],
  missingSignature: [
    "fraudProofMissingSignature",
    "fraudProofMissingSignatureStep02",
    "fraudProofMissingSignatureStep03",
    "fraudProofMissingSignatureStep04",
  ],
  missingNativeScriptTx: [
    "fraudProofMissingNativeScriptTx",
    "fraudProofMissingNativeScriptTxStep02",
    "fraudProofMissingNativeScriptTxStep03",
    "fraudProofMissingNativeScriptTxStep04",
    "fraudProofMissingNativeScriptTxStep05",
    "fraudProofMissingNativeScriptTxStep06",
    "fraudProofMissingNativeScriptTxStep07",
    "fraudProofMissingNativeScriptTxStep08",
  ],
  withdrawnReferenceInput: [
    "fraudProofWithdrawnReferenceInput",
    "fraudProofWithdrawnReferenceInputStep02",
    "fraudProofWithdrawnReferenceInputStep03",
  ],
  canonicalDecodability: [
    "fraudProofCanonicalDecodability",
    "fraudProofCanonicalDecodabilityStep02",
  ],
  committedFieldShape: [
    "fraudProofCommittedFieldShape",
    "fraudProofCommittedFieldShapeStep02",
  ],
  minFee: ["fraudProofMinFee", "fraudProofMinFeeStep02"],
  withdrawalMistag: [
    "fraudProofWithdrawalMistag",
    "fraudProofWithdrawalMistagStep02",
    "fraudProofWithdrawalMistagStep03",
    "fraudProofWithdrawalMistagStep04",
    "fraudProofWithdrawalMistagStep05",
  ],
  doubleWithdraw: [
    "fraudProofDoubleWithdraw",
    "fraudProofDoubleWithdrawStep02",
  ],
  crossBlockDuplicateEvent: [
    "fraudProofCrossBlockDuplicateEvent",
    "fraudProofCrossBlockDuplicateEventStep02",
  ],
  l2TxMistag: ["fraudProofL2TxMistag", "fraudProofL2TxMistagStep02"],
  withdrawnInput: [
    "fraudProofWithdrawnInput",
    "fraudProofWithdrawnInputStep02",
    "fraudProofWithdrawnInputStep03",
  ],
  valueNotPreserved: [
    "fraudProofValueNotPreserved",
    "fraudProofValueNotPreservedStep02",
    "fraudProofValueNotPreservedStep03",
    "fraudProofValueNotPreservedStep04",
  ],
  inputSetUniqueness: [
    "fraudProofInputSetUniqueness",
    "fraudProofInputSetUniquenessStep02",
    "fraudProofInputSetUniquenessStep03",
    "fraudProofInputSetUniquenessStep04",
  ],
  mintAuthorization: [
    "fraudProofMintAuthorization",
    "fraudProofMintAuthorizationStep02",
    "fraudProofMintAuthorizationStep03",
    "fraudProofMintAuthorizationStep04",
    "fraudProofMintAuthorizationStep05",
    "fraudProofMintAuthorizationStep06",
    "fraudProofMintAuthorizationStep07",
  ],
  networkId: ["fraudProofNetworkId", "fraudProofNetworkIdStep02"],
  missingNativeScriptUtxo: [
    "fraudProofMissingNativeScriptUtxo",
    "fraudProofMissingNativeScriptUtxoStep02",
    "fraudProofMissingNativeScriptUtxoStep03",
    "fraudProofMissingNativeScriptUtxoStep04",
    "fraudProofMissingNativeScriptUtxoStep05",
    "fraudProofMissingNativeScriptUtxoStep06",
    "fraudProofMissingNativeScriptUtxoStep07",
  ],
  nativeScriptInvalid: [
    "fraudProofNativeScriptInvalid",
    "fraudProofNativeScriptInvalidStep02",
    "fraudProofNativeScriptInvalidStep03",
    "fraudProofNativeScriptInvalidStep04",
    "fraudProofNativeScriptInvalidStep05",
  ],
  minAda: [
    "fraudProofMinAda",
    "fraudProofMinAdaStep02",
    "fraudProofMinAdaStep03",
    "fraudProofMinAdaStep04",
    "fraudProofMinAdaStep05",
  ],
  fieldPreimageLengthMismatch: [
    "fraudProofFieldPreimageLengthMismatch",
    "fraudProofFieldPreimageLengthMismatchStep02Accepted",
    "fraudProofFieldPreimageLengthMismatchStep02Forced",
    "fraudProofFieldPreimageLengthMismatchStep03",
  ],
  fieldItemWidthIllegal: [
    "fraudProofFieldItemWidthIllegal",
    "fraudProofFieldItemWidthIllegalStep02",
    "fraudProofFieldItemWidthIllegalStep03",
  ],
  witnessScriptDecoding: [
    "fraudProofWitnessScriptDecoding",
    "fraudProofWitnessScriptDecodingStep02",
    "fraudProofWitnessScriptDecodingStep03",
    "fraudProofWitnessScriptDecodingStep04",
  ],
  scriptIntegrityHashMissing: [
    "fraudProofScriptIntegrityHashMissing",
    "fraudProofScriptIntegrityHashMissingStep02",
    "fraudProofScriptIntegrityHashMissingStep03",
    "fraudProofScriptIntegrityHashMissingScriptGrammar",
    "fraudProofScriptIntegrityHashMissingScriptScan",
    "fraudProofScriptIntegrityHashMissingRedeemerGrammar",
    "fraudProofScriptIntegrityHashMissingStep04",
  ],
  transactionOutputNonCanonical: [
    "fraudProofTransactionOutputNonCanonical",
    "fraudProofTransactionOutputNonCanonicalStep02",
    "fraudProofTransactionOutputNonCanonicalStep03",
    "fraudProofTransactionOutputNonCanonicalStep04",
  ],
  mintItemNonCanonical: [
    "fraudProofMintItemNonCanonical",
    "fraudProofMintItemNonCanonicalStep02",
    "fraudProofMintItemNonCanonicalStep03",
    "fraudProofMintItemNonCanonicalStep04",
  ],
  resolvedOutputNonCanonical: [
    "fraudProofResolvedOutputNonCanonical",
    "fraudProofResolvedOutputNonCanonicalStep02",
    "fraudProofResolvedOutputNonCanonicalStep03",
    "fraudProofResolvedOutputNonCanonicalStep04",
    "fraudProofResolvedOutputNonCanonicalStep05",
  ],
  mintDeclaredAssetLimit: [
    "fraudProofMintDeclaredAssetLimit",
    "fraudProofMintDeclaredAssetLimitStep02",
    "fraudProofMintDeclaredAssetLimitStep03",
    "fraudProofMintDeclaredAssetLimitStep04",
  ],
  spendInputSignerMissing: [
    "fraudProofSpendInputSignerMissing",
    "fraudProofSpendInputSignerMissingStep02",
    "fraudProofSpendInputSignerMissingStep03",
    "fraudProofSpendInputSignerMissingStep04",
    "fraudProofSpendInputSignerMissingStep05",
  ],
  protectedOutputSignerMissing: [
    "fraudProofProtectedOutputSignerMissing",
    "fraudProofProtectedOutputSignerMissingStep02",
    "fraudProofProtectedOutputSignerMissingStep03",
    "fraudProofProtectedOutputSignerMissingStep04",
    "fraudProofProtectedOutputSignerMissingStep05",
  ],
  observersForbiddenOnUntaggedNetwork: [
    "fraudProofObserversForbiddenOnUntaggedNetwork",
    "fraudProofObserversForbiddenOnUntaggedNetworkStep02",
  ],
  outputReferenceScriptDecoding: [
    "fraudProofOutputReferenceScriptDecoding",
    "fraudProofOutputReferenceScriptDecodingStep02",
    "fraudProofOutputReferenceScriptDecodingStep03",
    "fraudProofOutputReferenceScriptDecodingStep04",
    "fraudProofOutputReferenceScriptDecodingStep05",
    "fraudProofOutputReferenceScriptDecodingStep06",
  ],
  executionSourceScriptDecoding: [
    "fraudProofExecutionSourceScriptDecoding",
    "fraudProofExecutionSourceScriptDecodingStep02",
    "fraudProofExecutionSourceScriptDecodingStep03",
    "fraudProofExecutionSourceScriptDecodingStep04",
    "fraudProofExecutionSourceScriptDecodingStep05",
  ],
  observerOrderInvalid: [
    "fraudProofObserverOrderInvalid",
    "fraudProofObserverOrderInvalidStep02",
    "fraudProofObserverOrderInvalidStep03",
    "fraudProofObserverOrderInvalidStep04",
  ],
  redeemerCanonicity: [
    "fraudProofRedeemerCanonicity",
    "fraudProofRedeemerCanonicityStep02",
    "fraudProofRedeemerCanonicityStep03",
  ],
  receivePurposeLanguage: [
    "fraudProofReceivePurposeLanguage",
    "fraudProofReceivePurposeLanguageStep02",
    "fraudProofReceivePurposeLanguageStep03",
  ],
  unusedScriptWitness: [
    "fraudProofUnusedScriptWitness",
    "fraudProofUnusedScriptWitnessStep02",
    "fraudProofUnusedScriptWitnessStep03",
    "fraudProofUnusedScriptWitnessStep04",
    "fraudProofUnusedScriptWitnessStep05",
    "fraudProofUnusedScriptWitnessStep06",
  ],
  missingScriptSource: [
    "fraudProofMissingScriptSource",
    "fraudProofMissingScriptSourceStep02",
    "fraudProofMissingScriptSourceStep03",
    "fraudProofMissingScriptSourceStep04",
    "fraudProofMissingScriptSourceStep05",
    "fraudProofMissingScriptSourceStep06",
  ],
  missingRedeemer: [
    "fraudProofMissingRedeemer",
    "fraudProofMissingRedeemerStep02",
    "fraudProofMissingRedeemerStep02a",
    "fraudProofMissingRedeemerStep02b",
    "fraudProofMissingRedeemerStep03",
    "fraudProofMissingRedeemerStep04",
    "fraudProofMissingRedeemerStep05",
  ],
  unusedRedeemer: [
    "fraudProofUnusedRedeemer",
    "fraudProofUnusedRedeemerStep02",
    "fraudProofUnusedRedeemerStep02a",
    "fraudProofUnusedRedeemerStep02b",
    "fraudProofUnusedRedeemerStep02c",
    "fraudProofUnusedRedeemerStep03",
    "fraudProofUnusedRedeemerStep04",
    "fraudProofUnusedRedeemerStep05",
    "fraudProofUnusedRedeemerStep06",
  ],
  executionNativeScriptInvalid: [
    "fraudProofExecutionNativeScriptInvalid",
    "fraudProofExecutionNativeScriptInvalidStep02",
    "fraudProofExecutionNativeScriptInvalidStep03",
    "fraudProofExecutionNativeScriptInvalidStep04",
    "fraudProofExecutionNativeScriptInvalidStep05",
    "fraudProofExecutionNativeScriptInvalidStep06",
    "fraudProofExecutionNativeScriptInvalidAcceptedReconstructionInit",
    "fraudProofExecutionNativeScriptInvalidAcceptedSpendPrefix",
    "fraudProofExecutionNativeScriptInvalidAcceptedMintPrefix",
    "fraudProofExecutionNativeScriptInvalidAcceptedObserverPrefix",
    "fraudProofExecutionNativeScriptInvalidAcceptedReceivePrefix",
    "fraudProofExecutionNativeScriptInvalidAcceptedInlineSource",
    "fraudProofExecutionNativeScriptInvalidAcceptedReferenceSource",
  ],
  scriptIntegrityHashMismatch: [
    "fraudProofScriptIntegrityHashMismatch",
    "fraudProofScriptIntegrityHashMismatchStep02",
    "fraudProofScriptIntegrityHashMismatchStep03",
    "fraudProofScriptIntegrityHashMismatchStep04",
    "fraudProofScriptIntegrityHashMismatchStep05",
  ],
  distinctAssetAccumulationLimit: [
    "fraudProofDistinctAssetAccumulationLimit",
    "fraudProofDistinctAssetAccumulationLimitStep02",
    "fraudProofDistinctAssetAccumulationLimitStep03",
    "fraudProofDistinctAssetAccumulationLimitStep04",
    "fraudProofDistinctAssetAccumulationLimitStep05",
    "fraudProofDistinctAssetAccumulationLimitStep06",
  ],
} as const satisfies Record<
  SupportedFaultProofCategoryName,
  readonly [string, ...string[]]
>;
