import "@al-ft/midgard-core/da-transport";
import "@al-ft/midgard-sdk";
import "vitest";
import "../src/coordinator/on-chain.js";
import "../src/coordinator/planner.js";
import "../src/coordinator/pool-backoff.js";
import "../src/coordinator/witnesses.js";
import "./coordinator.candidate-record.js";
import "./coordinator.coordinator-witness-and-candidate-planning.js";
