export {
  authenticWatcherDaBondPool,
  deriveWatcherDaBondPoolObservation,
  type WatcherDaBondPoolObservation,
} from "./availability/pool-observation.js";
export {
  createWatcherFaultDecisionBridge,
  unsafeCreateWatcherFaultDecisionBridgeForTest,
  WATCHER_FAULT_DECISION_BRIDGE_SCHEMA_VERSION,
  type WatcherFaultDecisionBridge,
  type WatcherFaultDecisionBridgeResult,
  type WatcherFaultDecisionTarget,
} from "./fault-proofs/fault-decision-bridge.js";
export {
  openWatcherFaultDecisionJournal,
  readWatcherFaultDecisionEvidence,
  unsafeOpenWatcherFaultDecisionJournalForTest,
  type UnsafeWatcherFaultDecisionJournalForTest,
  WATCHER_FAULT_DECISION_JOURNAL_SCHEMA_VERSION,
  WATCHER_FAULT_DECISION_RECORD_SCHEMA_VERSION,
  type WatcherFaultDecisionJournal,
  type WatcherPersistedFaultDecisionRecord,
} from "./fault-proofs/fault-decision-journal.js";
export {
  createWatcherFaultProofApplication,
  createWatcherFaultProofReadinessApplication,
  unsafeCreateWatcherFaultProofApplicationForTest,
  WATCHER_FAULT_PROOF_APPLICATION,
  WATCHER_FAULT_PROOF_STARTUP_READINESS,
  WATCHER_INSTALLED_WORKFLOW_CATEGORIES,
  WATCHER_MISSING_WORKFLOW_CATEGORIES,
  WATCHER_STARTUP_READINESS_HEADER_HASH,
  type WatcherFaultProofApplication,
  type WatcherFaultProofApplicationDependencies,
  type WatcherFaultProofApplicationOptions,
  type WatcherFaultProofHeaderClassificationInput,
  type WatcherFaultProofInfrastructureAuthority,
  type WatcherFaultProofStartupReadiness,
  type WatcherInstalledWorkflowCategory,
} from "./fault-proofs/fault-proof-application.js";
export {
  createWatcherFaultProofSupervisor,
  unsafeCreateWatcherFaultProofSupervisorForTest,
  type UnsafeWatcherFaultProofSupervisorForTest,
  WATCHER_FAULT_PROOF_SUPERVISOR_SCHEMA_VERSION,
  type WatcherFaultProofDeadline,
  watcherFaultProofDeadline,
  type WatcherFaultProofJob,
  type WatcherFaultProofProgressRequest,
  type WatcherFaultProofSupervisor,
  type WatcherFaultProofSupervisorStatus,
} from "./fault-proofs/fault-proof-supervisor.js";
export {
  isWatcherPreflightStalledResult,
  runWorkflowWithPreflightStallRetries,
  WATCHER_PREFLIGHT_STALL_RETRY_BUDGET_MS,
  WATCHER_PREFLIGHT_STALL_RETRY_DELAY_MS,
  type WatcherPreflightStalledResult,
} from "./fault-proofs/preflight-stall-retry.js";
export {
  assertWatcherProtocolParameterRuntimeAuthority,
  createWatcherProtocolParameterRuntimeAuthority,
  WATCHER_PROTOCOL_PARAMETER_RUNTIME_AUTHORITY,
  type WatcherProtocolParameterRuntimeAuthority,
} from "./funding/prover-funding.js";
export {
  assertWatcherProverFundingAuthorityFactory,
  createWatcherProverFundingAuthority,
  createWatcherProverFundingAuthorityFactory,
  WATCHER_PROVER_FUNDING_AUTHORITY,
  type WatcherProverFundingAuthority,
  type WatcherProverFundingAuthorityFactory,
} from "./funding/prover-funding-authority.js";
export {
  aggregateWatcherProverFundingSweep,
  assertWatcherProverFundingCalculation,
  assertWatcherProverFundingSweep,
  assertWatcherRuntimeProverFundingCalculation,
  calculateWatcherProverFunding,
  calculateWatcherRuntimeProverFunding,
  WATCHER_PROVER_FUNDING_CALCULATION,
  WATCHER_PROVER_FUNDING_SWEEP,
  WATCHER_RUNTIME_PROVER_FUNDING_CALCULATION,
  type WatcherProverFundingActionCalculation,
  type WatcherProverFundingCalculation,
  type WatcherProverFundingSweep,
  type WatcherRuntimeProverFundingCalculation,
} from "./funding/prover-funding-calculation.js";
export {
  assertWatcherProverFundingReservationPlan,
  makeWatcherProverFundingReservationRecord,
  parseWatcherProverFundingReservationRecord,
  planWatcherProverFundingReservation,
  restoreWatcherProverFundingReservationPlan,
  WATCHER_PROVER_FUNDING_RESERVATION_PLAN,
  type WatcherProverFundingReservationInput,
  type WatcherProverFundingReservationPlan,
  type WatcherProverFundingReservationRecord,
  type WatcherProverFundingReservationStore,
  type WatcherProverFundingReservationTransition,
} from "./funding/prover-funding-reservation.js";
export {
  isWatcherProverFundingReservationConflict,
  openWatcherSqliteProverFundingReservationStore,
  WATCHER_SQLITE_PROVER_FUNDING_RESERVATION_STORE,
  type WatcherProverFundingReservationConflict,
  type WatcherSqliteProverFundingReservationStoreRuntime,
} from "./funding/sqlite-prover-funding-reservation-store.js";
export {
  assertWatcherWorkflowFundingProfileOverlay,
  createWatcherWorkflowFundingProfileBundle,
  loadWatcherWorkflowFundingProfileOverlay,
  WATCHER_WORKFLOW_FUNDING_CONFIGURATION,
  WATCHER_WORKFLOW_FUNDING_PROFILE_BUNDLE,
  WATCHER_WORKFLOW_FUNDING_PROFILE_OVERLAY,
  type WatcherWorkflowFundingProfileBody,
  type WatcherWorkflowFundingProfileBundle,
  type WatcherWorkflowFundingProfileOverlay,
  workflowFundingProfileFromOverlay,
} from "./funding/workflow-funding-profile-overlay.js";
export {
  deriveWatcherAttestationTimeoutObservation,
  type WatcherAttestationTimeoutObservation,
} from "./indexers/attestation-timeout-observation.js";
export {
  assertWatcherStateQueueObservation,
  type WatcherAuthenticatedStateQueueObservation,
  type WatcherCorrectionLockObservation,
  type WatcherStateQueueHeaderObservation,
} from "./indexers/authenticated-state-queue-observation.js";
export {
  makeWatcherStateQueueHeader,
  makeWatcherStateQueueSnapshot,
  parseWatcherStateQueueHeader,
  parseWatcherStateQueueSnapshot,
  WATCHER_STATE_QUEUE_SNAPSHOT_SCHEMA_VERSION,
  type WatcherConfirmedState,
  type WatcherIndexedActiveOperator,
  type WatcherIndexedRetiredOperator,
  type WatcherIndexedScheduler,
  type WatcherStateQueueHeader,
  type WatcherStateQueueSnapshot,
} from "./indexers/state-queue-snapshot.js";
export {
  admitWatcherNativeRollForwardBlock,
  WATCHER_NATIVE_BLOCK_ADMISSION_SCHEMA_VERSION,
  type WatcherNativeBlockAdmission,
} from "./l1/native-block-admission.js";
export {
  deriveWatcherNativeGenesisIdentity,
  parseWatcherNativeChainSyncEvent,
  type WatcherNativeNodeConfig,
} from "./l1/native-chain-sync.derive-watcher-native-genesis-identity.js";
export * as watcherNativeGenesisIdentity from "./l1/native-chain-sync.derive-watcher-native-genesis-identity.js";
export {
  readWatcherNativeChainSyncEventReceipt,
  WATCHER_NATIVE_CHAIN_SYNC_SCHEMA_VERSION,
  type WatcherNativeChainSyncAuthority,
  type WatcherNativeChainSyncAuthorityDetails,
  watcherNativeChainSyncAuthorityDetails,
  type WatcherNativeChainSyncEvent,
  type WatcherNativeChainSyncEventReceipt,
  watcherNativeChainSyncEventReceipt,
  type WatcherNativeChainSyncPoint,
  type WatcherNativeChainSyncRollBackward,
  type WatcherNativeChainSyncRollForward,
  type WatcherNativeChainSyncRuntime,
} from "./l1/native-chain-sync.exact-record.js";
export * as watcherNativeChainSyncRecord from "./l1/native-chain-sync.exact-record.js";
export {
  queryWatcherNativeRewardAccount,
  WatcherLocalKupmios,
  type WatcherNativeRewardAccountQuery,
} from "./l1/native-reward-account.js";
export { isWatcherNativeNodeUnavailable } from "./l1/transient-failure.js";
export { retryWatcherL1Transient } from "./l1/transient-retry.js";
export {
  openWatcherDeploymentFollower,
  type WatcherDeploymentFollower,
  watcherFollowedScripts,
} from "./l1-follower/deployment-follower.js";
export {
  parseWatcherConfig,
  parseWatcherConfigJson,
  parseWatcherStrictJsonValue,
  WATCHER_CARDANO_SECURITY_PARAMETER_K,
  WATCHER_CONFIG_BOUNDS,
  WATCHER_CONFIG_SCHEMA_VERSION,
  type WatcherConfig,
  type WatcherConfigDiagnostic,
  watcherConfigDiagnostic,
  WatcherConfigError,
  type WatcherConfigErrorCode,
  type WatcherConfigMode,
  type WatcherDaPeerConfig,
  type WatcherL1Config,
  type WatcherL1SourceConfig,
  type WatcherRollbackAuthorityKeySource,
  type WatcherTargetNetwork,
  type WatcherWalletKeySource,
} from "./runtime/config.js";
export {
  assertWatcherVerifiedDeploymentAuthority,
  loadWatcherVerifiedDeploymentAuthority,
  type VerifiedWatcherDeploymentAuthority,
} from "./runtime/deployment-authority.js";
export {
  assertWatcherDeploymentProtocolParameterAuthority,
  assertWatcherDeploymentProtocolScriptAuthority,
  makeWatcherDeploymentIdentitySignaturePayload,
  type VerifiedWatcherDeploymentIdentity,
  verifyWatcherDeploymentIdentity,
  WATCHER_DEPLOYMENT_IDENTITY_SIGNATURE_DOMAIN,
  WATCHER_DEPLOYMENT_PROTOCOL_SCRIPT_AUTHORITY_SCHEMA_VERSION,
  WATCHER_DEPLOYMENT_RELEASE_BINDINGS_SCHEMA_VERSION,
  WATCHER_SIGNED_DEPLOYMENT_IDENTITY_SCHEMA_VERSION,
  watcherDeploymentAppliedScriptHashes,
  type WatcherDeploymentIdentityDiagnostic,
  watcherDeploymentIdentityDiagnostic,
  WatcherDeploymentIdentityError,
  type WatcherDeploymentIdentityErrorCode,
  type WatcherDeploymentIdentityPolicy,
  type WatcherDeploymentProtocolParameterAuthority,
  watcherDeploymentProtocolParameterAuthority,
  type WatcherDeploymentProtocolScriptAuthority,
  watcherDeploymentProtocolScriptAuthority,
  watcherDeploymentReleaseEconomicsAuthority,
  watcherDeploymentReleaseFinalityAuthority,
  watcherDeploymentReleaseFinalityPolicy,
  type WatcherDeploymentTrustRoot,
  type WatcherFraudProofCatalogueIdentity,
  type WatcherReferenceScriptIdentity,
} from "./runtime/deployment-identity.js";
export {
  authorWatcherDeploymentRelease,
  type WatcherDeploymentReleasePaths,
  type WatcherDeploymentReleaseWriter,
  type WatcherExistingAuthorityPolicy,
} from "./runtime/deployment-release-authoring.js";
export {
  startWatcherOperationsHttpServer,
  WATCHER_OPERATIONS_HTTP,
  type WatcherOperationsHttpServer,
} from "./runtime/operations-http.js";
export {
  createWatcherOperationsObservability,
  WATCHER_ALERT_CODES,
  WATCHER_INFORMATIONAL_ALERT_CODES,
  WATCHER_OPERATIONS_OBSERVABILITY,
  WATCHER_PROOF_STAGE_KINDS,
  type WatcherAlertCode,
  type WatcherAlertDiagnostic,
  type WatcherDaFetchDiagnostic,
  type WatcherEventDiagnostic,
  type WatcherL1SourceDiagnostic,
  type WatcherOperationsApi,
  type WatcherOperationsDaBondPool,
  type WatcherOperationsDaBondPoolReadFailure,
  type WatcherOperationsDiagnostic,
  type WatcherOperationsDiagnosticKind,
  type WatcherOperationsMetrics,
  type WatcherOperationsObservability,
  type WatcherOperationsPage,
  type WatcherOperationsSink,
  type WatcherOperationsStatus,
  type WatcherProofStageKind,
  type WatcherProofStepDiagnostic,
  type WatcherVerificationDiagnostic,
} from "./runtime/operations-observability.js";
export {
  decodeWatcherAuthenticationKey32,
  loadWatcherProcessConfigFile,
  loadWatcherSecretText,
  parseWatcherProcessConfig,
  WATCHER_PROCESS_CONFIG_SCHEMA_VERSION,
  type WatcherProcessConfig,
  watcherSecretSourceIdentity,
} from "./runtime/process-config.js";
export {
  runWatcherCommand,
  unsafeRunWatcherCommandForTest,
  WATCHER_COMMAND_FAILURE_EXIT_CODE,
  WATCHER_PACKAGE_NAME,
  type WatcherCommand,
  type WatcherCommandIo,
} from "./runtime/scaffold.js";
export {
  createWatcherDecisionDriver,
  createWatcherRuntime,
  mintWatcherProverFundingReservationPermit,
  WATCHER_DECISION_PASS_FAILED,
  WATCHER_RELEASE_OBSERVATION_PENDING,
  WATCHER_RUNTIME_SCHEMA_VERSION,
  type WatcherDecisionDriver,
  type WatcherDecisionReadiness,
  type WatcherProverFundingUtxoProvider,
  type WatcherRuntime,
} from "./runtime/watcher-runtime.js";
export {
  makeWatcherDurablePayload,
  watcherCanonicalJson,
  type WatcherDaProofInput,
  type WatcherDurablePayload,
  WatcherDurableStoreError,
  type WatcherDurableStoreErrorCode,
  type WatcherReconstructedState,
} from "./storage/durable-store.js";
export {
  WATCHER_PUBLIC_DA_CLIENT_SCHEMA_VERSION,
  type WatcherPublicDaAttempt,
  type WatcherPublicDaAttemptStatus,
  type WatcherPublicDaEventToStep,
  type WatcherPublicDaLibp2pTransportV1,
  type WatcherPublicDaPayload,
  type WatcherPublicDaProofBundle,
  type WatcherPublicDaRequest,
  type WatcherPublicDaTraceStep,
} from "./storage/public-da-client.js";
export {
  createWatcherPublicDaLibp2pTransport,
  encodeWatcherPublicDaFrame,
  readWatcherPublicDaFrames,
  type WatcherPublicDaLibp2pFactory,
  WatcherPublicDaLibp2pTransport,
  type WatcherPublicDaLibp2pTransportOptions,
} from "./storage/public-da-libp2p-transport.js";
export {
  createWatcherRetainedDaRuntime,
  createWatcherRetainedDaRuntimeOwner,
  createWatcherWorkflowRuntimeLoader,
  WATCHER_RETAINED_DA_RUNTIME,
  type WatcherRetainedDaRuntime,
  type WatcherRetainedDaRuntimeOptions,
  type WatcherRetainedDaRuntimeOwner,
  type WatcherRetainedDaTransportStatus,
  type WatcherWorkflowInfrastructure,
  type WatcherWorkflowInfrastructureBuilder,
} from "./storage/retained-da-runtime.js";
export {
  openWatcherSqliteDurableBackend,
  WATCHER_SQLITE_DURABLE_BACKEND_SCHEMA_VERSION,
  type WatcherSqliteDurableBackend,
} from "./storage/sqlite-durable-backend.js";
export {
  assertWatcherAuthenticatedReplayTranscript,
  createWatcherAuthenticatedReplayTranscript,
  replayWatcherAuthenticatedReplayTranscript,
  WATCHER_AUTHENTICATED_REPLAY_TRANSCRIPT,
  type WatcherAuthenticatedReplayTranscript,
  watcherAuthenticatedReplayTranscriptCborHex,
  type WatcherReplayCoordinate,
  watcherReplayRawRecordCborHex,
} from "./verification/authenticated-replay-transcript.js";
export {
  assertWatcherFullBlockReplayResult,
  evaluateWatcherBlockReplay,
  evaluateWatcherBlockReplayCandidates,
  type EvaluateWatcherBlockReplayCandidatesInput,
  type EvaluateWatcherBlockReplayInput,
  makeWatcherBlockReplayReconstructedState,
  makeWatcherPhaseBConfig,
  WATCHER_BLOCK_REPLAY_BUCKET_CONCURRENCY,
  WATCHER_BLOCK_REPLAY_CANONICAL_PHASES,
  WATCHER_BLOCK_REPLAY_CANONICAL_REJECT_CODES,
  WATCHER_BLOCK_REPLAY_CLAIMED_REJECT_CODES,
  WATCHER_BLOCK_REPLAY_DEPENDENCY_REJECT_CODES,
  WATCHER_BLOCK_REPLAY_DOMINATED_REJECT_CODE_JUSTIFICATIONS,
  WATCHER_BLOCK_REPLAY_DOMINATED_REJECT_CODES,
  WATCHER_BLOCK_REPLAY_DOWNSTREAM_PREREQUISITE_SCHEMA_VERSION,
  WATCHER_BLOCK_REPLAY_EVIDENCED_REJECT_CODES,
  WATCHER_BLOCK_REPLAY_PHASE_A_OWNED_JUSTIFICATION,
  WATCHER_BLOCK_REPLAY_PHASE_A_OWNED_REJECT_CODES,
  WATCHER_BLOCK_REPLAY_PROTOCOL_MINUS_UNCLAIMED,
  WATCHER_BLOCK_REPLAY_REACHABLE_REJECT_CODES,
  WATCHER_BLOCK_REPLAY_REASON_CODES,
  WATCHER_BLOCK_REPLAY_REFERENCE_DETAIL_PREFIXES,
  WATCHER_BLOCK_REPLAY_SCHEMA_VERSION,
  WATCHER_BLOCK_REPLAY_STAGE_BY_CONSENSUS_PHASE,
  WATCHER_BLOCK_REPLAY_STAGES,
  WATCHER_BLOCK_REPLAY_UNCLAIMED_REJECT_CODE_JUSTIFICATIONS,
  WATCHER_BLOCK_REPLAY_UNCLAIMED_REJECT_CODES,
  WATCHER_BLOCK_REPLAY_VERIFIED_CONTRACT,
  type WatcherBlockReplayAction,
  type WatcherBlockReplayCommittedStep,
  watcherBlockReplayCommittedSteps,
  type WatcherBlockReplayDownstreamPrerequisite,
  WatcherBlockReplayError,
  type WatcherBlockReplayEventAuthority,
  type WatcherBlockReplayEventRoot,
  type WatcherBlockReplayForcedValidationFact,
  type WatcherBlockReplayIntermediateRoot,
  watcherBlockReplayPriorState,
  type WatcherBlockReplayPriorUtxo,
  type WatcherBlockReplayReasonCode,
  WatcherBlockReplayRecordError,
  type WatcherBlockReplayRecordErrorCode,
  type WatcherBlockReplayRejection,
  watcherBlockReplayRejectionProjection,
  type WatcherBlockReplayResult,
  type WatcherBlockReplayStage,
  watcherBlockReplayStageForRejection,
  type WatcherBlockReplayStageMismatch,
  type WatcherBlockReplayTransactionRoot,
} from "./verification/block-replay.js";
export {
  evaluateWatcherHeaderRootReconstruction,
  type EvaluateWatcherHeaderRootReconstructionInput,
  makeWatcherAuthenticatedHeaderObservation,
  makeWatcherHeaderRootReconstructedState,
  WATCHER_HEADER_COUNT_FIELDS,
  WATCHER_HEADER_ROOT_FIELDS,
  WATCHER_HEADER_ROOT_RECONSTRUCTION_REASON_CODES,
  WATCHER_HEADER_ROOT_RECONSTRUCTION_SCHEMA_VERSION,
  type WatcherHeaderCountField,
  type WatcherHeaderCountSet,
  type WatcherHeaderRootField,
  WatcherHeaderRootReconstructionError,
  type WatcherHeaderRootReconstructionErrorCode,
  type WatcherHeaderRootReconstructionReasonCode,
  type WatcherHeaderRootReconstructionResult,
  type WatcherHeaderRootSet,
} from "./verification/header-root-reconstruction.js";
export {
  detectAndJournalMissingSignatureFindings,
  detectMissingSignatureFinding,
  recoverMissingSignatureVkey,
  WATCHER_MISSING_SIGNATURE_DETECTION_DEFAULTS,
  WATCHER_MISSING_SIGNATURE_DETECTOR_SCHEMA_VERSION,
  type WatcherMissingSignatureCandidate,
  type WatcherMissingSignatureDetection,
  type WatcherMissingSignatureDetectionConfig,
  type WatcherMissingSignatureVkeySources,
} from "./verification/missing-signature-detector.js";
export {
  evaluateWatcherPhaseABlock,
  type EvaluateWatcherPhaseABlockInput,
  evaluateWatcherPhaseAQueuedTxs,
  makeWatcherPhaseAConfig,
  WATCHER_PHASE_A_CANONICAL_REJECT_CODES,
  WATCHER_PHASE_A_CONCURRENCY,
  WATCHER_PHASE_A_CONSENSUS_REJECT_CODES,
  WATCHER_PHASE_A_CREATED_AT,
  WATCHER_PHASE_A_DIRECT_REJECT_CODES,
  WATCHER_PHASE_A_DOMINATED_REJECT_CODE_JUSTIFICATIONS,
  WATCHER_PHASE_A_DOMINATED_REJECT_CODES,
  WATCHER_PHASE_A_EVIDENCED_REJECT_CODES,
  WATCHER_PHASE_A_EXCLUDED_REJECT_CODE_JUSTIFICATIONS,
  WATCHER_PHASE_A_EXCLUDED_REJECT_CODES,
  WATCHER_PHASE_A_REACHABLE_REJECT_CODES,
  WATCHER_PHASE_A_VERIFIER_REASON_CODES,
  WATCHER_PHASE_A_VERIFIER_SCHEMA_VERSION,
  type WatcherPhaseABlockContext,
  type WatcherPhaseABlockTransaction,
  watcherPhaseAQueuedTxs,
  type WatcherPhaseARejection,
  watcherPhaseARejectionProjection,
  type WatcherPhaseAVerificationResult,
  WatcherPhaseAVerifierError,
  type WatcherPhaseAVerifierReasonCode,
} from "./verification/phase-a-verifier.js";
export {
  computeWatcherRuleBundleCommitment,
  encodeWatcherRuleBundle,
  type LoadedWatcherRuleBundle,
  loadWatcherRuleBundle,
  makeWatcherCanonicalRuleBundle,
  parseWatcherRuleBundle,
  WATCHER_RULE_BUNDLE_REJECTION_SELECTION,
  WATCHER_RULE_BUNDLE_SCHEMA_VERSION,
  WATCHER_RULE_BUNDLE_TRANSITION_PRIORITY,
  WATCHER_RULE_BUNDLE_VALIDATION_PHASE_PRIORITY,
  WATCHER_RULE_BUNDLE_VERSION,
  type WatcherRuleBundle,
  type WatcherRuleBundleConstructionIdentity,
  WatcherRuleBundleError,
  type WatcherRuleBundleErrorCode,
  type WatcherRuleBundleFeature,
  type WatcherRuleBundleTargetParameters,
} from "./verification/rule-bundle.js";
