// Renders docs/agents/required-checks.md from the registry, so the table a
// contributor reads is the table preflight runs. `node scripts/preflight.mjs
// --write-docs` writes it; `--check-docs` (and its test) fails when the
// committed file differs.

import { FULL_RUN, FULL_RUN_ENV } from "./registry.mjs";

export const REQUIRED_CHECKS_DOC = "docs/agents/required-checks.md";
export const MISSES_LOG = "scripts/preflight/misses.jsonl";

const code = (text) => `\`${text}\``;

const describeCheck = (check) => {
  const lines = [`### ${code(check.id)}`, "", `${check.title}.`, ""];
  lines.push(`- Command: ${code(check.display)}`);
  if (check.fix !== undefined) {
    lines.push(`- Fix: ${code(check.fix)}`);
  }
  if (check.always) {
    lines.push("- Runs on: every change");
  } else if (check.triggerNote !== undefined) {
    lines.push(`- Runs on: ${check.triggerNote}`);
  } else {
    lines.push("- Runs on:");
    for (const trigger of check.triggers) {
      lines.push(`  - ${code(trigger)}`);
    }
  }
  if (check.capabilities.length > 0) {
    lines.push(`- Needs: ${check.capabilities.map(code).join(", ")}`);
  }
  const flags = [
    ...(check.prePush ? ["runs in the pre-push hook"] : []),
    ...(check.warnOnly ? [`warns only (${check.warnReason})`] : []),
  ];
  if (flags.length > 0) {
    lines.push(`- Mode: ${flags.join("; ")}`);
  }
  return lines.join("\n");
};

export const renderRequiredChecks = (registry) =>
  `${[
    "# Required Checks",
    "",
    "<!-- Generated by `node scripts/preflight.mjs --write-docs` from",
    "scripts/preflight/registry.mjs. Do not edit by hand. -->",
    "",
    "The checks a change must pass before it is pushed, and the command that",
    "runs exactly the ones your change needs:",
    "",
    "```sh",
    "node scripts/preflight.mjs            # working tree against the base",
    "node scripts/preflight.mjs --list     # what would run, without running it",
    "node scripts/preflight.mjs --strict   # committed changes only (what a push sends)",
    "node scripts/preflight.mjs --json     # machine-readable verdict on stdout",
    "node scripts/doctor.mjs               # environment problems, each with its fix",
    "```",
    "",
    "The base is `--base <ref>`, else the branch's upstream, else",
    "`origin/colll78/canonical-v1-watcher-l1-source-checkpoint`.",
    "",
    "## Selection is never the final gate",
    "",
    "- CI runs every check on every pull request before merge. Preflight exists",
    "  to catch a red build before the push, not to decide what CI may skip.",
    "- Selection favours recall over precision. When in doubt, add a trigger or a",
    "  full-run entry.",
    `- A change to any full-run path below, a moved Aiken compiler pin, ${code("--full")},`,
    `  or ${code(`${FULL_RUN_ENV}=1`)} selects every check at full scope.`,
    "- A check whose capability is missing is skipped with a reason and the run",
    "  exits 3. Could not look is never passed.",
    "- When CI catches a failure that preflight selection missed, append a line",
    "  to the misses log (below) and widen the trigger that missed it.",
    "",
    "## Exit codes",
    "",
    "- `0`: every selected check passed (warnings do not block).",
    "- `1`: a check failed.",
    "- `2`: usage error, or the change set could not be computed.",
    "- `3`: nothing failed, but a check was skipped because a capability it",
    "  needs is missing or could not be checked.",
    "",
    "Statuses in `--json` (`checks[]`): `passed`, `failed`, `skipped`, `warned`.",
    "",
    "## Pre-push hook",
    "",
    "`.githooks/pre-push` runs `node scripts/preflight.mjs --pre-push`: the",
    "committed diff, restricted to the checks marked below as running in the",
    "pre-push hook. It blocks the push only on a failed check. Skip it once with",
    "`MIDGARD_SKIP_PREFLIGHT=1 git push`.",
    "",
    "## Full-run paths",
    "",
    ...FULL_RUN.map((glob) => `- ${code(glob)}`),
    "",
    "## Capabilities",
    "",
    "- `aiken`: the pinned Aiken fork (`AIKEN_FORK_VERSION` in the workflows), on",
    "  `PATH` or in `MIDGARD_AIKEN_BIN`.",
    "- `node-modules`: `pnpm --dir demo install --frozen-lockfile` has run.",
    "- `core-dist`: `demo/midgard-core/dist` matches its sources",
    "  (`demo/scripts/assert-midgard-core-dist-current.mjs`).",
    "- `blueprint`: the blueprint stamp is fresh",
    "  (`demo/scripts/lib/blueprint-stamp.mjs`).",
    "- `postgres`: the test server answers on `127.0.0.1:5433`",
    "  (`bash scripts/start-test-postgres.sh`). Preflight never uses port 55433.",
    "- `db-prefix`: this checkout has its own test-database prefix",
    "  (`MIDGARD_TEST_DATABASE_PREFIX`, or derived from the worktree path).",
    "- `git-merge-tree`: git 2.38 or later.",
    "",
    "## Checks",
    "",
    registry.checks.map(describeCheck).join("\n\n"),
    "",
    "## Misses log",
    "",
    `When CI fails on something preflight did not select, append one JSON object`,
    `per line to ${code(MISSES_LOG)} (create it on the first miss; never rewrite`,
    "earlier lines):",
    "",
    "```text",
    '{"date":"2026-09-25","ciRun":"<url>","commit":"<sha>","ciCheck":"<workflow / step>","changedPaths":["<path>"],"preflightRan":["<check id>"],"why":"<why selection missed it>","remedy":"<trigger or full-run change, and the commit that made it>"}',
    "```",
    "",
  ].join("\n")}`;
