// Renders docs/agents/required-checks.md from the registry, so the table a
// contributor reads is the table preflight runs. `node scripts/preflight.mjs
// --write-docs` writes it; `--check-docs` (and its test) fails when the
// committed file differs.

import { FULL_RUN, FULL_RUN_ENV, VERIFICATION_ONLY } from "./registry.mjs";
import { RUNTIME_CHECKS } from "./runtime-owner.mjs";

export const REQUIRED_CHECKS_DOC = "docs/agents/required-checks.md";
export const MISSES_LOG = "scripts/preflight/misses.jsonl";

const code = (text) => `\`${text}\``;

const describeCheck = (check) => {
  const lines = [`### ${code(check.id)}`, "", `${check.title}.`, ""];
  lines.push(`- Command: ${code(check.display)}`);
  if (check.fix !== undefined) {
    lines.push(`- Fix: ${code(check.fix)}`);
  }
  if (check.always) {
    lines.push("- Runs on: every change");
  } else if (check.triggerNote !== undefined) {
    lines.push(`- Runs on: ${check.triggerNote}`);
  } else {
    lines.push("- Runs on:");
    for (const trigger of check.triggers) {
      lines.push(`  - ${code(trigger)}`);
    }
  }
  if (check.capabilities.length > 0) {
    lines.push(`- Needs: ${check.capabilities.map(code).join(", ")}`);
  }
  const flags = [
    ...(RUNTIME_CHECKS.includes(check.id)
      ? ["Node CI owns the ordinary PR matrix; --full-local runs it locally"]
      : []),
    ...(check.prePush ? ["runs in the pre-push hook"] : []),
    ...(check.warnOnly ? [`warns only (${check.warnReason})`] : []),
  ];
  if (flags.length > 0) {
    lines.push(`- Mode: ${flags.join("; ")}`);
  }
  return lines.join("\n");
};

export const renderRequiredChecks = (registry) =>
  `${[
    "# Required Checks",
    "",
    "<!-- Generated by `node scripts/preflight.mjs --write-docs` from",
    "scripts/preflight/registry.mjs. Do not edit by hand. -->",
    "",
    "Required obligations and their execution owners. The ordinary PR command",
    "runs local checks and lists covered runtime work as pending in Node CI:",
    "",
    "```sh",
    "node scripts/preflight.mjs            # working tree against the base",
    "node scripts/preflight.mjs --list     # what would run, without running it",
    "node scripts/preflight.mjs --strict   # committed changes only (what a push sends)",
    "node scripts/preflight.mjs --full-local # selected matrix locally: the gate before a merge",
    "node scripts/preflight.mjs --full     # every check locally at full scope",
    "node scripts/preflight.mjs --json     # machine-readable verdict on stdout",
    "node scripts/preflight.mjs --run <id> # one check by id at full scope (what CI runs)",
    "node scripts/doctor.mjs               # environment problems, each with its fix",
    "```",
    "",
    "The base is `--base <target-ref>`, otherwise",
    "`origin/colll78/canonical-v1-watcher-l1-source-checkpoint`.",
    "Fetch origin first. Missing targets and old target ancestors are refused.",
    "A clean merge is selected by its changes relative to the target, excluding",
    "equivalent already-landed work. Conflicts retain conservative selection.",
    "",
    "## Selection is never the final gate",
    "",
    "- CI's declared path filters determine the required hosted jobs. Preflight",
    "  cannot waive those jobs or distinct integration/acceptance checks.",
    "- Selection favours recall over precision. When in doubt, add a trigger or a",
    "  full-run entry.",
    `- A shared full-run path below (except the listed verification-only modules), a moved Aiken compiler pin, ${code("--full")},`,
    `  or ${code(`${FULL_RUN_ENV}=1`)} selects every check at full scope. Explicit --full`,
    "  and the environment switch also choose local runtime ownership.",
    "- A check whose capability is missing is skipped with a reason and the run",
    "  exits 3. Could not look is never passed.",
    "- When CI catches a failure that preflight selection missed, append a line",
    "  to the misses log (below) and widen the trigger that missed it.",
    "",
    "## Exit codes",
    "",
    "- `0`: every selected check passed (warnings do not block).",
    "- `1`: a check failed.",
    "- `2`: usage error, or the change set could not be computed.",
    "- `3`: nothing failed, but a check was skipped because a capability it",
    "  needs is missing or could not be checked.",
    "",
    "Statuses in `--json` (`checks[]`): `passed`, `failed`, `skipped`, `warned`.",
    "`hosted[]` lists pending CI obligations separately; it contains no verdicts.",
    "Exit 0 reports only completed local checks, not PR readiness.",
    "",
    "## Runtime execution owner",
    "",
    "Node CI owns `demo-build`, `demo-typecheck`, `demo-test` and `demo-test-db`,",
    "plus `tx-preparation:sdk` while its recipe is exactly the full Lucid + SDK",
    "suites hosted CI already runs. Node/emulator preparation remain separate.",
    "when the PR paths match its actual workflow and its success-only aggregate",
    "gate covers every job. Unknown routing or missing YAML capability retains",
    "local execution. `--full-local` restores the selected local matrix; it does",
    "not widen selection. Automatic full-scope inputs keep ordinary PR ownership.",
    "Focused local causal regressions, the fast hook and distinct acceptance",
    "lanes remain mandatory. Prepare fresh local prerequisites for the checks",
    "you run: hosted scheduling supplies no dist, native binary or blueprint.",
    "Read the [merge checklist](verification.md#merge-checklist) before merging:",
    "workflow census, exact head, successful conclusions and reviews remain required.",
    "",
    "## Gate before a merge",
    "",
    "Gate a lane before merging it with `node scripts/preflight.mjs --full-local",
    "--base <target-ref>`, not a hand-written list of commands: it runs every",
    "check the change selects, each from the command CI runs, the package suites",
    "included. Those run as `node scripts/contrib.mjs test --package <name>",
    "--related <changed paths>` for each package the change can reach: only the",
    "tests the change reaches, widening to the whole package wherever the reach",
    "is unsure (see [focused tests and builds](contrib/tests-and-builds.md)). A",
    "full run (`--full`, a full-run path) runs every whole suite instead. Tests a",
    "suite skips by its own conditions pass, as under CI. Node CI still runs the",
    "whole suites; the local gate never waives them.",
    "",
    "## CI runs checks by id",
    "",
    "A workflow step that runs a registry check names it:",
    "`node scripts/preflight.mjs --run <id>` (repeatable). It runs that check's",
    "full-scope command from the table below, from the repository root, with the",
    "same capability probes and fail-closed exits; a missing capability exits 3",
    "and fails the step. The command lives only in the registry, so a local run",
    "and CI cannot drift; `scripts/preflight/ci-wiring.test.mjs` refuses a step",
    "that spells out a registry command instead, or names a check that is",
    "unknown, internal or only warns. A check a workflow runs by id counts as",
    "gated by CI. `--run` combines only with `--list`.",
    "",
    "A workflow that runs a check by id lists every module of the runner in its",
    "path filters, so a runner change re-runs those steps:",
    "`scripts/ci/preflight-runner-closure.mjs` derives the list from the import",
    "closure and the probe modules, and",
    "`scripts/ci/preflight-runner-filters.test.mjs` fails on a missing one.",
    "",
    "## Pre-push hook",
    "",
    "`.githooks/pre-push` runs `node scripts/preflight.mjs --pre-push`: the",
    "committed diff, restricted to the checks marked below as running in the",
    "pre-push hook. It blocks the push only on a failed check. Skip it once with",
    "`MIDGARD_SKIP_PREFLIGHT=1 git push`.",
    "",
    "## Full-run paths",
    "",
    ...FULL_RUN.map((glob) => `- ${code(glob)}`),
    "",
    "### Verification-only exceptions",
    "",
    "These modules serve preflight only. They select tooling self-tests instead",
    "of repeating unchanged protocol suites; Repo Tools CI remains required.",
    "Shared probes, artifact derivation, package execution and unknown new",
    "preflight helpers retain full scope. `--full` still runs every check locally.",
    ...VERIFICATION_ONLY.map((glob) => `- ${code(glob)}`),
    "",
    "## Verified CI reuse",
    "",
    "`node scripts/preflight.mjs --strict --ci-run <Repo-Tools-run-id>` can reuse",
    "only `required-checks-doc` and `contributor-build-guards`. It verifies the",
    "actual checkout tree and merge parents, current remote target, Node profile,",
    "steps that run each validator by id (`--run`, so the registry command) and",
    "their successful completion against the retained",
    "`repo-validator-identity` artifact. Dirty, stale, missing or different",
    "evidence fails closed. Other selected checks still execute. `--list` never",
    "verifies or claims reuse. Read the [merge checklist](verification.md#merge-checklist)",
    "before treating hosted evidence as acceptance.",
    "",
    "## Same-run SDK suite reuse",
    "",
    "The SDK transaction-preparation obligation follows the full workspace suites.",
    "Only completed full Lucid and SDK package scripts from this invocation can",
    "satisfy it: structured reports must cover every test file, with no failed,",
    "skipped, todo or setup-refused cases. Source, installed dependency bytes/link",
    "routing, compiled outputs, blueprint/stamp and runtime/environment must match",
    "before/after both suites and at reuse. Planned tests are never evidence.",
    "Absent or different evidence leaves the standalone `test:tx-prep:sdk` command",
    "required; failures remain failures. Node/Tools/emulator lanes and cross-run",
    "CI reuse retain their existing gates. No SDK evidence survives this run.",
    "",
    "## Capabilities",
    "",
    "- `aiken`: the pinned Aiken fork (`AIKEN_FORK_VERSION` in the workflows), on",
    "  `PATH` or in `MIDGARD_AIKEN_BIN`.",
    "- `node-modules`: `pnpm --dir demo install --frozen-lockfile` has run.",
    "- `docs-site-node-modules`: `pnpm --dir docs-site install --frozen-lockfile`",
    "  has run; this is separate from the demo workspace's dependencies.",
    "- `nix`: `nix --version` succeeds. The spec build also needs flakes enabled",
    "  and access to the dependencies declared in `technical-spec/flake.nix`.",
    "- `core-dist`: `demo/midgard-core/dist` matches its sources",
    "  (`demo/scripts/assert-midgard-core-dist-current.mjs`).",
    "- `blueprint`: the blueprint stamp is fresh",
    "  (`demo/scripts/lib/blueprint-stamp.mjs`).",
    "- `postgres`: the test server answers on `127.0.0.1:5433`",
    "  (`bash scripts/start-test-postgres.sh`). Preflight never uses port 55433.",
    "- `db-prefix`: this checkout has its own test-database prefix",
    "  (`MIDGARD_TEST_DATABASE_PREFIX`, or derived from the worktree path).",
    "- `git-merge-tree`: git 2.38 or later.",
    "",
    "## Checks",
    "",
    registry.checks.map(describeCheck).join("\n\n"),
    "",
    "## Misses log",
    "",
    `When CI fails on something preflight did not select, append one JSON object`,
    `per line to ${code(MISSES_LOG)} (create it on the first miss; never rewrite`,
    "earlier lines): <!-- doc-links:future -->",
    "",
    "```text",
    '{"date":"2026-09-25","ciRun":"<url>","commit":"<sha>","ciCheck":"<workflow / step>","changedPaths":["<path>"],"preflightRan":["<check id>"],"why":"<why selection missed it>","remedy":"<trigger or full-run change, and the commit that made it>"}',
    "```",
    "",
  ].join("\n")}`;
