// Public entrypoint; implementation is grouped by responsibility below.
export {
  acceptWatcherLocalUserEventAnchor,
  acceptWatcherLocalUserEventPublication,
  acceptWatcherLocalUserEventReadmission,
  admitWatcherLocalUserEventAuthority,
  advanceWatcherLocalUserEventCoverage,
  assertWatcherLocalUserEventAuthorityCurrent,
  assertWatcherLocalUserEventHeadCurrent,
  assertWatcherLocalUserEventPointCovered,
  closeWatcherLocalUserEventHistory,
  closeWatcherLocalUserEventReadmission,
  createWatcherLocalUserEventHistory,
  isWatcherLocalUserEventAuthorityUnavailable,
  prepareWatcherLocalUserEventAnchor,
  prepareWatcherLocalUserEventCanonicalReplay,
  prepareWatcherLocalUserEventReadmission,
  prepareWatcherLocalUserEventTransition,
  readWatcherLocalUserEventAnchor,
  readWatcherLocalUserEventAuthority,
  readWatcherLocalUserEventCoverage,
  readWatcherLocalUserEventHistory,
  readWatcherLocalUserEventReadmission,
  readWatcherLocalUserEventTransition,
  readWatcherLocalUserEventValidation,
  restoreWatcherLocalUserEventCoverage,
  restoreWatcherLocalUserEventHistory,
  resumeWatcherLocalUserEventHistory,
  rewindWatcherLocalUserEventCoverage,
  suspendWatcherLocalUserEventHistory,
  type WatcherLocalUserEventAnchor,
  type WatcherLocalUserEventAuthority,
  type WatcherLocalUserEventAuthorityRead,
  type WatcherLocalUserEventCoverage,
  type WatcherLocalUserEventEntry,
  type WatcherLocalUserEventHeaderCutoff,
  type WatcherLocalUserEventHistory,
  type WatcherLocalUserEventPointCoverage,
  type WatcherLocalUserEventReadmission,
  type WatcherLocalUserEventReplaySource,
  type WatcherLocalUserEventTransition,
} from "./user-event-indexer/local-history.js";
export {
  isWatcherForcedOperatorVerdict,
  makeWatcherUserEventIndexerPolicy,
  parseWatcherUserEventIndexerPolicy,
  WATCHER_FORCED_TX_VALID,
  watcherForcedOperatorVerdict,
} from "./user-event-indexer/policy.js";
export {
  WATCHER_FORCED_TERMINAL_CLASSIFICATION_SCHEMA_VERSION,
  WATCHER_USER_EVENT_INDEXER_BOUNDS,
  WATCHER_USER_EVENT_INDEXER_POLICY_SCHEMA_VERSION,
  WATCHER_USER_EVENT_OBSERVATION_SCHEMA_VERSION,
  WATCHER_USER_EVENT_SNAPSHOT_SCHEMA_VERSION,
  type WatcherForcedOperatorVerdict,
  type WatcherForcedTerminalClassification,
  type WatcherIndexedUserEvent,
  type WatcherTerminalUserEvent,
  type WatcherUserEventDeploymentAuthority,
  type WatcherUserEventFinalityStatus,
  type WatcherUserEventIndexerPolicy,
  type WatcherUserEventKind,
  type WatcherUserEventNetwork,
  type WatcherUserEventObservation,
  type WatcherUserEventSnapshot,
  type WatcherUserEventTerminalStatus,
} from "./user-event-indexer/types.js";
