packages:
  - lucid-midgard
  - midgard-core
  - midgard-fault-proofs
  - midgard-validation
  - midgard-node
  - midgard-node-tools
  - midgard-sdk
  - midgard-watcher
  - da-committee-node
  - midgard-test-support
