import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import {
  chmod,
  mkdtemp,
  readFile,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  encodeCborArrayRaw,
  encodeCborBytes,
  encodeCborMapRaw,
  encodeCborUnsigned,
} from "@al-ft/midgard-core/codec/cbor";
import { computeHash32 } from "@al-ft/midgard-core/codec/hash";
import { DEPLOYMENT_MANIFEST_REFERENCE_SCRIPT_CONTRACT_BY_ROLE } from "@al-ft/midgard-core/deployment-manifest-identity";
import { parseOutRefLabel } from "@al-ft/midgard-core/out-ref";
import { computeFraudProofRawL1PointId } from "@al-ft/midgard-fault-proofs";
import {
  buildDepositValidators,
  buildHubOracleMintingValidator,
  buildTxOrderValidators,
  buildWithdrawalValidators,
  parseFaultProofBlueprint,
} from "@al-ft/midgard-sdk";
import { CML, validatorToScriptHash } from "@lucid-evolution/lucid";
import { vi } from "vitest";

import { createWatcherLocalBackfillUserEventReferenceAuthority } from "../../src/indexers/user-event-reference-authority.js";
import {
  admitWatcherLocalBackfillFinality,
  type WatcherLocalBackfillFinalityReceipt,
} from "../../src/l1/finality-engine.js";
import {
  admitWatcherLocalBackfillObservation,
  type WatcherLocalBackfillObservationReceipt,
} from "../../src/l1/l1-adapter.js";
import { openWatcherLocalHistoricalCapture } from "../../src/l1/local-historical-capture.js";
import { admitWatcherNativeRollForwardBlock } from "../../src/l1/native-block-admission.js";
import { WATCHER_NATIVE_CHAIN_SYNC_SCHEMA_VERSION } from "../../src/l1/native-chain-sync.js";
import { WATCHER_CONFIG_SCHEMA_VERSION } from "../../src/runtime/config.js";
import {
  verifyWatcherUserEventScriptBinding,
  type WatcherUserEventScriptBinding,
} from "../../src/runtime/deployment-identity.js";
import {
  makeWatcherAuthorityContracts,
  makeWatcherDeploymentAuthorityFixture,
} from "../support/deployment-authority-fixture.js";
// Explicitly synthetic local test chain. The initialization and reference frames
// came from a passing ordinary emulator scenario. Header keys/signatures are dummy
// fixture data: this proves native framing/W12/application authority wiring only,
// and makes no consensus validity, public-chain inclusion or historical claim.
const GENESIS_BYTES = JSON.stringify({ networkMagic: 1 });
const GENESIS = createHash("sha256").update(GENESIS_BYTES).digest("hex");
const makeConfig = (
  NODE_CONFIG_PATH: string,
  GENESIS_CONFIG_PATH: string,
  queryEndpoints?: Readonly<{ ogmios: string; kupo: string }>,
) =>
  Object.freeze({
    schemaVersion: WATCHER_CONFIG_SCHEMA_VERSION,
    mode: "acceptance",
    targetNetwork: "Preprod",
    l1: Object.freeze({
      source: Object.freeze({
        sourceMode: "local_node",
        authorityNodeId: "watcher-node",
        chainSync: Object.freeze({
          kind: "cardano_node_socket",
          socketPath: "/run/cardano/node.socket",
          nodeConfigPath: NODE_CONFIG_PATH,
          genesisConfigPath: GENESIS_CONFIG_PATH,
          genesisIdentitySha256: GENESIS,
        }),
        queryServices: Object.freeze([
          Object.freeze({
            kind: "ogmios",
            identity: "local-ogmios",
            endpoint: queryEndpoints?.ogmios ?? "ws://127.0.0.1:1337",
          }),
          Object.freeze({
            kind: "kupo",
            identity: "local-kupo",
            endpoint: queryEndpoints?.kupo ?? "http://127.0.0.1:1442",
          }),
        ]),
      }),
      requestTimeoutMs: 10_000,
      maxConcurrency: 4,
      finality: Object.freeze({
        depth: 30,
        rollback: Object.freeze({
          beforeFinality: "rewind",
          afterFinality: "quarantine",
          maxDepth: 30,
        }),
      }),
    }),
    da: Object.freeze({
      peers: Object.freeze([
        {
          identity: "da-peer-a",
          multiaddr:
            "/dns4/da-a.example/tcp/443/p2p/12D3KooWAbcdefghijkmnopqrstuvwxyz12345",
        },
      ]),
      requestTimeoutMs: 10_000,
      maxConcurrency: 4,
    }),
    storage: Object.freeze({
      driver: "sqlite",
      path: "/var/lib/midgard-watcher/watcher.sqlite",
      rollbackAuthorityKeySource: Object.freeze({
        kind: "environment",
        variable: "MIDGARD_WATCHER_ROLLBACK_AUTHORITY_KEY",
      }),
    }),
    proverWallet: Object.freeze({
      keySource: Object.freeze({
        kind: "environment",
        variable: "MIDGARD_WATCHER_PROVER_KEY",
      }),
    }),
    deadlines: Object.freeze({
      daFetchMs: 60_000,
      daPublishMs: 60_000,
      proofConstructMs: 300_000,
      proofSubmitMs: 120_000,
    }),
  });

// Generated by the real node initialization emulator with
// MIDGARD_WRITE_WATCHER_INITIALIZATION_FIXTURE=1. Regenerate after validator changes.
const INITIALIZATION = JSON.parse(
  readFileSync(
    new URL("../fixtures/user-event-initialization.json", import.meta.url),
    "utf8",
  ),
) as Readonly<{
  canonicalOneShotOutRef: string;
  transactionCbor: string;
  creatingTransactions: readonly Readonly<{ transactionCbor: string }>[];
}>;

const blueprintBytes = readFileSync(
  process.env.MIDGARD_REAL_BLUEPRINT_PATH ??
    fileURLToPath(
      new URL("../../../../onchain/aiken/plutus.json", import.meta.url),
    ),
);
const blueprint = parseFaultProofBlueprint(
  JSON.parse(blueprintBytes.toString("utf8")) as unknown,
);
const makeOriginDeployment = (ruleBundleCommitment?: string) => {
  const contractSet = makeWatcherAuthorityContracts();
  const hub = buildHubOracleMintingValidator({
    blueprint,
    oneShotOutRef: parseOutRefLabel(INITIALIZATION.canonicalOneShotOutRef),
  });
  const input = {
    blueprint,
    network: "Preprod" as const,
    hubOraclePolicyId: hub.policyId,
  };
  const deposit = buildDepositValidators(input);
  const withdrawal = buildWithdrawalValidators(input);
  const { txOrder, fieldPreimageCertificate } = buildTxOrderValidators(input);
  const scripts = {
    hubOracleMint: hub.mintingScript,
    depositMint: deposit.mintingScript,
    depositSpend: deposit.spendingScript,
    withdrawalMint: withdrawal.mintingScript,
    withdrawalSpend: withdrawal.spendingScript,
    txOrderMint: txOrder.mintingScript,
    txOrderSpend: txOrder.spendingScript,
    fieldPreimageCertificateMint: fieldPreimageCertificate.mintingScript,
  };
  for (const [name, script] of Object.entries(scripts)) {
    contractSet.contracts[name] = {
      ...contractSet.contracts[name],
      contract: { type: script.type, cborHex: script.script },
      scriptHash: validatorToScriptHash(script),
    };
  }
  for (const [role, name] of Object.entries(
    DEPLOYMENT_MANIFEST_REFERENCE_SCRIPT_CONTRACT_BY_ROLE,
  )) {
    contractSet.referenceScripts[role] = {
      ...contractSet.referenceScripts[role],
      scriptHash: contractSet.contracts[name].scriptHash,
    };
  }
  return makeWatcherDeploymentAuthorityFixture({
    contractSet,
    blueprintHash: createHash("sha256").update(blueprintBytes).digest("hex"),
    hubOracleOneShotOutRef: INITIALIZATION.canonicalOneShotOutRef,
    ...(ruleBundleCommitment === undefined ? {} : { ruleBundleCommitment }),
  });
};

type Point = Readonly<{
  blockHash: string;
  blockNo: string;
  slot: string;
  pointId: string;
}>;
export type SyntheticUserEventBlock = Readonly<{
  point: Point;
  parentPoint: Point;
  nativeBlock: ReturnType<typeof admitWatcherNativeRollForwardBlock>;
}>;
type Creating = Readonly<{
  txHash: string;
  transactionCbor: string;
  creatingPoint: Point;
  predecessorPoint: Point;
  creatingTransactionIndex: number;
  inputOutRefs: readonly string[];
  outputs: readonly CreatingOutput[];
}>;
type CreatingOutput = Readonly<{
  transaction_index: number;
  transaction_id: string;
  output_index: number;
  address: string;
  value: Readonly<{ coins: string; assets: Readonly<Record<string, string>> }>;
  datum_hash: string | null;
  datum_type?: "hash" | "inline";
  script_hash: string | null;
  created_at: Readonly<{ slot_no: number; header_hash: string }>;
  datum: string | null;
  script: Readonly<{ language: string; script: string }> | null;
}>;
type Consumption = Readonly<{
  transaction_id: string;
  input_index: number;
  slot_no: number;
  header_hash: string;
}>;

// Keep only primitive data after indexing; CML child getters allocate independent
// WASM wrappers, so release every wrapper before leaving this synchronous scope.
const withFixtureCml = <Result>(
  read: (
    own: <T extends { free(): void } | undefined>(value: T) => T,
  ) => Result,
): Result => {
  const allocated: { free(): void }[] = [];
  const own = <T extends { free(): void } | undefined>(value: T): T => {
    if (value !== undefined) allocated.push(value);
    return value;
  };
  try {
    return read(own);
  } finally {
    for (const value of allocated.reverse()) value.free();
  }
};
const pointAt = (blockHash: string, blockNo: bigint, slot: bigint): Point => {
  const point = {
    blockHash,
    blockNo: blockNo.toString(),
    slot: slot.toString(),
  };
  return Object.freeze({
    ...point,
    pointId: computeFraudProofRawL1PointId(point),
  });
};
const buildBlock = (
  transactions: readonly string[],
  parentPoint: Point,
  slotInterval = 1n,
): SyntheticUserEventBlock => {
  const frames = transactions.map((cbor) =>
    CML.Transaction.from_cbor_hex(cbor),
  );
  const bodyParts = [
    encodeCborArrayRaw(frames.map((tx) => tx.body().to_cbor_bytes())),
    encodeCborArrayRaw(frames.map((tx) => tx.witness_set().to_cbor_bytes())),
    encodeCborMapRaw(
      frames.flatMap((tx, index) => {
        const auxiliary = tx.auxiliary_data();
        return auxiliary === undefined
          ? []
          : [
              [
                encodeCborUnsigned(BigInt(index)),
                auxiliary.to_cbor_bytes(),
              ] as const,
            ];
      }),
    ),
    encodeCborArrayRaw(
      frames.flatMap((tx, index) =>
        tx.is_valid() ? [] : [encodeCborUnsigned(BigInt(index))],
      ),
    ),
  ];
  const bodyHash = computeHash32(
    Buffer.concat(bodyParts.map((part) => computeHash32(part))),
  );
  const headerBody = CML.HeaderBody.new(
    BigInt(parentPoint.blockNo) + 1n,
    BigInt(parentPoint.slot) + slotInterval,
    CML.BlockHeaderHash.from_hex(parentPoint.blockHash),
    CML.PublicKey.from_bytes(new Uint8Array(32).fill(1)),
    CML.VRFVkey.from_raw_bytes(new Uint8Array(32).fill(2)),
    CML.VRFCert.new(new Uint8Array(64).fill(3), new Uint8Array(80).fill(4)),
    BigInt(bodyParts.reduce((size, part) => size + part.length, 0)),
    CML.BlockBodyHash.from_raw_bytes(bodyHash),
    CML.OperationalCert.new(
      CML.KESVkey.from_raw_bytes(new Uint8Array(32).fill(5)),
      0n,
      0n,
      CML.Ed25519Signature.from_raw_bytes(new Uint8Array(64).fill(6)),
    ),
    CML.ProtocolVersion.new(9n, 0n),
  );
  const header = CML.Header.new(
    headerBody,
    CML.KESSignature.from_cbor_bytes(
      encodeCborBytes(new Uint8Array(448).fill(7)),
    ),
  );
  const headerBytes = header.to_cbor_bytes();
  const point = pointAt(
    computeHash32(headerBytes).toString("hex"),
    headerBody.block_number(),
    headerBody.slot(),
  );
  const rawBlockCbor = encodeCborArrayRaw([headerBytes, ...bodyParts]).toString(
    "hex",
  );
  const nativeBlock = admitWatcherNativeRollForwardBlock({
    ...point,
    schemaVersion: WATCHER_NATIVE_CHAIN_SYNC_SCHEMA_VERSION,
    kind: "roll_forward",
    blockType: "7",
    prevHash: parentPoint.blockHash,
    rawBlockCbor,
    tip: { kind: "point", ...point },
  });
  if (
    nativeBlock.transactionIds.length !== frames.length ||
    frames.some(
      (tx, index) =>
        CML.hash_transaction(tx.body()).to_hex() !==
        nativeBlock.transactionIds[index],
    )
  )
    throw new Error("Synthetic block changed a transaction identity");
  return Object.freeze({ point, parentPoint, nativeBlock });
};

export type SyntheticFinalizedUserEventBlock = Readonly<{
  finality: WatcherLocalBackfillFinalityReceipt;
  observation: WatcherLocalBackfillObservationReceipt;
  referenceAuthority: ReturnType<
    typeof createWatcherLocalBackfillUserEventReferenceAuthority
  >;
  close: () => Promise<void>;
}>;
export type SyntheticNativeTip = Readonly<{
  blockHash: string;
  blockNo: string;
  slot: string;
}>;
export type SyntheticNativeQuery = Readonly<{
  startupDigest: string;
  target: SyntheticNativeTip;
  tip: SyntheticNativeTip;
}>;
type OriginDeployment = Omit<
  ReturnType<typeof makeOriginDeployment>,
  "signedIdentity" | "trustRoots"
> & {
  signedIdentity: unknown;
  trustRoots: readonly ReturnType<
    typeof makeOriginDeployment
  >["trustRoots"][number][];
};

export type SyntheticUserEventOriginFixture = Readonly<{
  deployment: OriginDeployment;
  deploymentIdentity: ReturnType<typeof makeOriginDeployment>["result"];
  scriptBinding: WatcherUserEventScriptBinding;
  watcherConfig: ReturnType<typeof makeConfig>;
  nativeChainSyncBinaryPath: string;
  activationBlock: SyntheticUserEventBlock;
  emptySuccessorBlock: SyntheticUserEventBlock;
  activationTransactionCbor: string;
  initializationBodyCbor: string;
  makeBlock: (
    input: Readonly<{
      transactions: readonly string[];
      creatingBodies?: readonly string[];
      parent?: SyntheticUserEventBlock;
      slot?: number;
    }>,
  ) => Promise<SyntheticUserEventBlock>;
  openFinalizedBlock: (
    block: SyntheticUserEventBlock,
  ) => Promise<SyntheticFinalizedUserEventBlock>;
  /** Controlled mode only. Set the initial tip before starting a monitor. */
  setNativeTip: (tip: SyntheticNativeTip) => Promise<void>;
  /** Append to the current controlled tip and publish the new tip atomically. */
  appendNativeBlock: (
    input: Readonly<{ transactions: readonly string[]; slot: number }>,
  ) => Promise<SyntheticUserEventBlock>;
  /** Adds actual empty native frames descending from the current controlled tip. */
  growNativeTip: (
    count?: number,
    minimumFirstSlot?: number,
  ) => Promise<SyntheticNativeTip>;
  rollbackNativeStream: (point: SyntheticNativeTip | "origin") => Promise<void>;
  exitNativeStream: (exitCode?: number) => Promise<void>;
  /** Descriptive acquisitions recorded by the actual helper subprocess. */
  readNativeQueries: () => Promise<readonly SyntheticNativeQuery[]>;
  close: () => Promise<void>;
}>;
export const createSyntheticUserEventOriginFixture = async (
  options: Readonly<{
    queryEndpoints?: Readonly<{ ogmios: string; kupo: string }>;
    nativeTipBaseDepth?: number;
    nativeTipMode?: "query_counter" | "controlled";
    nativeStreamInitialAcknowledgement?: boolean;
    blockSlotInterval?: number;
    ruleBundleCommitment?: string;
    protocolParameters?: unknown;
    /** Exact accepted transactions and identity from a live emulator deployment. */
    published?: Readonly<{
      deployment: OriginDeployment;
      transactionCbor: string;
      inclusionSlot?: number;
      creatingTransactions: readonly Readonly<{ transactionCbor: string }>[];
    }>;
  }> = {},
): Promise<SyntheticUserEventOriginFixture> => {
  const nativeTipBaseDepth = options.nativeTipBaseDepth ?? 3000;
  const blockSlotInterval = options.blockSlotInterval ?? 1;
  if (
    !Number.isSafeInteger(blockSlotInterval) ||
    blockSlotInterval < 1 ||
    blockSlotInterval > 60
  ) {
    throw new Error("Synthetic block slot interval is outside fixture bounds");
  }
  const nativeTipMode = options.nativeTipMode ?? "query_counter";
  const nativeStreamInitialAcknowledgement =
    options.nativeStreamInitialAcknowledgement ?? false;
  if (typeof nativeStreamInitialAcknowledgement !== "boolean")
    throw new Error("Synthetic stream acknowledgement option must be boolean");
  if (nativeTipMode !== "query_counter" && nativeTipMode !== "controlled")
    throw new Error("Unknown synthetic native tip mode");
  if (
    !Number.isSafeInteger(nativeTipBaseDepth) ||
    nativeTipBaseDepth < 30 ||
    nativeTipBaseDepth > 4000
  )
    throw new Error(
      "Synthetic native tip base depth is outside fixture bounds",
    );
  const dir = await mkdtemp(join("/var/tmp", "synthetic-user-event-origin-"));
  const nodeConfig = join(dir, "node.json");
  const genesisConfig = join(dir, "genesis.json");
  const binaryPath = join(dir, "helper.mjs");
  const registryPath = join(dir, "blocks.json");
  const counterPath = join(dir, "counter");
  const tipPath = join(dir, "tip.json");
  const controlPath = join(dir, "native-control.json");
  const queryLogPath = join(dir, "native-queries.jsonl");
  await writeFile(genesisConfig, GENESIS_BYTES);
  await writeFile(
    nodeConfig,
    JSON.stringify({ ShelleyGenesisFile: genesisConfig }),
  );
  await writeFile(counterPath, "0");
  await writeFile(queryLogPath, "");
  const deployment =
    options.published?.deployment ??
    makeOriginDeployment(options.ruleBundleCommitment);
  const deploymentIdentity = deployment.result;
  const scriptBinding: WatcherUserEventScriptBinding =
    verifyWatcherUserEventScriptBinding({
      deploymentIdentity,
      blueprintBytes,
    });
  const watcherConfig = makeConfig(
    nodeConfig,
    genesisConfig,
    options.queryEndpoints,
  );
  const blocks: SyntheticUserEventBlock[] = [];
  const creating: Creating[] = [];
  const creatingByHash = new Map<string, Creating>();
  const outputsByAddress = new Map<string, CreatingOutput[]>();
  const outputsByUnit = new Map<string, CreatingOutput[]>();
  const consumptionsByOutRef = new Map<string, Consumption[]>();
  const closed: (() => Promise<void>)[] = [];
  const initialization = options.published ?? INITIALIZATION;
  const initializationTransaction = CML.Transaction.from_cbor_hex(
    initialization.transactionCbor,
  );
  const initialSlot =
    options.published?.inclusionSlot === undefined
      ? initializationTransaction.body().validity_interval_start()! + 1n
      : BigInt(options.published.inclusionSlot) + 1n;
  const seededReferenceSpan =
    2n * BigInt(initialization.creatingTransactions.length);
  const anchorSlot = initialSlot - 3n;
  const latestReferenceStartSlot = anchorSlot - seededReferenceSpan;
  if (latestReferenceStartSlot < 0n) {
    await rm(dir, { recursive: true, force: true });
    throw new Error(
      "Synthetic initialization has insufficient prior slots for its creating transactions",
    );
  }
  // Reference-only prehistory must precede Init in both coordinates. A fixed
  // native height of 100 placed later seeded references after live proof blocks.
  const referenceStartSlot =
    latestReferenceStartSlot < 100n ? latestReferenceStartSlot : 100n;
  const anchorHeight = seededReferenceSpan + 1n;
  const anchor = pointAt(
    "ab".repeat(32),
    anchorHeight > 100n ? anchorHeight : 100n,
    anchorSlot,
  );
  const emptyParent = buildBlock([], anchor);
  blocks.push(emptyParent);
  const activationBlock = buildBlock(
    [initialization.transactionCbor],
    emptyParent.point,
  );
  blocks.push(activationBlock);
  const emptySuccessorBlock = buildBlock([], activationBlock.point);
  blocks.push(emptySuccessorBlock);
  type StreamCommand =
    | Readonly<{ kind: "rollback"; point: SyntheticNativeTip | "origin" }>
    | Readonly<{ kind: "exit"; exitCode: number }>;
  const control: {
    mode: "query_counter" | "controlled";
    tip: SyntheticNativeTip;
    commands: StreamCommand[];
    closed: boolean;
  } = {
    mode: nativeTipMode,
    tip: {
      blockHash: createHash("sha256")
        .update("synthetic-controlled-tip")
        .digest("hex"),
      blockNo: (
        BigInt(emptySuccessorBlock.point.blockNo) + BigInt(nativeTipBaseDepth)
      ).toString(),
      slot: (
        BigInt(emptySuccessorBlock.point.slot) +
        BigInt(Math.max(600, nativeTipBaseDepth))
      ).toString(),
    },
    commands: [],
    closed: false,
  };
  const writeAtomic = async (path: string, value: unknown) => {
    const temporary = `${path}.next`;
    await writeFile(temporary, JSON.stringify(value));
    await rename(temporary, path);
  };
  const persistControl = () => writeAtomic(controlPath, control);
  await persistControl();
  if (nativeTipMode === "query_counter")
    await writeAtomic(tipPath, { kind: "point", ...control.tip });
  let controlWrites: Promise<void> = Promise.resolve();
  const changeControl = <T>(change: () => Promise<T>): Promise<T> => {
    const result = controlWrites.then(async () => {
      if (control.closed) throw new Error("Synthetic native fixture is closed");
      return await change();
    });
    controlWrites = result.then(
      () => undefined,
      () => undefined,
    );
    return result;
  };
  const registerCreating = (
    transactionCbor: string,
    knownBlock?: SyntheticUserEventBlock,
    index = 0,
  ) => {
    const source = withFixtureCml((own) => {
      const transaction = own(CML.Transaction.from_cbor_hex(transactionCbor));
      const body = own(transaction.body());
      const txHash = own(CML.hash_transaction(body)).to_hex();
      const existing = creatingByHash.get(txHash);
      if (existing !== undefined) return existing;
      const position = BigInt(creating.length);
      const predecessorPoint =
        knownBlock?.parentPoint ??
        pointAt(
          createHash("sha256")
            .update(`synthetic-reference-parent-${txHash}`)
            .digest("hex"),
          1n + position * 2n,
          referenceStartSlot + position * 2n,
        );
      const creatingPoint =
        knownBlock?.point ??
        pointAt(
          createHash("sha256")
            .update(`synthetic-reference-child-${txHash}`)
            .digest("hex"),
          2n + position * 2n,
          referenceStartSlot + 1n + position * 2n,
        );
      const inputs = own(body.inputs());
      const inputOutRefs = Array.from({ length: inputs.len() }, (_, index) => {
        const input = own(inputs.get(index));
        return `${own(input.transaction_id()).to_hex()}#${input.index().toString()}`;
      });
      const bodyOutputs = own(body.outputs());
      const outputs = Array.from(
        { length: bodyOutputs.len() },
        (_, outputIndex): CreatingOutput => {
          const output = own(bodyOutputs.get(outputIndex));
          const address = own(output.address()).to_bech32();
          const value = own(output.amount());
          const multiAsset = own(value.multi_asset());
          const policies = own(multiAsset.keys());
          const assets: Record<string, string> = {};
          for (
            let policyIndex = 0;
            policyIndex < policies.len();
            policyIndex++
          ) {
            const policy = own(policies.get(policyIndex));
            const policyAssets = own(multiAsset.get_assets(policy));
            if (policyAssets === undefined)
              throw new Error("Synthetic output lost its asset policy");
            const names = own(policyAssets.keys());
            for (let assetIndex = 0; assetIndex < names.len(); assetIndex++) {
              const name = own(names.get(assetIndex));
              const amount = policyAssets.get(name);
              if (amount === undefined)
                throw new Error("Synthetic output lost its asset quantity");
              assets[`${policy.to_hex()}.${name.to_hex()}`] = amount.toString();
            }
          }
          const datum = own(output.datum());
          const inline = own(datum?.as_datum());
          const datumHash = own(
            inline === undefined
              ? output.datum_hash()
              : CML.hash_plutus_data(inline),
          );
          const script = own(output.script_ref());
          const scriptHash = own(script?.hash());
          const resolvedScript = (() => {
            if (script === undefined) return null;
            const native = own(script.as_native());
            if (native !== undefined)
              return { language: "native", script: native.to_cbor_hex() };
            const versions = [
              ["plutus:v1", own(script.as_plutus_v1())],
              ["plutus:v2", own(script.as_plutus_v2())],
              ["plutus:v3", own(script.as_plutus_v3())],
            ] as const;
            for (const [language, plutus] of versions) {
              if (plutus !== undefined)
                return {
                  language,
                  script: Buffer.from(plutus.to_raw_bytes()).toString("hex"),
                };
            }
            throw new Error("Unsupported fixture reference script");
          })();
          return Object.freeze({
            transaction_index: index,
            transaction_id: txHash,
            output_index: outputIndex,
            address,
            value: Object.freeze({
              coins: value.coin().toString(),
              assets: Object.freeze(assets),
            }),
            datum_hash: datumHash?.to_hex() ?? null,
            ...(datumHash === undefined
              ? {}
              : {
                  datum_type:
                    inline === undefined
                      ? ("hash" as const)
                      : ("inline" as const),
                }),
            script_hash: scriptHash?.to_hex() ?? null,
            created_at: Object.freeze({
              slot_no: Number(creatingPoint.slot),
              header_hash: creatingPoint.blockHash,
            }),
            datum: inline?.to_cbor_hex() ?? null,
            script: resolvedScript,
          });
        },
      );
      const source: Creating = Object.freeze({
        txHash,
        transactionCbor,
        creatingPoint,
        predecessorPoint,
        creatingTransactionIndex: index,
        inputOutRefs: Object.freeze(inputOutRefs),
        outputs: Object.freeze(outputs),
      });
      creating.push(source);
      creatingByHash.set(txHash, source);
      for (const output of outputs) {
        const addressRows = outputsByAddress.get(output.address) ?? [];
        addressRows.push(output);
        outputsByAddress.set(output.address, addressRows);
        for (const [unit, amount] of Object.entries(output.value.assets)) {
          if (amount === "0") continue;
          const unitRows = outputsByUnit.get(unit) ?? [];
          unitRows.push(output);
          outputsByUnit.set(unit, unitRows);
        }
      }
      return source;
    });
    // Reference-only creating frames do not consume inputs in the native chain.
    // Keep every coordinate, including duplicates, so history queries preserve
    // their existing refusal when a synthetic chain spends an outref twice.
    if (knownBlock !== undefined) {
      source.inputOutRefs.forEach((outRef, inputIndex) => {
        const consumptions = consumptionsByOutRef.get(outRef) ?? [];
        consumptions.push(
          Object.freeze({
            transaction_id: source.txHash,
            input_index: inputIndex,
            slot_no: Number(knownBlock.point.slot),
            header_hash: knownBlock.point.blockHash,
          }),
        );
        consumptionsByOutRef.set(outRef, consumptions);
      });
    }
  };
  for (const frame of initialization.creatingTransactions)
    registerCreating(frame.transactionCbor);
  registerCreating(initialization.transactionCbor, activationBlock);
  const persistBlocks = () => writeAtomic(registryPath, blocks);
  await persistBlocks();
  await writeFile(
    binaryPath,
    `#!${process.execPath}
import { appendFileSync, existsSync, readFileSync, renameSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { createInterface } from 'node:readline';
const reader=createInterface({input:process.stdin,crlfDelay:Infinity});
const line=await new Promise(resolve=>reader.once('line',resolve));
const startup=JSON.parse(line);
// The producer replaces these files atomically. Poll metadata every tick, but
// parse growing block registries only when their file identity changes.
const cachedJson=path=>{
  let identity;
  let value;
  return ()=>{
    const stat=statSync(path,{bigint:true});
    const next=[stat.dev,stat.ino,stat.size,stat.mtimeNs,stat.ctimeNs].join(':');
    if(next!==identity){
      value=JSON.parse(readFileSync(path,'utf8'));
      identity=next;
    }
    return value;
  };
};
const readControl=cachedJson(${JSON.stringify(controlPath)});
const readBlocks=cachedJson(${JSON.stringify(registryPath)});
const initialControl=readControl();
if(initialControl.closed) throw new Error('Synthetic fixture is closed');
if(startup.operation.kind!=='exact_point'&&startup.operation.kind!=='stream') throw new Error('Unknown synthetic native operation');
const exact=startup.operation.kind==='exact_point';
const block=exact?readBlocks().find(block=>block.point.blockHash===startup.operation.target.blockHash):null;
if(exact&&!block) throw new Error('Unknown synthetic fixture block');
let legacyTip;
if(initialControl.mode==='query_counter') {
  if(exact) {
    const query=Number(readFileSync(${JSON.stringify(counterPath)},'utf8'))+1;
    writeFileSync(${JSON.stringify(counterPath)},String(query));
    legacyTip={kind:'point',blockHash:createHash('sha256').update('synthetic-tip-'+query).digest('hex'),blockNo:String(BigInt(block.point.blockNo)+BigInt(${nativeTipBaseDepth}+query)),slot:String(BigInt(block.point.slot)+BigInt(${Math.max(600, nativeTipBaseDepth)}+query))};
    writeFileSync(${JSON.stringify(tipPath + ".next")}+process.pid,JSON.stringify(legacyTip));
    renameSync(${JSON.stringify(tipPath + ".next")}+process.pid,${JSON.stringify(tipPath)});
  } else {
    legacyTip=existsSync(${JSON.stringify(tipPath)})?JSON.parse(readFileSync(${JSON.stringify(tipPath)},'utf8')):{kind:'point',...initialControl.tip};
  }
}
const tipAt=control=>control.mode==='controlled'?{kind:'point',...control.tip}:legacyTip;
const canonical=value=>Array.isArray(value)?value.map(canonical):value!==null&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonical(value[key])])):value;
const emit=value=>process.stdout.write(JSON.stringify(canonical(value))+'\\n');
const emitBlock=(block,tip)=>emit({blockHash:block.point.blockHash,blockNo:block.point.blockNo,slot:block.point.slot,blockType:'7',kind:'roll_forward',prevHash:block.parentPoint.blockHash,rawBlockCbor:block.nativeBlock.rawBlockCbor,schemaVersion:startup.schemaVersion,tip});
const startupDigest=createHash('sha256').update(line,'utf8').digest('hex');
const tip=tipAt(initialControl);
emit({authorityNodeId:startup.authorityNodeId,currentTip:tip,genesisIdentitySha256:startup.genesisIdentitySha256,kind:'ready',network:startup.network,networkMagic:startup.networkMagic,operation:startup.operation,schemaVersion:startup.schemaVersion,selectedIntersection:startup.intersection,socketPath:startup.socketPath,startupDigest});
if(!exact&&${JSON.stringify(nativeStreamInitialAcknowledgement)})
  emit({schemaVersion:startup.schemaVersion,kind:'roll_backward',point:startup.intersection,tip});
if(exact) {
  appendFileSync(${JSON.stringify(queryLogPath)},JSON.stringify({startupDigest,target:{blockHash:block.point.blockHash,blockNo:block.point.blockNo,slot:block.point.slot},tip:{blockHash:tip.blockHash,blockNo:tip.blockNo,slot:tip.slot}})+'\\n');
  emitBlock(block,tip);
}
let position=startup.intersection;
let commandCursor=initialControl.commands.length;
setInterval(()=>{
  const control=readControl();
  if(control.closed) process.exit(0);
  if(exact) return;
  const tip=tipAt(control);
  while(commandCursor<control.commands.length) {
    const command=control.commands[commandCursor++];
    if(command.kind==='exit') {
      process.stderr.write('Synthetic native stream exit requested\\n');
      process.exit(command.exitCode);
    }
    position=command.point==='origin'?{kind:'origin'}:{kind:'point',blockHash:command.point.blockHash,slot:command.point.slot};
    emit({schemaVersion:startup.schemaVersion,kind:'roll_backward',point:position,tip});
  }
  const blocks=readBlocks();
  const next=position.kind==='origin'?blocks[0]:blocks.find(block=>block.parentPoint.blockHash===position.blockHash&&block.parentPoint.slot===position.slot);
  if(!next||BigInt(next.point.blockNo)>BigInt(tip.blockNo)||BigInt(next.point.slot)>BigInt(tip.slot)) return;
  emitBlock(next,tip);
  position={kind:'point',blockHash:next.point.blockHash,slot:next.point.slot};
},10);
`,
  );
  await chmod(binaryPath, 0o700);
  class BoundarySocket extends EventTarget {
    readyState = 0;
    intersection = { slot: Number(anchor.slot), id: anchor.blockHash };
    constructor() {
      super();
      queueMicrotask(() => {
        if (this.readyState !== 0) return;
        this.readyState = 1;
        this.dispatchEvent(new Event("open"));
      });
    }
    send(text: string): void {
      if (this.readyState !== 1)
        throw new Error("Synthetic Ogmios socket is not open");
      const request = JSON.parse(text) as {
        id: number;
        method: string;
        params: { points?: ("origin" | { slot: number; id: string })[] };
      };
      let result: unknown;
      if (request.method === "findIntersection") {
        const intersection = request.params.points![0]!;
        if (intersection === "origin") {
          const tip: SyntheticNativeTip =
            nativeTipMode === "controlled"
              ? (
                  JSON.parse(readFileSync(controlPath, "utf8")) as {
                    tip: SyntheticNativeTip;
                  }
                ).tip
              : (JSON.parse(
                  readFileSync(tipPath, "utf8"),
                ) as SyntheticNativeTip);
          result = {
            intersection,
            tip: {
              id: tip.blockHash,
              slot: Number(tip.slot),
              height: Number(tip.blockNo),
            },
          };
        } else {
          this.intersection = intersection;
          result = { intersection };
        }
      } else {
        const block = blocks.find(
          (block) => block.parentPoint.blockHash === this.intersection.id,
        );
        const references = creating.filter(
          (row) => row.predecessorPoint.blockHash === this.intersection.id,
        );
        // Controlled tips can also be parents of later test blocks. Kupo
        // advertises those checkpoints, so its Ogmios peer must expose their
        // heights when the boundary search probes them. They carry no txs.
        const parentCheckpoint = blocks
          .map(({ parentPoint }) => parentPoint)
          .filter(
            (point) => BigInt(point.slot) > BigInt(this.intersection.slot),
          )
          .sort((a, b) => Number(BigInt(a.slot) - BigInt(b.slot)))[0];
        const point =
          block?.point ?? references[0]?.creatingPoint ?? parentCheckpoint;
        if (point === undefined)
          throw new Error("Synthetic fixture has no requested child");
        const transactions =
          block === undefined
            ? references.map((row) => ({
                id: row.txHash,
                cbor: row.transactionCbor,
              }))
            : block.nativeBlock.transactionIds.map((id, index) => ({
                id,
                cbor: block.nativeBlock.transactionCbors[index]!,
              }));
        result = {
          direction: "forward",
          block: {
            id: point.blockHash,
            slot: Number(point.slot),
            height: Number(point.blockNo),
            ancestor: this.intersection.id,
            transactions,
          },
        };
      }
      queueMicrotask(() =>
        this.dispatchEvent(
          new MessageEvent("message", {
            data: JSON.stringify({ jsonrpc: "2.0", id: request.id, result }),
          }),
        ),
      );
    }
    close(): void {
      if (this.readyState >= 2) return;
      this.readyState = 2;
      queueMicrotask(() => {
        this.readyState = 3;
        this.dispatchEvent(
          Object.assign(new Event("close"), {
            code: 1000,
            reason: "",
            wasClean: true,
          }),
        );
      });
    }
  }
  vi.stubGlobal("WebSocket", BoundarySocket);
  const originalFetch = globalThis.fetch;
  vi.stubGlobal("fetch", async (url: string, init?: RequestInit) => {
    // Other local services (trusted-head authority, mutation leases) retain
    // their actual HTTP handlers when this fixture supplies chain transport.
    if (
      options.queryEndpoints !== undefined &&
      !Object.values(options.queryEndpoints).some(
        (endpoint) =>
          new URL(endpoint.replace(/^ws/u, "http")).origin ===
          new URL(url).origin,
      )
    ) {
      try {
        // Synthetic ledger time advances independently of the local HTTP
        // server's idle timers; do not reuse its idle test connections.
        const headers = new Headers(init?.headers);
        headers.set("connection", "close");
        return await originalFetch(url, { ...init, headers });
      } catch (cause) {
        const endpoint = new URL(url);
        throw new Error(
          `Fixture service request failed: ${init?.method ?? "GET"} ${endpoint.origin}${endpoint.pathname}`,
          { cause },
        );
      }
    }
    const path = new URL(url).pathname;
    if (init?.method === "POST") {
      const request = JSON.parse(String(init.body)) as {
        id: string;
        method: string;
      };
      if (
        request.method === "queryLedgerState/protocolParameters" &&
        options.protocolParameters !== undefined
      ) {
        return new Response(
          JSON.stringify({
            jsonrpc: "2.0",
            id: request.id,
            result: options.protocolParameters,
          }),
        );
      }
      if (request.method !== "queryNetwork/tip")
        throw new Error("Synthetic fixture has no requested HTTP RPC");
      const tip: SyntheticNativeTip =
        nativeTipMode === "controlled"
          ? (
              JSON.parse(readFileSync(controlPath, "utf8")) as {
                tip: SyntheticNativeTip;
              }
            ).tip
          : (JSON.parse(readFileSync(tipPath, "utf8")) as SyntheticNativeTip);
      return new Response(
        JSON.stringify({
          jsonrpc: "2.0",
          id: request.id,
          result: {
            id: tip.blockHash,
            height: Number(tip.blockNo),
            slot: Number(tip.slot),
          },
        }),
      );
    }
    const headers = {
      "X-Most-Recent-Checkpoint": "999999",
      ETag: "55".repeat(32),
    };
    if (path.startsWith("/matches/")) {
      const pattern = decodeURIComponent(path.slice("/matches/".length));
      const [rawIndex, txHash] = pattern.split("@");
      const unit = /^[0-9a-f]{56}\.(?:[0-9a-f]{2}){0,32}$/u.test(pattern)
        ? pattern.replace(".", "")
        : null;
      const address = /^addr(?:_test)?1[0-9a-z]+$/u.test(pattern)
        ? pattern
        : null;
      let rows: readonly CreatingOutput[];
      if (unit !== null) {
        rows = outputsByUnit.get(pattern) ?? [];
      } else if (address !== null) {
        rows = outputsByAddress.get(address) ?? [];
      } else {
        const source = creatingByHash.get(txHash!);
        if (source === undefined)
          throw new Error(
            `Synthetic fixture has no requested creating frame: ${pattern}`,
          );
        if (rawIndex === "*") {
          rows = source.outputs;
        } else {
          const outputIndex = Number(rawIndex);
          const output = source.outputs[outputIndex];
          if (!Number.isSafeInteger(outputIndex) || output === undefined)
            throw new Error(
              `Synthetic fixture has no requested output: ${pattern}`,
            );
          rows = [output];
        }
      }
      const matches = rows.map((output) => {
        // Unit/address queries report native-chain consumption; exact outref
        // queries deliberately retain this fixture's existing unspent view.
        const consumptions =
          unit !== null || address !== null
            ? (consumptionsByOutRef.get(
                `${output.transaction_id}#${output.output_index.toString()}`,
              ) ?? [])
            : [];
        if (consumptions.length > 1)
          throw new Error(
            "Synthetic unit history contains a duplicate consumption",
          );
        return { ...output, spent_at: consumptions[0] ?? null };
      });
      return new Response(JSON.stringify(matches), { headers });
    }
    const slot = Number(path.split("/").at(-1));
    const points = [
      anchor,
      ...blocks.flatMap((block) => [block.point, block.parentPoint]),
      ...creating.flatMap((row) => [row.creatingPoint, row.predecessorPoint]),
    ];
    const point = points
      .sort((a, b) => Number(b.slot) - Number(a.slot))
      .find((point) => Number(point.slot) <= slot);
    if (point === undefined)
      throw new Error("Synthetic fixture has no requested checkpoint");
    return new Response(
      JSON.stringify({
        slot_no: Number(point.slot),
        header_hash: point.blockHash,
      }),
      { headers },
    );
  });
  const makeBlock = async ({
    transactions,
    creatingBodies = [],
    parent,
    slot,
  }: Readonly<{
    transactions: readonly string[];
    creatingBodies?: readonly string[];
    parent?: SyntheticUserEventBlock;
    slot?: number;
  }>) =>
    changeControl(async () => {
      // Resolve the default parent under the same lock as insertion. Concurrent
      // callers must extend one chain rather than race into sibling blocks.
      const actualParent = parent ?? blocks.at(-1)!;
      const interval =
        slot === undefined
          ? BigInt(blockSlotInterval)
          : BigInt(slot) - BigInt(actualParent.point.slot);
      if (interval < 1n)
        throw new Error(
          "Synthetic block inclusion must follow its parent slot",
        );
      const block = buildBlock(transactions, actualParent.point, interval);
      blocks.push(block);
      for (const body of creatingBodies) {
        const transaction = CML.Transaction.new(
          CML.TransactionBody.from_cbor_hex(body),
          CML.TransactionWitnessSet.new(),
          true,
        );
        registerCreating(transaction.to_cbor_hex());
      }
      transactions.forEach((cbor, index) =>
        registerCreating(cbor, block, index),
      );
      await persistBlocks();
      return block;
    });
  const snapshotTip = (tip: SyntheticNativeTip): SyntheticNativeTip => {
    if (
      !/^[0-9a-f]{64}$/u.test(tip.blockHash) ||
      [tip.blockNo, tip.slot].some(
        (value) =>
          !/^(0|[1-9][0-9]*)$/u.test(value) ||
          BigInt(value) > 0xffffffffffffffffn,
      )
    )
      throw new Error("Synthetic native tip has invalid coordinates");
    return Object.freeze({
      blockHash: tip.blockHash,
      blockNo: tip.blockNo,
      slot: tip.slot,
    });
  };
  const requireControlledTip = () => {
    if (nativeTipMode !== "controlled")
      throw new Error("Synthetic native tip controls require controlled mode");
  };
  const setNativeTip = (tip: SyntheticNativeTip) => {
    requireControlledTip();
    const snapshot = snapshotTip(tip);
    return changeControl(async () => {
      control.tip = snapshot;
      await persistControl();
    });
  };
  const appendNativeBlock = ({
    transactions,
    slot,
  }: Readonly<{ transactions: readonly string[]; slot: number }>) => {
    requireControlledTip();
    if (!Number.isSafeInteger(slot) || slot < 0)
      throw new Error("Native inclusion slot is invalid");
    return changeControl(async () => {
      const parent = control.tip;
      const interval = BigInt(slot) - BigInt(parent.slot);
      if (interval < 1n)
        throw new Error("Native inclusion must follow the controlled tip slot");
      for (const cbor of transactions) {
        const body = CML.Transaction.from_cbor_hex(cbor).body();
        const start = body.validity_interval_start();
        const end = body.ttl();
        if (
          (start !== undefined && BigInt(slot) < start) ||
          (end !== undefined && BigInt(slot) >= end)
        )
          throw new Error(
            `Confirmed transaction ${CML.hash_transaction(body).to_hex()} is outside its validity interval at slot ${slot}`,
          );
      }
      const block = buildBlock(
        transactions,
        pointAt(parent.blockHash, BigInt(parent.blockNo), BigInt(parent.slot)),
        interval,
      );
      blocks.push(block);
      transactions.forEach((cbor, index) =>
        registerCreating(cbor, block, index),
      );
      await persistBlocks();
      control.tip = snapshotTip(block.point);
      await persistControl();
      return block;
    });
  };
  const growNativeTip = (count = 1, minimumFirstSlot?: number) => {
    requireControlledTip();
    if (!Number.isSafeInteger(count) || count < 1 || count > 4096)
      throw new Error("Synthetic native tip growth is outside fixture bounds");
    if (
      minimumFirstSlot !== undefined &&
      (!Number.isSafeInteger(minimumFirstSlot) || minimumFirstSlot < 0)
    )
      throw new Error("Synthetic minimum growth slot is invalid");
    return changeControl(async () => {
      const start = control.tip;
      snapshotTip({
        ...start,
        blockNo: (BigInt(start.blockNo) + BigInt(count)).toString(),
        slot: (
          BigInt(start.slot) + BigInt(count * blockSlotInterval)
        ).toString(),
      });
      let parentPoint = pointAt(
        start.blockHash,
        BigInt(start.blockNo),
        BigInt(start.slot),
      );
      for (let index = 0; index < count; index++) {
        const minimumInterval =
          index === 0 && minimumFirstSlot !== undefined
            ? BigInt(minimumFirstSlot) - BigInt(parentPoint.slot)
            : 0n;
        const next = buildBlock(
          [],
          parentPoint,
          minimumInterval > BigInt(blockSlotInterval)
            ? minimumInterval
            : BigInt(blockSlotInterval),
        );
        blocks.push(next);
        parentPoint = next.point;
      }
      const tip = snapshotTip(parentPoint);
      await persistBlocks();
      control.tip = tip;
      await persistControl();
      return tip;
    });
  };
  const appendStreamCommand = (command: StreamCommand) =>
    changeControl(async () => {
      if (control.commands.length >= 128)
        throw new Error("Synthetic native stream command limit exceeded");
      control.commands.push(command);
      await persistControl();
    });
  const rollbackNativeStream = (point: SyntheticNativeTip | "origin") =>
    appendStreamCommand({
      kind: "rollback",
      point: point === "origin" ? point : snapshotTip(point),
    });
  const exitNativeStream = (exitCode = 1) => {
    if (!Number.isSafeInteger(exitCode) || exitCode < 1 || exitCode > 255)
      throw new Error(
        "Synthetic native stream exit code is outside fixture bounds",
      );
    return appendStreamCommand({ kind: "exit", exitCode });
  };
  const readNativeQueries = async (): Promise<
    readonly SyntheticNativeQuery[]
  > => {
    const text = await readFile(queryLogPath, "utf8");
    return Object.freeze(
      text
        .slice(0, text.lastIndexOf("\n") + 1)
        .split("\n")
        .filter(Boolean)
        .map((line) => {
          const query = JSON.parse(line) as SyntheticNativeQuery;
          return Object.freeze({
            startupDigest: query.startupDigest,
            target: snapshotTip(query.target),
            tip: snapshotTip(query.tip),
          });
        }),
    );
  };
  const openFinalizedBlock = async (block: SyntheticUserEventBlock) => {
    const args = {
      watcherConfig,
      deploymentIdentity,
      nativeChainSyncBinaryPath: binaryPath,
      point: block.point,
      limits: { timeoutMs: 60_000 },
    };
    const first = await openWatcherLocalHistoricalCapture(args);
    closed.push(first.close);
    const firstObservation = admitWatcherLocalBackfillObservation(
      first.receipt,
    );
    const pending = admitWatcherLocalBackfillFinality({
      ...args,
      observation: firstObservation,
      previous: null,
    });
    if (
      pending.result.action !== "observe_pending" ||
      pending.admitted === null
    )
      throw new Error("Synthetic W12 first capture did not become pending");
    await first.close();
    const current = await openWatcherLocalHistoricalCapture(args);
    closed.push(current.close);
    const observation: WatcherLocalBackfillObservationReceipt =
      admitWatcherLocalBackfillObservation(current.receipt);
    const result = admitWatcherLocalBackfillFinality({
      ...args,
      observation,
      previous: pending.admitted,
    });
    if (result.result.action !== "finalize" || result.admitted === null)
      throw new Error("Synthetic W12 deeper capture did not finalize");
    const finality: WatcherLocalBackfillFinalityReceipt = result.admitted;
    const referenceAuthority =
      createWatcherLocalBackfillUserEventReferenceAuthority({
        deploymentIdentity,
        finality,
        observation,
      });
    return {
      finality,
      observation,
      referenceAuthority,
      close: current.close,
    };
  };
  let closing: Promise<void> | undefined;
  const close = () =>
    (closing ??= (async () => {
      await controlWrites;
      control.closed = true;
      const stopControl = await Promise.allSettled([persistControl()]);
      const outcomes = await Promise.allSettled(
        closed
          .splice(0)
          .reverse()
          .map((stop) => stop()),
      );
      const cleanup = await Promise.allSettled([
        rm(dir, { recursive: true, force: true }),
        Promise.resolve().then(() => vi.unstubAllGlobals()),
      ]);
      const errors = [...stopControl, ...outcomes, ...cleanup].flatMap(
        (result) => (result.status === "rejected" ? [result.reason] : []),
      );
      if (errors.length > 0)
        throw new AggregateError(
          errors,
          "Synthetic origin fixture cleanup failed",
        );
    })());
  return {
    deployment,
    deploymentIdentity,
    scriptBinding,
    watcherConfig,
    nativeChainSyncBinaryPath: binaryPath,
    activationBlock,
    emptySuccessorBlock,
    activationTransactionCbor: initialization.transactionCbor,
    initializationBodyCbor: initializationTransaction.body().to_cbor_hex(),
    makeBlock,
    openFinalizedBlock,
    setNativeTip,
    appendNativeBlock,
    growNativeTip,
    rollbackNativeStream,
    exitNativeStream,
    readNativeQueries,
    close,
  };
};
