import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

import {
  buildVanRossemFitLedger,
  type VanRossemFitLedger,
} from "../src/proof-fit/van-rossem-fit-ledger.js";
import { realBlueprintPath } from "./support/emulator/blueprints.js";

const ledgerPath = new URL(
  "../../../docs/fault-proofs/size-plans/spend-input-signer-missing-v1-fit-ledger.json",
  import.meta.url,
);

/**
 * Every transaction the maximum lifecycle submits, by name. The stored ledger
 * is regenerated by running `spend-input-signer-missing-lifecycle.test.ts`
 * with `MIDGARD_UPDATE_FIT=1`; this list pins that no row of the maximum
 * shape, of the cancel sweep, or of the applied-script publication has gone
 * missing from it.
 */
const EXACT_ROWS = [
  ...Array.from(
    { length: 5 },
    (_, index) => `step0${(index + 1).toString()}-reference-publication`,
  ),
  "certificate-reference-publication",
  "cancel-step01",
  "cancel-step02",
  "cancel-step03",
  "cancel-step04-initial",
  "cancel-step04-resumed",
  "cancel-step05",
  "accepted-init",
  "accepted-step01",
  "accepted-step02",
  // Every scan batch re-mints the field-7 certificate (`-00`) before the
  // resumed scan transaction itself (`-01`).
  ...Array.from({ length: 20 }, (_, index) => [
    `accepted-step04-${index.toString().padStart(2, "0")}-00`,
    `accepted-step04-${index.toString().padStart(2, "0")}-01`,
  ]).flat(),
  "accepted-step05-proof-mint",
  "accepted-remove",
  "forced-init",
  "forced-step01",
  "forced-step02",
  "forced-step03",
  "forced-step04",
  "forced-step05-proof-mint",
  "forced-remove",
] as const;

/** Step 03 at the maximum shape publishes three chunks, mints the
 * certificate, and then continues the thread: five measured rows. */
const STEP_03_ROW_PREFIX = "accepted-step03-";
const STEP_03_ROW_COUNT = 5;

describe("spendInputSignerMissing signed Van Rossem fit ledger", () => {
  it("is bound to the fresh locked build and reproduces every maximum row with positive margins", async () => {
    const stored = JSON.parse(
      await readFile(ledgerPath, "utf8"),
    ) as VanRossemFitLedger;
    const blueprintBytes = await readFile(realBlueprintPath);
    const blueprint = JSON.parse(blueprintBytes.toString("utf8")) as {
      readonly preamble: { readonly compiler: { readonly version: string } };
    };
    expect(stored.blueprintSha256).toBe(
      createHash("sha256").update(blueprintBytes).digest("hex"),
    );
    expect(stored.compilerVersion).toBe(blueprint.preamble.compiler.version);
    expect(stored.category).toBe("spendInputSignerMissing:00000027:testnet");
    // The margins and the ledger digest are derived, never hand-edited: the
    // writer must reproduce the stored file from its raw measurements alone.
    const rebuilt = buildVanRossemFitLedger({
      category: stored.category,
      blueprintSha256: stored.blueprintSha256,
      compilerVersion: stored.compilerVersion,
      measurements: stored.entries.map((entry) => ({
        name: entry.name,
        kind: entry.kind,
        maximumShape: entry.maximumShape,
        signedBytes: entry.signedBytes,
        memoryUnits: BigInt(entry.memoryUnits),
        cpuUnits: BigInt(entry.cpuUnits),
      })),
    });
    expect(rebuilt).toStrictEqual(stored);
    const names = new Set(stored.entries.map((entry) => entry.name));
    for (const row of EXACT_ROWS) expect(names.has(row), row).toBe(true);
    expect(
      stored.entries.filter((entry) =>
        entry.name.startsWith(STEP_03_ROW_PREFIX),
      ),
    ).toHaveLength(STEP_03_ROW_COUNT);
    for (const entry of stored.entries) {
      expect(entry.signedByteMargin, entry.name).toBeGreaterThan(0);
      expect(BigInt(entry.memoryUnitMargin), entry.name).toBeGreaterThan(0n);
      expect(BigInt(entry.cpuUnitMargin), entry.name).toBeGreaterThan(0n);
      if (entry.kind === "publication") {
        expect(entry.publicationReserveMargin, entry.name).not.toBeNull();
        expect(
          entry.publicationReserveMargin!,
          entry.name,
        ).toBeGreaterThanOrEqual(0);
      }
    }
  });
});
