import { encodeCbor } from "@al-ft/midgard-core/codec";
import { type RejectionReason } from "@al-ft/midgard-sdk";

import {
  EXECUTION_NATIVE_SCRIPT_INVALID_COMPLETE_CANONICAL_REPLAY,
  FIELD_ITEM_WIDTH_ILLEGAL_COMPLETE_CANONICAL_REPLAY,
  FIELD_PREIMAGE_LENGTH_MISMATCH_COMPLETE_CANONICAL_REPLAY,
  INPUT_SET_UNIQUENESS_COMPLETE_CANONICAL_REPLAY,
  INVALID_RANGE_COMPLETE_CANONICAL_REPLAY,
  INVALID_SIGNATURE_COMPLETE_CANONICAL_REPLAY,
  MIN_ADA_COMPLETE_CANONICAL_REPLAY,
  MIN_FEE_COMPLETE_CANONICAL_REPLAY,
  MINT_DECLARED_ASSET_LIMIT_COMPLETE_CANONICAL_REPLAY,
  MISSING_SIGNATURE_COMPLETE_CANONICAL_REPLAY,
  NATIVE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
  NATIVE_SCRIPT_INVALID_COMPLETE_CANONICAL_REPLAY,
  NETWORK_ID_COMPLETE_CANONICAL_REPLAY,
  NO_REFERENCE_INPUT_COMPLETE_CANONICAL_REPLAY,
  NON_EXISTENT_INPUT_COMPLETE_CANONICAL_REPLAY,
  OBSERVER_ORDER_INVALID_COMPLETE_CANONICAL_REPLAY,
  OBSERVERS_FORBIDDEN_ON_UNTAGGED_NETWORK_COMPLETE_CANONICAL_REPLAY,
  OUTPUT_REFERENCE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
  PROTECTED_OUTPUT_SIGNER_MISSING_COMPLETE_CANONICAL_REPLAY,
  REDEEMER_CANONICITY_COMPLETE_CANONICAL_REPLAY,
  RESOLVED_OUTPUT_NON_CANONICAL_COMPLETE_CANONICAL_REPLAY,
  SCRIPT_INTEGRITY_HASH_MISSING_COMPLETE_CANONICAL_REPLAY,
  SPEND_INPUT_SIGNER_MISSING_COMPLETE_CANONICAL_REPLAY,
  TRANSACTION_OUTPUT_NON_CANONICAL_COMPLETE_CANONICAL_REPLAY,
  VALUE_NOT_PRESERVED_COMPLETE_CANONICAL_REPLAY,
  WITNESS_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
  ZERO_INPUT_COMPLETE_CANONICAL_REPLAY,
} from "../src/workflow/complete-replay.js";
import { outRefCbor } from "./helpers/canonical-block-evidence-fixture.js";
import {
  outputWithNativeScript,
  outputWithRawNativePayload,
} from "./support/output-reference-script-decoding-emulator.js";
import {
  canonicalRedeemer,
  nativeFalseScript,
  nativeMint,
  nativeSignatureScript,
  nativeTrueScript,
  output,
  type ReasonCase,
  signerHash,
} from "./typed-reason-retained-classification.reason-case.js";

export const cases: readonly ReasonCase[] = [
  {
    arm: "ValueNotPreserved",
    category: "valueNotPreserved",
    replayer: VALUE_NOT_PRESERVED_COMPLETE_CANONICAL_REPLAY,
    reason: "ValueNotPreserved",
    accepted: {},
    wrongful: { outputs: [output(1_999_993n)] },
    priorLedger: true,
  },
  {
    arm: "ExecutionNativeScriptFalse",
    category: "executionNativeScriptInvalid",
    replayer: EXECUTION_NATIVE_SCRIPT_INVALID_COMPLETE_CANONICAL_REPLAY,
    reason: { ExecutionNativeScriptFalse: { execution_index: 0n } },
    accepted: nativeMint(nativeFalseScript),
    wrongful: nativeMint(nativeTrueScript),
    priorLedger: true,
  },
  {
    arm: "SpendInputSignerMissing",
    category: "spendInputSignerMissing",
    replayer: SPEND_INPUT_SIGNER_MISSING_COMPLETE_CANONICAL_REPLAY,
    reason: { SpendInputSignerMissing: { input_index: 0n } },
    accepted: {},
    wrongful: {},
    wrongfulWitness: "valid",
    priorLedger: true,
  },
  {
    arm: "InputSpentOutputNonCanonical",
    category: "resolvedOutputNonCanonical",
    replayer: RESOLVED_OUTPUT_NON_CANONICAL_COMPLETE_CANONICAL_REPLAY,
    reason: {
      InputSpentOutputNonCanonical: { source_kind: 0n, input_index: 0n },
    },
    accepted: {},
    wrongful: {},
    priorLedger: true,
    acceptedApplicability: "not_exercised",
  },
  ...(
    [
      "ResolvedReferenceScriptMalformed",
      "ResolvedReferenceScriptNodeLimit",
      "ResolvedReferenceScriptDepthLimit",
    ] as const
  ).map(
    (arm): ReasonCase => ({
      arm,
      category: "nativeScriptDecoding",
      replayer: NATIVE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
      reason: {
        [arm]: { source_kind: 0n, input_index: 0n },
      } as RejectionReason,
      accepted: {},
      wrongful: {},
      priorLedger: true,
      priorOutput: outputWithNativeScript({ type: "all", scripts: [] }),
      acceptedApplicability: "not_exercised",
    }),
  ),
  {
    arm: "InputNotFound",
    category: "nonExistentInput",
    replayer: NON_EXISTENT_INPUT_COMPLETE_CANONICAL_REPLAY,
    reason: { InputNotFound: { source_kind: 0n, input_index: 0n } },
    accepted: { spendInputs: [outRefCbor(72, 0n)] },
    wrongful: {},
    priorLedger: true,
  },
  {
    arm: "InputNotFound",
    category: "noReferenceInput",
    replayer: NO_REFERENCE_INPUT_COMPLETE_CANONICAL_REPLAY,
    reason: { InputNotFound: { source_kind: 1n, input_index: 0n } },
    accepted: { referenceInputs: [outRefCbor(72, 0n)] },
    wrongful: { referenceInputs: [outRefCbor(71, 0n)] },
    priorLedger: true,
  },
  {
    arm: "WitnessNativeScriptNodeLimit",
    category: "witnessScriptDecoding",
    replayer: WITNESS_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
    reason: { WitnessNativeScriptNodeLimit: { script_index: 0n } },
    accepted: {},
    wrongful: { scriptWitnesses: [nativeTrueScript] },
    acceptedApplicability: "unreachable_under_consensus_bounds",
  },
  {
    arm: "WitnessNativeScriptDepthLimit",
    category: "witnessScriptDecoding",
    replayer: WITNESS_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
    reason: { WitnessNativeScriptDepthLimit: { script_index: 0n } },
    accepted: {},
    wrongful: { scriptWitnesses: [nativeTrueScript] },
    acceptedApplicability: "unreachable_under_consensus_bounds",
  },
  {
    arm: "OutputReferenceScriptNodeLimit",
    category: "outputReferenceScriptDecoding",
    replayer: OUTPUT_REFERENCE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
    reason: { OutputReferenceScriptNodeLimit: { output_index: 0n } },
    accepted: {},
    wrongful: {
      outputs: [outputWithNativeScript({ type: "all", scripts: [] })],
    },
    acceptedApplicability: "unreachable_under_consensus_bounds",
  },
  {
    arm: "OutputReferenceScriptDepthLimit",
    category: "outputReferenceScriptDecoding",
    replayer: OUTPUT_REFERENCE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
    reason: { OutputReferenceScriptDepthLimit: { output_index: 0n } },
    accepted: {},
    wrongful: {
      outputs: [outputWithNativeScript({ type: "all", scripts: [] })],
    },
    acceptedApplicability: "unreachable_under_consensus_bounds",
  },
  {
    arm: "AddressWitnessSignatureInvalid",
    category: "invalidSignature",
    replayer: INVALID_SIGNATURE_COMPLETE_CANONICAL_REPLAY,
    reason: { AddressWitnessSignatureInvalid: { witness_index: 0n } },
    accepted: {},
    wrongful: {},
    acceptedWitness: "invalid",
    wrongfulWitness: "valid",
  },
  {
    arm: "RequiredSignerUnsigned",
    category: "missingSignature",
    replayer: MISSING_SIGNATURE_COMPLETE_CANONICAL_REPLAY,
    reason: { RequiredSignerUnsigned: { signer_index: 0n } },
    accepted: { requiredSigners: [signerHash] },
    wrongful: { requiredSigners: [signerHash] },
    wrongfulWitness: "valid",
  },
  {
    arm: "OutputNonCanonical",
    category: "transactionOutputNonCanonical",
    replayer: TRANSACTION_OUTPUT_NON_CANONICAL_COMPLETE_CANONICAL_REPLAY,
    reason: { OutputNonCanonical: { output_index: 0n } },
    accepted: { outputs: [Buffer.from("a0", "hex")] },
    wrongful: { outputs: [output()] },
  },
  {
    arm: "ProtectedOutputSignerMissing",
    category: "protectedOutputSignerMissing",
    replayer: PROTECTED_OUTPUT_SIGNER_MISSING_COMPLETE_CANONICAL_REPLAY,
    reason: { ProtectedOutputSignerMissing: { output_index: 0n } },
    accepted: { outputs: [output(2_000_000n, true)] },
    wrongful: { outputs: [output(2_000_000n, true)] },
    wrongfulWitness: "valid",
  },
  {
    arm: "MintDeclaredAssetLimit",
    category: "mintDeclaredAssetLimit",
    replayer: MINT_DECLARED_ASSET_LIMIT_COMPLETE_CANONICAL_REPLAY,
    reason: { MintDeclaredAssetLimit: { policy_index: 0n } },
    accepted: {
      mintPolicyItems: [
        Buffer.concat([
          Buffer.from("82581c", "hex"),
          Buffer.alloc(28, 0x31),
          Buffer.from("b9400100", "hex"),
        ]),
      ],
    },
    wrongful: {
      mintPolicyItems: [
        encodeCbor([Buffer.alloc(28, 0x31), new Map([[Buffer.alloc(0), 1n]])]),
      ],
    },
  },
  {
    arm: "OutputReferenceScriptMalformed",
    category: "outputReferenceScriptDecoding",
    replayer: OUTPUT_REFERENCE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
    reason: { OutputReferenceScriptMalformed: { output_index: 0n } },
    accepted: {
      outputs: [outputWithRawNativePayload(Buffer.from("820700", "hex"))],
    },
    wrongful: {
      outputs: [outputWithNativeScript({ type: "all", scripts: [] })],
    },
  },
  {
    arm: "OutputBelowMinAda",
    category: "minAda",
    replayer: MIN_ADA_COMPLETE_CANONICAL_REPLAY,
    reason: { OutputBelowMinAda: { output_index: 0n } },
    accepted: { outputs: [output(1n)] },
    wrongful: { outputs: [output(2_000_000n)] },
  },
  {
    arm: "FieldPreimageLengthMismatch",
    category: "fieldPreimageLengthMismatch",
    replayer: FIELD_PREIMAGE_LENGTH_MISMATCH_COMPLETE_CANONICAL_REPLAY,
    reason: { FieldPreimageLengthMismatch: { field_index: 0n } },
    accepted: {},
    wrongful: {},
    mismatchFieldIndex: 0,
  },
  {
    arm: "FeeBelowMinimum",
    category: "minFee",
    replayer: MIN_FEE_COMPLETE_CANONICAL_REPLAY,
    reason: "FeeBelowMinimum",
    accepted: {},
    wrongful: {},
    minFeeB: 8n,
  },
  {
    arm: "WitnessScriptHeaderMalformed",
    category: "witnessScriptDecoding",
    replayer: WITNESS_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
    reason: { WitnessScriptHeaderMalformed: { script_index: 0n } },
    accepted: { scriptWitnesses: [Buffer.from("8201410a", "hex")] },
    wrongful: { scriptWitnesses: [nativeTrueScript] },
  },
  {
    arm: "WitnessNativeScriptMalformed",
    category: "witnessScriptDecoding",
    replayer: WITNESS_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
    reason: { WitnessNativeScriptMalformed: { script_index: 0n } },
    accepted: { scriptWitnesses: [Buffer.from("820043820700", "hex")] },
    wrongful: { scriptWitnesses: [nativeTrueScript] },
  },
  {
    arm: "WitnessNativeScriptFalse",
    category: "nativeScriptInvalid",
    replayer: NATIVE_SCRIPT_INVALID_COMPLETE_CANONICAL_REPLAY,
    reason: { WitnessNativeScriptFalse: { script_index: 0n } },
    accepted: { scriptWitnesses: [nativeSignatureScript] },
    wrongful: { scriptWitnesses: [nativeTrueScript] },
  },
  {
    arm: "ScriptIntegrityHashMissing",
    category: "scriptIntegrityHashMissing",
    replayer: SCRIPT_INTEGRITY_HASH_MISSING_COMPLETE_CANONICAL_REPLAY,
    reason: "ScriptIntegrityHashMissing",
    accepted: { scriptWitnesses: [Buffer.from("82034401020304", "hex")] },
    wrongful: {
      scriptWitnesses: [Buffer.from("82034401020304", "hex")],
      scriptIntegrityHash: Buffer.alloc(32, 1),
    },
  },
  {
    arm: "RedeemerMalformed",
    category: "redeemerCanonicity",
    replayer: REDEEMER_CANONICITY_COMPLETE_CANONICAL_REPLAY,
    reason: { RedeemerMalformed: { redeemer_index: 0n } },
    accepted: { redeemerWitnesses: [Buffer.from("ff", "hex")] },
    wrongful: { redeemerWitnesses: [canonicalRedeemer] },
  },
  {
    arm: "FieldItemWidthIllegal",
    category: "fieldItemWidthIllegal",
    replayer: FIELD_ITEM_WIDTH_ILLEGAL_COMPLETE_CANONICAL_REPLAY,
    reason: { FieldItemWidthIllegal: { field_index: 5n, item_index: 0n } },
    accepted: { mintPolicyItems: [Buffer.alloc(0)] },
    wrongful: { mintPolicyItems: [Buffer.alloc(29, 0xe6)] },
  },
  {
    arm: "EmptyInputs",
    category: "zeroInput",
    replayer: ZERO_INPUT_COMPLETE_CANONICAL_REPLAY,
    reason: "EmptyInputs",
    accepted: { spendInputs: [] },
    wrongful: {},
  },
  {
    arm: "DuplicateInput",
    category: "inputSetUniqueness",
    replayer: INPUT_SET_UNIQUENESS_COMPLETE_CANONICAL_REPLAY,
    reason: {
      DuplicateInput: {
        first_field_index: 0n,
        first_item_index: 0n,
        second_field_index: 0n,
        second_item_index: 1n,
      },
    },
    accepted: { spendInputs: [outRefCbor(71, 0n), outRefCbor(71, 0n)] },
    wrongful: { spendInputs: [outRefCbor(71, 0n), outRefCbor(72, 0n)] },
  },
  {
    arm: "ValidityIntervalMalformed",
    category: "invalidRange",
    replayer: INVALID_RANGE_COMPLETE_CANONICAL_REPLAY,
    reason: "ValidityIntervalMalformed",
    accepted: { validityIntervalStart: 30n, validityIntervalEnd: 20n },
    wrongful: {},
  },
  {
    arm: "ValidityIntervalExcludesBlockSlot",
    category: "invalidRange",
    replayer: INVALID_RANGE_COMPLETE_CANONICAL_REPLAY,
    reason: "ValidityIntervalExcludesBlockSlot",
    accepted: { validityIntervalStart: 30n, validityIntervalEnd: 40n },
    wrongful: {},
  },
  {
    arm: "NetworkIdMismatch",
    category: "networkId",
    replayer: NETWORK_ID_COMPLETE_CANONICAL_REPLAY,
    reason: "NetworkIdMismatch",
    accepted: { networkId: 1n },
    wrongful: {},
  },
  {
    arm: "ObserversForbiddenOnUntaggedNetwork",
    category: "observersForbiddenOnUntaggedNetwork",
    replayer: OBSERVERS_FORBIDDEN_ON_UNTAGGED_NETWORK_COMPLETE_CANONICAL_REPLAY,
    reason: "ObserversForbiddenOnUntaggedNetwork",
    accepted: {
      scriptIntegrityHash: Buffer.alloc(32, 1),
      networkId: 255n,
      requiredObservers: [Buffer.alloc(28, 1)],
    },
    wrongful: { requiredObservers: [Buffer.alloc(28, 1)] },
  },
  {
    arm: "ObserverOrderInvalid",
    category: "observerOrderInvalid",
    replayer: OBSERVER_ORDER_INVALID_COMPLETE_CANONICAL_REPLAY,
    reason: { ObserverOrderInvalid: { observer_index: 1n } },
    accepted: { requiredObservers: [Buffer.alloc(28, 2), Buffer.alloc(28, 1)] },
    wrongful: { requiredObservers: [Buffer.alloc(28, 1), Buffer.alloc(28, 2)] },
  },
];
