import { FRAUD_PROOF_CATALOGUE_CATEGORY_ORDER } from "@al-ft/midgard-sdk";
import type { LucidEvolution, Network } from "@lucid-evolution/lucid";

import {
  CANONICAL_DECODABILITY_COMPLETE_CANONICAL_REPLAY,
  COMMITTED_FIELD_SHAPE_COMPLETE_CANONICAL_REPLAY,
  createCompleteCanonicalReplayUnion,
  createFabricatedDepositCompleteCanonicalReplay,
  createFabricatedWithdrawalCompleteCanonicalReplay,
  CROSS_BLOCK_DUPLICATE_EVENT_COMPLETE_CANONICAL_REPLAY,
  DA_HASH_PREIMAGE_COMPLETE_CANONICAL_REPLAY,
  DISTINCT_ASSET_ACCUMULATION_LIMIT_COMPLETE_CANONICAL_REPLAY,
  DOUBLE_SPEND_COMPLETE_CANONICAL_REPLAY,
  DOUBLE_WITHDRAW_COMPLETE_CANONICAL_REPLAY,
  EXECUTION_NATIVE_SCRIPT_INVALID_COMPLETE_CANONICAL_REPLAY,
  EXECUTION_SOURCE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
  FIELD_ITEM_WIDTH_ILLEGAL_COMPLETE_CANONICAL_REPLAY,
  FIELD_PREIMAGE_LENGTH_MISMATCH_COMPLETE_CANONICAL_REPLAY,
  INPUT_NO_IDX_COMPLETE_CANONICAL_REPLAY,
  INPUT_SET_UNIQUENESS_COMPLETE_CANONICAL_REPLAY,
  INVALID_RANGE_COMPLETE_CANONICAL_REPLAY,
  INVALID_SIGNATURE_COMPLETE_CANONICAL_REPLAY,
  L2_TX_MISTAG_COMPLETE_CANONICAL_REPLAY,
  MIN_ADA_COMPLETE_CANONICAL_REPLAY,
  MIN_FEE_COMPLETE_CANONICAL_REPLAY,
  MINT_AUTHORIZATION_COMPLETE_CANONICAL_REPLAY,
  MINT_DECLARED_ASSET_LIMIT_COMPLETE_CANONICAL_REPLAY,
  MISSING_NATIVE_SCRIPT_TX_COMPLETE_CANONICAL_REPLAY,
  MISSING_NATIVE_SCRIPT_UTXO_COMPLETE_CANONICAL_REPLAY,
  MISSING_REDEEMER_COMPLETE_CANONICAL_REPLAY,
  MISSING_SCRIPT_SOURCE_COMPLETE_CANONICAL_REPLAY,
  MISSING_SIGNATURE_COMPLETE_CANONICAL_REPLAY,
  NATIVE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
  NATIVE_SCRIPT_INVALID_COMPLETE_CANONICAL_REPLAY,
  NETWORK_ID_COMPLETE_CANONICAL_REPLAY,
  NO_REFERENCE_INPUT_COMPLETE_CANONICAL_REPLAY,
  NON_EXISTENT_INPUT_COMPLETE_CANONICAL_REPLAY,
  OBSERVER_ORDER_INVALID_COMPLETE_CANONICAL_REPLAY,
  OBSERVERS_FORBIDDEN_ON_UNTAGGED_NETWORK_COMPLETE_CANONICAL_REPLAY,
  OUTPUT_REFERENCE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
  PROTECTED_OUTPUT_SIGNER_MISSING_COMPLETE_CANONICAL_REPLAY,
  RECEIVE_PURPOSE_LANGUAGE_COMPLETE_CANONICAL_REPLAY,
  REDEEMER_CANONICITY_COMPLETE_CANONICAL_REPLAY,
  REFERENCE_INPUT_NO_IDX_COMPLETE_CANONICAL_REPLAY,
  RESOLVED_OUTPUT_NON_CANONICAL_COMPLETE_CANONICAL_REPLAY,
  SCRIPT_INTEGRITY_HASH_MISMATCH_COMPLETE_CANONICAL_REPLAY,
  SCRIPT_INTEGRITY_HASH_MISSING_COMPLETE_CANONICAL_REPLAY,
  SPEND_INPUT_SIGNER_MISSING_COMPLETE_CANONICAL_REPLAY,
  TRANSACTION_OUTPUT_NON_CANONICAL_COMPLETE_CANONICAL_REPLAY,
  TRANSITION_TRACE_COMPLETE_CANONICAL_REPLAY,
  UNUSED_REDEEMER_COMPLETE_CANONICAL_REPLAY,
  UNUSED_SCRIPT_WITNESS_COMPLETE_CANONICAL_REPLAY,
  VALIDATION_TRACE_DISPUTE_COMPLETE_CANONICAL_REPLAY,
  VALUE_NOT_PRESERVED_COMPLETE_CANONICAL_REPLAY,
  WITHDRAWAL_MISTAG_COMPLETE_CANONICAL_REPLAY,
  WITHDRAWN_INPUT_COMPLETE_CANONICAL_REPLAY,
  WITHDRAWN_REFERENCE_INPUT_COMPLETE_CANONICAL_REPLAY,
  WITNESS_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
  ZERO_INPUT_COMPLETE_CANONICAL_REPLAY,
} from "./complete-replay.js";
import { createFabricatedDepositEvidenceAuthority } from "./fabricated-deposit-evidence.js";
import { createFabricatedWithdrawalEvidenceAuthority } from "./fabricated-withdrawal-evidence.js";

/** The complete installed catalogue, with live event evidence and per-header replay context. */
export const createCatalogueCompleteCanonicalReplay = (input: {
  readonly lucid: LucidEvolution;
  readonly network: Network;
  readonly hubOraclePolicyId: string;
  readonly minimumConfirmationDepth: number;
  readonly owner: string;
}) => {
  const deposit = createFabricatedDepositEvidenceAuthority(input);
  const withdrawal = createFabricatedWithdrawalEvidenceAuthority(input);
  const replay = createCompleteCanonicalReplayUnion([
    DOUBLE_SPEND_COMPLETE_CANONICAL_REPLAY,
    NON_EXISTENT_INPUT_COMPLETE_CANONICAL_REPLAY,
    INPUT_NO_IDX_COMPLETE_CANONICAL_REPLAY,
    INVALID_RANGE_COMPLETE_CANONICAL_REPLAY,
    TRANSITION_TRACE_COMPLETE_CANONICAL_REPLAY,
    ZERO_INPUT_COMPLETE_CANONICAL_REPLAY,
    VALIDATION_TRACE_DISPUTE_COMPLETE_CANONICAL_REPLAY,
    DA_HASH_PREIMAGE_COMPLETE_CANONICAL_REPLAY,
    NO_REFERENCE_INPUT_COMPLETE_CANONICAL_REPLAY,
    REFERENCE_INPUT_NO_IDX_COMPLETE_CANONICAL_REPLAY,
    INVALID_SIGNATURE_COMPLETE_CANONICAL_REPLAY,
    createFabricatedDepositCompleteCanonicalReplay({
      authority: deposit,
      owner: input.owner,
    }),
    createFabricatedWithdrawalCompleteCanonicalReplay({
      authority: withdrawal,
      owner: input.owner,
    }),
    NATIVE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
    MISSING_SIGNATURE_COMPLETE_CANONICAL_REPLAY,
    MISSING_NATIVE_SCRIPT_TX_COMPLETE_CANONICAL_REPLAY,
    WITHDRAWN_REFERENCE_INPUT_COMPLETE_CANONICAL_REPLAY,
    CANONICAL_DECODABILITY_COMPLETE_CANONICAL_REPLAY,
    COMMITTED_FIELD_SHAPE_COMPLETE_CANONICAL_REPLAY,
    MIN_FEE_COMPLETE_CANONICAL_REPLAY,
    WITHDRAWAL_MISTAG_COMPLETE_CANONICAL_REPLAY,
    DOUBLE_WITHDRAW_COMPLETE_CANONICAL_REPLAY,
    CROSS_BLOCK_DUPLICATE_EVENT_COMPLETE_CANONICAL_REPLAY,
    L2_TX_MISTAG_COMPLETE_CANONICAL_REPLAY,
    WITHDRAWN_INPUT_COMPLETE_CANONICAL_REPLAY,
    VALUE_NOT_PRESERVED_COMPLETE_CANONICAL_REPLAY,
    INPUT_SET_UNIQUENESS_COMPLETE_CANONICAL_REPLAY,
    MINT_AUTHORIZATION_COMPLETE_CANONICAL_REPLAY,
    NETWORK_ID_COMPLETE_CANONICAL_REPLAY,
    MISSING_NATIVE_SCRIPT_UTXO_COMPLETE_CANONICAL_REPLAY,
    NATIVE_SCRIPT_INVALID_COMPLETE_CANONICAL_REPLAY,
    MIN_ADA_COMPLETE_CANONICAL_REPLAY,
    FIELD_PREIMAGE_LENGTH_MISMATCH_COMPLETE_CANONICAL_REPLAY,
    FIELD_ITEM_WIDTH_ILLEGAL_COMPLETE_CANONICAL_REPLAY,
    WITNESS_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
    SCRIPT_INTEGRITY_HASH_MISSING_COMPLETE_CANONICAL_REPLAY,
    TRANSACTION_OUTPUT_NON_CANONICAL_COMPLETE_CANONICAL_REPLAY,
    RESOLVED_OUTPUT_NON_CANONICAL_COMPLETE_CANONICAL_REPLAY,
    MINT_DECLARED_ASSET_LIMIT_COMPLETE_CANONICAL_REPLAY,
    SPEND_INPUT_SIGNER_MISSING_COMPLETE_CANONICAL_REPLAY,
    PROTECTED_OUTPUT_SIGNER_MISSING_COMPLETE_CANONICAL_REPLAY,
    OBSERVERS_FORBIDDEN_ON_UNTAGGED_NETWORK_COMPLETE_CANONICAL_REPLAY,
    OBSERVER_ORDER_INVALID_COMPLETE_CANONICAL_REPLAY,
    REDEEMER_CANONICITY_COMPLETE_CANONICAL_REPLAY,
    OUTPUT_REFERENCE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
    EXECUTION_SOURCE_SCRIPT_DECODING_COMPLETE_CANONICAL_REPLAY,
    RECEIVE_PURPOSE_LANGUAGE_COMPLETE_CANONICAL_REPLAY,
    UNUSED_SCRIPT_WITNESS_COMPLETE_CANONICAL_REPLAY,
    MISSING_SCRIPT_SOURCE_COMPLETE_CANONICAL_REPLAY,
    MISSING_REDEEMER_COMPLETE_CANONICAL_REPLAY,
    UNUSED_REDEEMER_COMPLETE_CANONICAL_REPLAY,
    EXECUTION_NATIVE_SCRIPT_INVALID_COMPLETE_CANONICAL_REPLAY,
    SCRIPT_INTEGRITY_HASH_MISMATCH_COMPLETE_CANONICAL_REPLAY,
    DISTINCT_ASSET_ACCUMULATION_LIMIT_COMPLETE_CANONICAL_REPLAY,
  ]);
  if (
    replay.launchScope.length !== FRAUD_PROOF_CATALOGUE_CATEGORY_ORDER.length ||
    replay.launchScope.some(
      (category, index) =>
        category !== FRAUD_PROOF_CATALOGUE_CATEGORY_ORDER[index],
    )
  )
    throw new Error("Catalogue replay omits or reorders an installed category");
  return replay;
};
