import { type FraudProofCatalogueCategoryName } from "@al-ft/midgard-sdk";

import {
  FIELD_ITEM_WIDTH_ILLEGAL_FAMILY_APPLICATION_RECORD,
  FIELD_PREIMAGE_LENGTH_MISMATCH_FAMILY_APPLICATION_RECORD,
  OUTPUT_REFERENCE_SCRIPT_DECODING_FAMILY_APPLICATION_RECORD,
  PROTECTED_OUTPUT_SIGNER_MISSING_FAMILY_APPLICATION_RECORD,
  TRANSACTION_OUTPUT_NON_CANONICAL_FAMILY_APPLICATION_RECORD,
  WITNESS_SCRIPT_DECODING_FAMILY_APPLICATION_RECORD,
} from "./family-application-registry.authenticated-certificate-family-application-record.js";
import {
  CROSS_BLOCK_DUPLICATE_EVENT_FAMILY_APPLICATION_RECORD,
  EXECUTION_NATIVE_SCRIPT_INVALID_FAMILY_APPLICATION_RECORD,
  MIN_ADA_FAMILY_APPLICATION_RECORD,
  MINT_AUTHORIZATION_FAMILY_APPLICATION_RECORD,
  MINT_ITEM_NON_CANONICAL_FAMILY_APPLICATION_RECORD,
  NATIVE_SCRIPT_DECODING_FAMILY_APPLICATION_RECORD,
  NATIVE_SCRIPT_INVALID_FAMILY_APPLICATION_RECORD,
  RESOLVED_OUTPUT_NON_CANONICAL_FAMILY_APPLICATION_RECORD,
  SPEND_INPUT_SIGNER_MISSING_FAMILY_APPLICATION_RECORD,
  TRANSITION_TRACE_FAMILY_APPLICATION_RECORD,
  WITHDRAWAL_MISTAG_FAMILY_APPLICATION_RECORD,
} from "./family-application-registry.bundle-cursor-family-application-record.js";
import {
  DISTINCT_ASSET_ACCUMULATION_LIMIT_FAMILY_APPLICATION_RECORD,
  EXECUTION_SOURCE_SCRIPT_DECODING_FAMILY_APPLICATION_RECORD,
  MINT_DECLARED_ASSET_LIMIT_FAMILY_APPLICATION_RECORD,
  MISSING_REDEEMER_FAMILY_APPLICATION_RECORD,
  MISSING_SCRIPT_SOURCE_FAMILY_APPLICATION_RECORD,
  OBSERVER_ORDER_INVALID_FAMILY_APPLICATION_RECORD,
  OBSERVERS_FORBIDDEN_ON_UNTAGGED_NETWORK_FAMILY_APPLICATION_RECORD,
  RECEIVE_PURPOSE_LANGUAGE_FAMILY_APPLICATION_RECORD,
  REDEEMER_CANONICITY_FAMILY_APPLICATION_RECORD,
  SCRIPT_INTEGRITY_HASH_MISMATCH_FAMILY_APPLICATION_RECORD,
  SCRIPT_INTEGRITY_HASH_MISSING_FAMILY_APPLICATION_RECORD,
  UNUSED_REDEEMER_FAMILY_APPLICATION_RECORD,
  UNUSED_SCRIPT_WITNESS_FAMILY_APPLICATION_RECORD,
} from "./family-application-registry.decision-digest-cursor-family-application-record.js";
import {
  DOUBLE_SPEND_FAMILY_APPLICATION_RECORD,
  LINEAR_FAMILY_APPLICATION_RECORDS,
} from "./family-application-registry.linear-family-application-record.js";
import {
  type FamilyApplicationRegistryEntry,
  MISSING_SIGNATURE_FAMILY_APPLICATION_RECORD,
  NETWORK_ID_FAMILY_APPLICATION_RECORD,
  VALIDATION_TRACE_DISPUTE_FAMILY_APPLICATION_RECORD,
  VALUE_NOT_PRESERVED_FAMILY_APPLICATION_RECORD,
} from "./family-application-registry.value-not-preserved-family-application-record.js";

/**
 * Every catalogue category's record, keyed by the record's own category: an
 * omitted or misnamed family fails typecheck here.
 */
export const FAMILY_APPLICATION_REGISTRY: {
  readonly [Category in FraudProofCatalogueCategoryName]: FamilyApplicationRegistryEntry<Category>;
} = Object.freeze({
  ...LINEAR_FAMILY_APPLICATION_RECORDS,
  doubleSpend: DOUBLE_SPEND_FAMILY_APPLICATION_RECORD,
  distinctAssetAccumulationLimit:
    DISTINCT_ASSET_ACCUMULATION_LIMIT_FAMILY_APPLICATION_RECORD,
  executionSourceScriptDecoding:
    EXECUTION_SOURCE_SCRIPT_DECODING_FAMILY_APPLICATION_RECORD,
  missingScriptSource: MISSING_SCRIPT_SOURCE_FAMILY_APPLICATION_RECORD,
  receivePurposeLanguage: RECEIVE_PURPOSE_LANGUAGE_FAMILY_APPLICATION_RECORD,
  scriptIntegrityHashMismatch:
    SCRIPT_INTEGRITY_HASH_MISMATCH_FAMILY_APPLICATION_RECORD,
  unusedRedeemer: UNUSED_REDEEMER_FAMILY_APPLICATION_RECORD,
  mintDeclaredAssetLimit: MINT_DECLARED_ASSET_LIMIT_FAMILY_APPLICATION_RECORD,
  missingRedeemer: MISSING_REDEEMER_FAMILY_APPLICATION_RECORD,
  observerOrderInvalid: OBSERVER_ORDER_INVALID_FAMILY_APPLICATION_RECORD,
  observersForbiddenOnUntaggedNetwork:
    OBSERVERS_FORBIDDEN_ON_UNTAGGED_NETWORK_FAMILY_APPLICATION_RECORD,
  redeemerCanonicity: REDEEMER_CANONICITY_FAMILY_APPLICATION_RECORD,
  scriptIntegrityHashMissing:
    SCRIPT_INTEGRITY_HASH_MISSING_FAMILY_APPLICATION_RECORD,
  unusedScriptWitness: UNUSED_SCRIPT_WITNESS_FAMILY_APPLICATION_RECORD,
  fieldItemWidthIllegal: FIELD_ITEM_WIDTH_ILLEGAL_FAMILY_APPLICATION_RECORD,
  fieldPreimageLengthMismatch:
    FIELD_PREIMAGE_LENGTH_MISMATCH_FAMILY_APPLICATION_RECORD,
  outputReferenceScriptDecoding:
    OUTPUT_REFERENCE_SCRIPT_DECODING_FAMILY_APPLICATION_RECORD,
  protectedOutputSignerMissing:
    PROTECTED_OUTPUT_SIGNER_MISSING_FAMILY_APPLICATION_RECORD,
  transactionOutputNonCanonical:
    TRANSACTION_OUTPUT_NON_CANONICAL_FAMILY_APPLICATION_RECORD,
  witnessScriptDecoding: WITNESS_SCRIPT_DECODING_FAMILY_APPLICATION_RECORD,
  mintItemNonCanonical: MINT_ITEM_NON_CANONICAL_FAMILY_APPLICATION_RECORD,
  nativeScriptInvalid: NATIVE_SCRIPT_INVALID_FAMILY_APPLICATION_RECORD,
  nativeScriptDecoding: NATIVE_SCRIPT_DECODING_FAMILY_APPLICATION_RECORD,
  mintAuthorization: MINT_AUTHORIZATION_FAMILY_APPLICATION_RECORD,
  withdrawalMistag: WITHDRAWAL_MISTAG_FAMILY_APPLICATION_RECORD,
  minAda: MIN_ADA_FAMILY_APPLICATION_RECORD,
  transitionTrace: TRANSITION_TRACE_FAMILY_APPLICATION_RECORD,
  crossBlockDuplicateEvent:
    CROSS_BLOCK_DUPLICATE_EVENT_FAMILY_APPLICATION_RECORD,
  resolvedOutputNonCanonical:
    RESOLVED_OUTPUT_NON_CANONICAL_FAMILY_APPLICATION_RECORD,
  spendInputSignerMissing: SPEND_INPUT_SIGNER_MISSING_FAMILY_APPLICATION_RECORD,
  executionNativeScriptInvalid:
    EXECUTION_NATIVE_SCRIPT_INVALID_FAMILY_APPLICATION_RECORD,
  missingSignature: MISSING_SIGNATURE_FAMILY_APPLICATION_RECORD,
  networkId: NETWORK_ID_FAMILY_APPLICATION_RECORD,
  valueNotPreserved: VALUE_NOT_PRESERVED_FAMILY_APPLICATION_RECORD,
  validationTraceDispute: VALIDATION_TRACE_DISPUTE_FAMILY_APPLICATION_RECORD,
});
