import "./validation-trace-dispute.validation-trace-semantic-resolver-group-sizes.js";

export const VALIDATION_TRACE_DISPUTE_FAULT_PROOF_TITLES = {
  proofItem: "fraud_proofs/validation_trace/proof_item_v1.main.else",
  dispute: "fraud_proofs/validation_trace/dispute_v1.main.spend",
  source: "fraud_proofs/validation_trace/source_v1.main.spend",
  game: "fraud_proofs/validation_trace/game_v1.main.spend",
  boundary: "fraud_proofs/validation_trace/boundary_v1.main.spend",
  timeout: "fraud_proofs/validation_trace/timeout_v1.main.spend",
  award: "fraud_proofs/validation_trace/award_v1.main.spend",
  canonicalDecodeItemStages: {
    source:
      "fraud_proofs/validation_trace/canonical_decode_item_source_v1.main.spend",
    observe:
      "fraud_proofs/validation_trace/canonical_decode_item_observe_v1.main.spend",
    proof:
      "fraud_proofs/validation_trace/canonical_decode_item_proof_v1.main.spend",
    settlement:
      "fraud_proofs/validation_trace/canonical_decode_item_settlement_v1.main.spend",
  },
  scriptSourcesStageOneRedeemerStages: {
    sourceAuthenticator:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_source_authenticator.main.spend",
    openHeaderExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_open_header_executor.main.spend",
    openTailExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_open_tail_executor.main.spend",
    headScalarExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_head_scalar_executor.main.spend",
    headSequenceExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_head_sequence_executor.main.spend",
    headMapExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_head_map_executor.main.spend",
    headLargeConstructorExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_head_large_constructor_executor.main.spend",
    attachIntegerExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_attach_integer_executor.main.spend",
    attachBytesExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_attach_bytes_executor.main.spend",
    foldListExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_fold_list_executor.main.spend",
    advanceIntegerExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_advance_integer_executor.main.spend",
    advanceBytesExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_advance_bytes_executor.main.spend",
    advanceLargeConstructorExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_advance_large_constructor_executor.main.spend",
    advanceLargeFieldsExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_advance_large_fields_executor.main.spend",
    closeExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_close_executor.main.spend",
    finishDataExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_finish_data_executor.main.spend",
    invalidHeaderExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_invalid_header_executor.main.spend",
    invalidTailExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_invalid_tail_executor.main.spend",
    envelope:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_envelope_v1.main.spend",
    traversalNormalizer:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_traversal_normalizer_v1.main.spend",
    outerNormalizer:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_outer_normalizer_v1.main.spend",
    foldMapExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_fold_map_executor_v1.main.spend",
    finalizeFrameExecutor:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_finalize_frame_executor_v1.main.spend",
    settlement:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_execution_settlement_v1.main.spend",
  },
  prepares: {
    canonicalDecode:
      "fraud_proofs/validation_trace/canonical_decode_v1.main.spend",
    compactBinding:
      "fraud_proofs/validation_trace/compact_binding_v1.main.spend",
    staticLedgerRules:
      "fraud_proofs/validation_trace/static_ledger_rules_v1.main.spend",
    inputSets: "fraud_proofs/validation_trace/input_sets_v1.main.spend",
    signatures: "fraud_proofs/validation_trace/signatures_v1.main.spend",
    phaseANativeScripts:
      "fraud_proofs/validation_trace/phase_a_native_scripts_v1.main.spend",
    phaseAScriptPreconditions:
      "fraud_proofs/validation_trace/phase_a_script_preconditions_v1.main.spend",
    resolveInputs: "fraud_proofs/validation_trace/resolve_inputs_v1.main.spend",
    scriptSources: "fraud_proofs/validation_trace/script_sources_v1.main.spend",
    nativeScripts: "fraud_proofs/validation_trace/native_scripts_v1.main.spend",
    scriptIntegrity:
      "fraud_proofs/validation_trace/script_integrity_v1.main.spend",
    cek: "fraud_proofs/validation_trace/cek_v1.main.spend",
    valueAndMint: "fraud_proofs/validation_trace/value_and_mint_v1.main.spend",
    ledgerDelta: "fraud_proofs/validation_trace/ledger_delta_v1.main.spend",
  },
  semantics: {
    canonicalDecodeEmpty:
      "fraud_proofs/validation_trace/canonical_decode_empty_semantic_v1.main.spend",
    canonicalDecodeItem:
      "fraud_proofs/validation_trace/canonical_decode_item_semantic_v1.main.spend",
    compactBinding:
      "fraud_proofs/validation_trace/compact_binding_semantic_v1.main.spend",
    staticLedgerRules:
      "fraud_proofs/validation_trace/static_ledger_rules_semantic_v1.main.spend",
    inputSetsEmpty:
      "fraud_proofs/validation_trace/input_sets_empty_semantic_v1.main.spend",
    inputSetsItem:
      "fraud_proofs/validation_trace/input_sets_item_semantic_v1.main.spend",
    signaturesAdvance:
      "fraud_proofs/validation_trace/signatures_advance_semantic_v1.main.spend",
    signaturesAddressItem:
      "fraud_proofs/validation_trace/signatures_address_item_semantic_v1.main.spend",
    signaturesRequiredItem:
      "fraud_proofs/validation_trace/signatures_required_item_semantic_v1.main.spend",
    signaturesHandoff:
      "fraud_proofs/validation_trace/signatures_handoff_semantic_v1.main.spend",
    phaseANativeScriptsAdvance:
      "fraud_proofs/validation_trace/phase_a_native_scripts_advance_semantic_v1.main.spend",
    phaseANativeScriptsItem:
      "fraud_proofs/validation_trace/phase_a_native_scripts_item_semantic_v1.main.spend",
    phaseANativeScriptsTokenHead:
      "fraud_proofs/validation_trace/phase_a_native_scripts_token_head_semantic_v1.main.spend",
    phaseANativeScriptsAllOrAnyContainerFramePayload:
      "fraud_proofs/validation_trace/phase_a_native_scripts_all_or_any_container_frame_payload_semantic_v1.main.spend",
    phaseANativeScriptsAllOrAnyEmptyContainerPayload:
      "fraud_proofs/validation_trace/phase_a_native_scripts_all_or_any_empty_container_payload_semantic_v1.main.spend",
    phaseANativeScriptsAtLeastContainerFramePayload:
      "fraud_proofs/validation_trace/phase_a_native_scripts_at_least_container_frame_payload_semantic_v1.main.spend",
    phaseANativeScriptsAtLeastEmptyContainerPayload:
      "fraud_proofs/validation_trace/phase_a_native_scripts_at_least_empty_container_payload_semantic_v1.main.spend",
    phaseANativeScriptsTimelockPayload:
      "fraud_proofs/validation_trace/phase_a_native_scripts_timelock_payload_semantic_v1.main.spend",
    phaseANativeScriptsSignatureMembershipPayload:
      "fraud_proofs/validation_trace/phase_a_native_scripts_signature_membership_payload_semantic_v1.main.spend",
    phaseANativeScriptsSignatureEmptyPayload:
      "fraud_proofs/validation_trace/phase_a_native_scripts_signature_empty_payload_semantic_v1.main.spend",
    phaseANativeScriptsSignatureBelowFirstPayload:
      "fraud_proofs/validation_trace/phase_a_native_scripts_signature_below_first_payload_semantic_v1.main.spend",
    phaseANativeScriptsSignatureAboveLastPayload:
      "fraud_proofs/validation_trace/phase_a_native_scripts_signature_above_last_payload_semantic_v1.main.spend",
    phaseANativeScriptsSignatureBetweenPayload:
      "fraud_proofs/validation_trace/phase_a_native_scripts_signature_between_payload_semantic_v1.main.spend",
    phaseANativeScriptsFrame:
      "fraud_proofs/validation_trace/phase_a_native_scripts_frame_semantic_v1.main.spend",
    phaseAScriptPreconditions:
      "fraud_proofs/validation_trace/phase_a_script_preconditions_semantic_v1.main.spend",
    phaseAScriptPreconditionsItem:
      "fraud_proofs/validation_trace/phase_a_script_preconditions_item_semantic_v1.main.spend",
    resolveInputsInitial:
      "fraud_proofs/validation_trace/resolve_inputs_initial_semantic_v1.main.spend",
    resolveInputsFinish:
      "fraud_proofs/validation_trace/resolve_inputs_finish_semantic_v1.main.spend",
    resolveInputsMembershipBegin:
      "fraud_proofs/validation_trace/resolve_inputs_membership_begin_semantic_v1.main.spend",
    resolveInputsMembershipStep:
      "fraud_proofs/validation_trace/resolve_inputs_membership_step_semantic_v1.main.spend",
    resolveInputsMembershipFinalize:
      "fraud_proofs/validation_trace/resolve_inputs_membership_finalize_semantic_v1.main.spend",
    resolveInputsNonMembership:
      "fraud_proofs/validation_trace/resolve_inputs_non_membership_semantic_v1.main.spend",
    scriptSourcesNonOutput:
      "fraud_proofs/validation_trace/script_sources_non_output_semantic_v1.main.spend",
    scriptSourcesOutputProofBegin:
      "fraud_proofs/validation_trace/script_sources_output_proof_begin_semantic_v1.main.spend",
    scriptSourcesOutputProofStep:
      "fraud_proofs/validation_trace/script_sources_output_proof_step_semantic_v1.main.spend",
    scriptSourcesOutputProofFinalize:
      "fraud_proofs/validation_trace/script_sources_output_proof_finalize_semantic_v1.main.spend",
    scriptSourcesOutputProofFinish:
      "fraud_proofs/validation_trace/script_sources_output_proof_finish_semantic_v1.main.spend",
    scriptSourcesStageZeroBegin:
      "fraud_proofs/validation_trace/script_sources_stage_zero_begin_semantic_v1.main.spend",
    scriptSourcesStageZeroFinish:
      "fraud_proofs/validation_trace/script_sources_stage_zero_finish_semantic_v1.main.spend",
    scriptSourcesStageZeroHashBlock:
      "fraud_proofs/validation_trace/script_sources_stage_zero_hash_block_semantic_v1.main.spend",
    scriptSourcesStageZeroHashAdvance:
      "fraud_proofs/validation_trace/script_sources_stage_zero_hash_advance_semantic_v1.main.spend",
    scriptSourcesStageZeroHashTerminal:
      "fraud_proofs/validation_trace/script_sources_stage_zero_hash_terminal_semantic_v1.main.spend",
    scriptSourcesStageNineMismatch:
      "fraud_proofs/validation_trace/script_sources_stage_nine_mismatch_semantic_v1.main.spend",
    scriptSourcesStageNineNativeMatch:
      "fraud_proofs/validation_trace/script_sources_stage_nine_native_match_semantic_v1.main.spend",
    scriptSourcesStageNineEffectfulMatch:
      "fraud_proofs/validation_trace/script_sources_stage_nine_effectful_match_semantic_v1.main.spend",
    scriptSourcesStageNineMissing:
      "fraud_proofs/validation_trace/script_sources_stage_nine_missing_semantic_v1.main.spend",
    scriptSourcesStageOneFinish:
      "fraud_proofs/validation_trace/script_sources_stage_one_finish_semantic_v1.main.spend",
    scriptSourcesStageOneRedeemer:
      "fraud_proofs/validation_trace/script_sources_stage_one_redeemer_semantic_v1.main.spend",
    scriptSourcesStageElevenFinish:
      "fraud_proofs/validation_trace/script_sources_stage_eleven_finish_semantic_v1.main.spend",
    scriptSourcesStageElevenSource:
      "fraud_proofs/validation_trace/script_sources_stage_eleven_source_semantic_v1.main.spend",
    scriptSourcesStageTwelveFinish:
      "fraud_proofs/validation_trace/script_sources_stage_twelve_finish_semantic_v1.main.spend",
    scriptSourcesStageTwelveRedeemer:
      "fraud_proofs/validation_trace/script_sources_stage_twelve_redeemer_semantic_v1.main.spend",
    scriptSourcesStageTenMissing:
      "fraud_proofs/validation_trace/script_sources_stage_ten_missing_semantic_v1.main.spend",
    scriptSourcesStageTenMismatch:
      "fraud_proofs/validation_trace/script_sources_stage_ten_mismatch_semantic_v1.main.spend",
    scriptSourcesStageTenMatch:
      "fraud_proofs/validation_trace/script_sources_stage_ten_match_semantic_v1.main.spend",
    scriptSourcesStageEightFinish:
      "fraud_proofs/validation_trace/script_sources_stage_eight_finish_semantic_v1.main.spend",
    scriptSourcesStageEightPurpose:
      "fraud_proofs/validation_trace/script_sources_stage_eight_purpose_semantic_v1.main.spend",
    scriptSourcesStageSevenObserver:
      "fraud_proofs/validation_trace/script_sources_stage_seven_observer_semantic_v1.main.spend",
    scriptSourcesStageSevenReceive:
      "fraud_proofs/validation_trace/script_sources_stage_seven_receive_semantic_v1.main.spend",
    scriptSourcesStageSevenFinish:
      "fraud_proofs/validation_trace/script_sources_stage_seven_finish_semantic_v1.main.spend",
    nativeScriptsTerminal:
      "fraud_proofs/validation_trace/native_scripts_terminal_semantic_v1.main.spend",
    nativeScriptsNative:
      "fraud_proofs/validation_trace/native_scripts_native_semantic_v1.main.spend",
    nativeScriptsEffectful:
      "fraud_proofs/validation_trace/native_scripts_effectful_semantic_v1.main.spend",
    scriptIntegrityAuthentication:
      "fraud_proofs/validation_trace/script_integrity_authentication_semantic_v1.main.spend",
    scriptIntegrityCompact:
      "fraud_proofs/validation_trace/script_integrity_compact_semantic_v1.main.spend",
    scriptIntegrityWitnessSet:
      "fraud_proofs/validation_trace/script_integrity_witness_set_semantic_v1.main.spend",
    scriptIntegrityFinalize:
      "fraud_proofs/validation_trace/script_integrity_finalize_semantic_v1.main.spend",
    cekFinish:
      "fraud_proofs/validation_trace/cek_finish_semantic_v1.main.spend",
    cekExecutionSelection:
      "fraud_proofs/validation_trace/cek_execution_selection_semantic_v1.main.spend",
    cekContextStep:
      "fraud_proofs/validation_trace/cek_context_step_semantic_v1.main.spend",
    cekCoreStep:
      "fraud_proofs/validation_trace/cek_core_step_semantic_v1.main.spend",
    valueAndMintBegin:
      "fraud_proofs/validation_trace/value_and_mint_begin_semantic_v1.main.spend",
    valueAndMintReplayBegin:
      "fraud_proofs/validation_trace/value_and_mint_replay_begin_semantic_v1.main.spend",
    valueAndMintReplayInput:
      "fraud_proofs/validation_trace/value_and_mint_replay_input_semantic_v1.main.spend",
    valueAndMintReplayAsset:
      "fraud_proofs/validation_trace/value_and_mint_replay_asset_semantic_v1.main.spend",
    valueAndMintReplayFinish:
      "fraud_proofs/validation_trace/value_and_mint_replay_finish_semantic_v1.main.spend",
    valueAndMintOutputDescriptor:
      "fraud_proofs/validation_trace/value_and_mint_output_descriptor_semantic_v1.main.spend",
    valueAndMintOutputAsset:
      "fraud_proofs/validation_trace/value_and_mint_output_asset_semantic_v1.main.spend",
    valueAndMintOutputFinish:
      "fraud_proofs/validation_trace/value_and_mint_output_finish_semantic_v1.main.spend",
    valueAndMintMintAsset:
      "fraud_proofs/validation_trace/value_and_mint_mint_asset_semantic_v1.main.spend",
    valueAndMintMintFinish:
      "fraud_proofs/validation_trace/value_and_mint_mint_finish_semantic_v1.main.spend",
    valueAndMintFinalize:
      "fraud_proofs/validation_trace/value_and_mint_finalize_semantic_v1.main.spend",
    ledgerDeltaOperation:
      "fraud_proofs/validation_trace/ledger_delta_operation_semantic_v1.main.spend",
    ledgerDeltaReplay:
      "fraud_proofs/validation_trace/ledger_delta_replay_semantic_v1.main.spend",
    ledgerDeltaReplayFinish:
      "fraud_proofs/validation_trace/ledger_delta_replay_finish_semantic_v1.main.spend",
    ledgerDeltaOutput:
      "fraud_proofs/validation_trace/ledger_delta_output_semantic_v1.main.spend",
    ledgerDeltaOutputFinish:
      "fraud_proofs/validation_trace/ledger_delta_output_finish_semantic_v1.main.spend",
    ledgerDeltaProofFrame:
      "fraud_proofs/validation_trace/ledger_delta_proof_frame_semantic_v1.main.spend",
    ledgerDeltaFinalize:
      "fraud_proofs/validation_trace/ledger_delta_finalize_semantic_v1.main.spend",
    ledgerDeltaTerminal:
      "fraud_proofs/validation_trace/ledger_delta_terminal_semantic_v1.main.spend",
  },
  yields: {
    scriptSourcesStageTwoAdvance:
      "fraud_proofs/validation_trace/script_sources_middle_yields_v1.stage_two_advance.withdraw",
    scriptSourcesStageThreeReplay:
      "fraud_proofs/validation_trace/script_sources_middle_yields_v1.stage_three_replay.withdraw",
    scriptSourcesStageThreeFinish:
      "fraud_proofs/validation_trace/script_sources_middle_yields_v1.stage_three_finish.withdraw",
    scriptSourcesStageFourBegin:
      "fraud_proofs/validation_trace/script_sources_middle_yields_v1.stage_four_begin.withdraw",
    scriptSourcesStageFourFinish:
      "fraud_proofs/validation_trace/script_sources_middle_yields_v1.stage_four_finish.withdraw",
    scriptSourcesStageSixBeginPolicy:
      "fraud_proofs/validation_trace/script_sources_middle_yields_v1.stage_six_begin_policy.withdraw",
    scriptSourcesStageSixFoldAsset:
      "fraud_proofs/validation_trace/script_sources_middle_yields_v1.stage_six_fold_asset.withdraw",
    scriptSourcesStageSixFinish:
      "fraud_proofs/validation_trace/script_sources_middle_yields_v1.stage_six_finish.withdraw",
    scriptSourcesObserverItem:
      "fraud_proofs/validation_trace/script_sources_stage_seven_observer_item_yield_v1.main.withdraw",
    scriptSourcesObserverBound:
      "fraud_proofs/validation_trace/script_sources_stage_seven_observer_bound_yield_v1.main.withdraw",
    scriptSourcesRedeemerDescriptor:
      "fraud_proofs/validation_trace/script_sources_redeemer_item_step_yield_v1.main.withdraw",
    ledgerOutputProofStructure:
      "fraud_proofs/validation_trace/ledger_output_proof_structure_yield.main.withdraw",
    ledgerOutputProofValue:
      "fraud_proofs/validation_trace/ledger_output_proof_value_yield.main.withdraw",
    ledgerOutputProofDatumFoldMap:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_fold_map_yield.main.withdraw",
    ledgerOutputProofDatumFinalizeFrame:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_finalize_frame_yield.main.withdraw",
    ledgerOutputProofDatumHeadScalar:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_head_scalar_yield.main.withdraw",
    ledgerOutputProofDatumAttachInteger:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_attach_integer_yield.main.withdraw",
    ledgerOutputProofDatumFoldList:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_fold_list_yield.main.withdraw",
    ledgerOutputProofDatumAdvanceInteger:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_advance_integer_yield.main.withdraw",
    ledgerOutputProofReferenceScript:
      "fraud_proofs/validation_trace/ledger_output_proof_reference_script_yield.main.withdraw",
    ledgerOutputProofScriptHash:
      "fraud_proofs/validation_trace/ledger_output_proof_script_hash_yield.main.withdraw",
    ledgerOutputProofNativeScript:
      "fraud_proofs/validation_trace/ledger_output_proof_native_script_yield.main.withdraw",
    ledgerOutputProofStructureAssets:
      "fraud_proofs/validation_trace/ledger_output_proof_structure_assets_yield.main.withdraw",
    ledgerOutputProofStructureOptional:
      "fraud_proofs/validation_trace/ledger_output_proof_structure_optional_yield.main.withdraw",
    ledgerOutputProofStructureFinish:
      "fraud_proofs/validation_trace/ledger_output_proof_structure_finish_yield.main.withdraw",
    ledgerOutputProofDatumHeadSequence:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_head_sequence_yield.main.withdraw",
    ledgerOutputProofDatumHeadMap:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_head_map_yield.main.withdraw",
    ledgerOutputProofDatumHeadLargeConstructor:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_head_large_constructor_yield.main.withdraw",
    ledgerOutputProofDatumAttachBytes:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_attach_bytes_yield.main.withdraw",
    ledgerOutputProofDatumAdvanceBytes:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_advance_bytes_yield.main.withdraw",
    ledgerOutputProofDatumFinish:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_finish_yield.main.withdraw",
    ledgerOutputProofDatumLargeConstructor:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_large_constructor_yield.main.withdraw",
    ledgerOutputProofDatumLargeFields:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_large_fields_yield.main.withdraw",
    ledgerOutputProofDatumClose:
      "fraud_proofs/validation_trace/ledger_output_proof_datum_close_yield.main.withdraw",
    ledgerOutputProofSpan:
      "fraud_proofs/validation_trace/ledger_output_proof_span_yield.main.withdraw",
    ledgerOutputProofScalarInteger:
      "fraud_proofs/validation_trace/ledger_output_proof_scalar_integer_yield.main.withdraw",
    ledgerOutputProofScalarBytes:
      "fraud_proofs/validation_trace/ledger_output_proof_scalar_bytes_yield.main.withdraw",
    ledgerOutputDescriptorScanFacts:
      "fraud_proofs/validation_trace/ledger_output_descriptor_scan_facts_yield.main.withdraw",
    ledgerOutputDescriptorReferenceScript:
      "fraud_proofs/validation_trace/ledger_output_descriptor_reference_script_yield.main.withdraw",
    ledgerOutputDescriptorDatumSummary:
      "fraud_proofs/validation_trace/ledger_output_descriptor_datum_summary_yield.main.withdraw",
    ledgerOutputDescriptorValueSummary:
      "fraud_proofs/validation_trace/ledger_output_descriptor_value_summary_yield.main.withdraw",
    phaseANativeItemNative:
      "fraud_proofs/validation_trace/phase_a_native_scripts_item_yields_v1.native.withdraw",
    phaseANativeItemForeign:
      "fraud_proofs/validation_trace/phase_a_native_scripts_item_yields_v1.foreign.withdraw",
    cekSelectionAuthenticate:
      "fraud_proofs/validation_trace/cek_execution_selection_yields.authenticate.withdraw",
    cekSelectionSuccessor:
      "fraud_proofs/validation_trace/cek_execution_selection_yields.successor.withdraw",
    cekSelectionMaterialProgram:
      "fraud_proofs/validation_trace/cek_execution_selection_yields.material_program.withdraw",
    cekSelectionMaterialData:
      "fraud_proofs/validation_trace/cek_execution_selection_yields.material_data.withdraw",
    valueAndMintAssetFold:
      "fraud_proofs/validation_trace/value_and_mint_asset_fold_yield.main.withdraw",
  },
} as const;
